/** 表格数据 */
export const tableData: ReportGroupInfo[] = [
	{
		groupId: "RG001",
		name: "基础数据报表组",
		url: "/reports/basic-data",
		remark: "包含基础业务数据的报表集合，用于日常运营分析",
	},
	{
		groupId: "RG002",
		name: "财务报表组",
		url: "/reports/financial",
		remark: "财务相关报表，包括收支、成本、利润等分析报表",
	},
	{
		groupId: "RG003",
		name: "用户行为报表组",
		url: "/reports/user-behavior",
		remark: "用户活跃度、行为路径、转化率等用户分析报表",
	},
	{
		groupId: "RG004",
		name: "销售业绩报表组",
		url: "/reports/sales-performance",
		remark: "销售数据、业绩统计、趋势分析等销售相关报表",
	},
	{
		groupId: "RG005",
		name: "运营监控报表组",
		url: "/reports/operation-monitor",
		remark: "系统运行状态、性能指标、异常监控等运营报表",
	},
	{
		groupId: "RG006",
		name: "市场分析报表组",
		url: "/reports/market-analysis",
		remark: "市场趋势、竞品分析、客户画像等市场研究报表",
	},
	{
		groupId: "RG007",
		name: "客户服务报表组",
		url: "/reports/customer-service",
		remark: "客户满意度、服务质量、投诉处理等客服相关报表",
	},
	{
		groupId: "RG008",
		name: "产品数据报表组",
		url: "/reports/product-data",
		remark: "产品使用情况、功能分析、版本对比等产品数据报表",
	},
	{
		groupId: "RG009",
		name: "库存管理报表组",
		url: "/reports/inventory-management",
		remark: "库存状态、进销存、周转率等库存管理相关报表",
	},
	{
		groupId: "RG010",
		name: "人力资源报表组",
		url: "/reports/human-resources",
		remark: "员工考勤、绩效评估、薪资统计等人力资源报表",
	},
	{
		groupId: "RG011",
		name: "风险控制报表组",
		url: "/reports/risk-control",
		remark: "风险识别、信用评估、合规检查等风险管理报表",
	},
	{
		groupId: "RG012",
		name: "质量管理报表组",
		url: "/reports/quality-management",
		remark: "质量检测、缺陷统计、改进追踪等质量管控报表",
	},
	{
		groupId: "RG013",
		name: "供应链报表组",
		url: "/reports/supply-chain",
		remark: "供应商评估、采购分析、物流跟踪等供应链管理报表",
	},
	{
		groupId: "RG014",
		name: "项目管理报表组",
		url: "/reports/project-management",
		remark: "项目进度、资源分配、成本控制等项目管理报表",
	},
	{
		groupId: "RG015",
		name: "数据质量报表组",
		url: "/reports/data-quality",
		remark: "数据完整性、一致性、准确性等数据质量监控报表",
	},
	{
		groupId: "RG016",
		name: "合规审计报表组",
		url: "/reports/compliance-audit",
		remark: "合规检查、审计跟踪、法规遵循等审计相关报表",
	},
	{
		groupId: "RG017",
		name: "技术运维报表组",
		url: "/reports/technical-ops",
		remark: "系统性能、服务器状态、网络监控等技术运维报表",
	},
	{
		groupId: "RG018",
		name: "营销活动报表组",
		url: "/reports/marketing-activities",
		remark: "活动效果、推广数据、ROI分析等营销活动报表",
	},
	{
		groupId: "RG019",
		name: "安全监控报表组",
		url: "/reports/security-monitoring",
		remark: "安全事件、威胁检测、访问控制等信息安全报表",
	},
	{
		groupId: "RG020",
		name: "环境监测报表组",
		url: "/reports/environment-monitoring",
		remark: "环境指标、能耗统计、污染监控等环境监测报表",
	},
	{
		groupId: "RG021",
		name: "设备维护报表组",
		url: "/reports/equipment-maintenance",
		remark: "设备状态、维修记录、保养计划等设备管理报表",
	},
	{
		groupId: "RG022",
		name: "培训教育报表组",
		url: "/reports/training-education",
		remark: "培训进度、学习效果、技能评估等教育培训报表",
	},
	{
		groupId: "RG023",
		name: "渠道分析报表组",
		url: "/reports/channel-analysis",
		remark: "渠道效果、合作伙伴、分销数据等渠道管理报表",
	},
	{
		groupId: "RG024",
		name: "成本核算报表组",
		url: "/reports/cost-accounting",
		remark: "成本分摊、预算对比、费用分析等成本核算报表",
	},
	{
		groupId: "RG025",
		name: "创新研发报表组",
		url: "/reports/innovation-rd",
		remark: "研发投入、专利申请、创新成果等研发管理报表",
	},
	{
		groupId: "RG026",
		name: "客户关系报表组",
		url: "/reports/customer-relationship",
		remark: "客户生命周期、忠诚度、流失分析等CRM相关报表",
	},
	{
		groupId: "RG027",
		name: "物流配送报表组",
		url: "/reports/logistics-delivery",
		remark: "配送效率、运输成本、物流轨迹等物流管理报表",
	},
	{
		groupId: "RG028",
		name: "业务流程报表组",
		url: "/reports/business-process",
		remark: "流程效率、瓶颈分析、优化建议等业务流程报表",
	},
	{
		groupId: "RG029",
		name: "数字化转型报表组",
		url: "/reports/digital-transformation",
		remark: "数字化程度、系统集成、转型效果等数字化报表",
	},
	{
		groupId: "RG030",
		name: "可持续发展报表组",
		url: "/reports/sustainable-development",
		remark: "ESG指标、社会责任、可持续发展等相关报表",
	},
	{
		groupId: "RG031",
		name: "智能分析报表组",
		url: "/reports/intelligent-analysis",
		remark: "AI预测、机器学习、智能推荐等智能化分析报表",
	},
	{
		groupId: "RG032",
		name: "区域业务报表组",
		url: "/reports/regional-business",
		remark: "区域分布、地理分析、本地化运营等区域业务报表",
	},
	{
		groupId: "RG033",
		name: "移动端数据报表组",
		url: "/reports/mobile-data",
		remark: "移动应用、用户行为、设备分析等移动端数据报表",
	},
	{
		groupId: "RG034",
		name: "社交媒体报表组",
		url: "/reports/social-media",
		remark: "社交影响力、内容传播、粉丝分析等社交媒体报表",
	},
	{
		groupId: "RG035",
		name: "综合仪表板报表组",
		url: "/reports/comprehensive-dashboard",
		remark: "综合性仪表板，集成各业务线关键指标的概览报表",
	},
];