/**
 * @file 楼栋结构图假数据
 * @description Building space structure diagram mock data
 */

import type { BuildingSpaceStructureDiagramListItem } from "@01s-11comm/type";

/**
 * 楼栋结构图模拟数据
 * Building space structure diagram mock data
 */
export const mockBuildingSpaceStructureDiagramData: BuildingSpaceStructureDiagramListItem[] = [
    {
        buildingId: "B001",
        buildingName: "A栋",
        totalFloors: 18,
        totalHouseholds: 72,
        buildingArea: 8640.5,
        buildingStructure: "钢筋混凝土结构",
        constructionYear: "2018",
        drawingPath: "/drawings/A栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-20 14:30:00",
        personInCharge: "张工程师",
        contactPhone: "138****8001",
        remarks: "结构稳定，无异常情况",
    },
    {
        buildingId: "B002",
        buildingName: "B栋",
        totalFloors: 22,
        totalHouseholds: 88,
        buildingArea: 10560.8,
        buildingStructure: "框架结构",
        constructionYear: "2020",
        drawingPath: "/drawings/B栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-18 10:15:00",
        personInCharge: "李工程师",
        contactPhone: "139****9002",
        remarks: "定期检查维护完成",
    },
    {
        buildingId: "B003",
        buildingName: "C栋",
        totalFloors: 15,
        totalHouseholds: 60,
        buildingArea: 7200.3,
        buildingStructure: "剪力墙结构",
        constructionYear: "2016",
        drawingPath: "/drawings/C栋_结构图_2024.pdf",
        status: "装修中",
        lastUpdateTime: "2024-11-15 16:45:00",
        personInCharge: "王工程师",
        contactPhone: "186****5678",
        remarks: "外墙装修施工中，预计12月完工",
    },
    {
        buildingId: "B004",
        buildingName: "D栋",
        totalFloors: 20,
        totalHouseholds: 80,
        buildingArea: 9600.7,
        buildingStructure: "钢筋混凝土结构",
        constructionYear: "2019",
        drawingPath: "/drawings/D栋_结构图_2024.pdf",
        status: "维修中",
        lastUpdateTime: "2024-11-12 09:20:00",
        personInCharge: "赵工程师",
        contactPhone: "159****3456",
        remarks: "电梯维护中，预计维修期7天",
    },
    {
        buildingId: "B005",
        buildingName: "E栋",
        totalFloors: 25,
        totalHouseholds: 100,
        buildingArea: 12000.9,
        buildingStructure: "钢结构",
        constructionYear: "2021",
        drawingPath: "/drawings/E栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-20 11:30:00",
        personInCharge: "陈工程师",
        contactPhone: "135****8901",
        remarks: "新建高档住宅，设施完善",
    },
    {
        buildingId: "B006",
        buildingName: "F栋",
        totalFloors: 12,
        totalHouseholds: 48,
        buildingArea: 5760.4,
        buildingStructure: "砖混结构",
        constructionYear: "2014",
        drawingPath: "/drawings/F栋_结构图_2024.pdf",
        status: "待验收",
        lastUpdateTime: "2024-11-10 14:50:00",
        personInCharge: "周工程师",
        contactPhone: "188****2346",
        remarks: "改造工程完工，等待最终验收",
    },
    {
        buildingId: "B007",
        buildingName: "G栋",
        totalFloors: 28,
        totalHouseholds: 112,
        buildingArea: 13440.6,
        buildingStructure: "框架结构",
        constructionYear: "2022",
        drawingPath: "/drawings/G栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-19 15:20:00",
        personInCharge: "吴工程师",
        contactPhone: "155****4321",
        remarks: "智能化系统升级完成",
    },
    {
        buildingId: "B008",
        buildingName: "H栋",
        totalFloors: 16,
        totalHouseholds: 64,
        buildingArea: 7680.2,
        buildingStructure: "剪力墙结构",
        constructionYear: "2017",
        drawingPath: "/drawings/H栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-17 12:10:00",
        personInCharge: "郑工程师",
        contactPhone: "137****8888",
        remarks: "定期安全检查通过",
    },
    {
        buildingId: "B009",
        buildingName: "I栋",
        totalFloors: 19,
        totalHouseholds: 76,
        buildingArea: 9120.8,
        buildingStructure: "钢筋混凝土结构",
        constructionYear: "2018",
        drawingPath: "/drawings/I栋_结构图_2024.pdf",
        status: "装修中",
        lastUpdateTime: "2024-11-14 08:40:00",
        personInCharge: "刘工程师",
        contactPhone: "170****2468",
        remarks: "大堂改造进行中",
    },
    {
        buildingId: "B010",
        buildingName: "J栋",
        totalFloors: 14,
        totalHouseholds: 56,
        buildingArea: 6720.5,
        buildingStructure: "砖混结构",
        constructionYear: "2015",
        drawingPath: "/drawings/J栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-20 13:25:00",
        personInCharge: "黄工程师",
        contactPhone: "182****7654",
        remarks: "老楼改造完成，状况良好",
    },
    {
        buildingId: "B011",
        buildingName: "K栋",
        totalFloors: 30,
        totalHouseholds: 120,
        buildingArea: 14400.3,
        buildingStructure: "钢结构",
        constructionYear: "2023",
        drawingPath: "/drawings/K栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-18 16:15:00",
        personInCharge: "林工程师",
        contactPhone: "199****3210",
        remarks: "超高层建筑，配备最新安全系统",
    },
    {
        buildingId: "B012",
        buildingName: "L栋",
        totalFloors: 8,
        totalHouseholds: 32,
        buildingArea: 3840.6,
        buildingStructure: "砖混结构",
        constructionYear: "2012",
        drawingPath: "/drawings/L栋_结构图_2024.pdf",
        status: "维修中",
        lastUpdateTime: "2024-11-13 10:30:00",
        personInCharge: "马工程师",
        contactPhone: "166****5678",
        remarks: "屋顶防水层翻新施工中",
    },
    {
        buildingId: "B013",
        buildingName: "M栋",
        totalFloors: 24,
        totalHouseholds: 96,
        buildingArea: 11520.7,
        buildingStructure: "框架结构",
        constructionYear: "2020",
        drawingPath: "/drawings/M栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-19 09:45:00",
        personInCharge: "徐工程师",
        contactPhone: "144****8765",
        remarks: "商业住宅综合体，运营良好",
    },
    {
        buildingId: "B014",
        buildingName: "N栋",
        totalFloors: 17,
        totalHouseholds: 68,
        buildingArea: 8160.4,
        buildingStructure: "剪力墙结构",
        constructionYear: "2019",
        drawingPath: "/drawings/N栋_结构图_2024.pdf",
        status: "待验收",
        lastUpdateTime: "2024-11-11 14:20:00",
        personInCharge: "杨工程师",
        contactPhone: "177****1234",
        remarks: "消防系统升级完成，待验收",
    },
    {
        buildingId: "B015",
        buildingName: "O栋",
        totalFloors: 21,
        totalHouseholds: 84,
        buildingArea: 10080.9,
        buildingStructure: "钢筋混凝土结构",
        constructionYear: "2021",
        drawingPath: "/drawings/O栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-20 15:50:00",
        personInCharge: "朱工程师",
        contactPhone: "133****7890",
        remarks: "绿色建筑认证，节能环保",
    },
    {
        buildingId: "B016",
        buildingName: "P栋",
        totalFloors: 13,
        totalHouseholds: 52,
        buildingArea: 6240.2,
        buildingStructure: "砖混结构",
        constructionYear: "2016",
        drawingPath: "/drawings/P栋_结构图_2024.pdf",
        status: "装修中",
        lastUpdateTime: "2024-11-16 11:15:00",
        personInCharge: "高工程师",
        contactPhone: "158****2345",
        remarks: "外墙翻新施工中",
    },
    {
        buildingId: "B017",
        buildingName: "Q栋",
        totalFloors: 26,
        totalHouseholds: 104,
        buildingArea: 12480.5,
        buildingStructure: "钢结构",
        constructionYear: "2022",
        drawingPath: "/drawings/Q栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-18 13:40:00",
        personInCharge: "梁工程师",
        contactPhone: "156****1357",
        remarks: "模块化建筑，施工质量优秀",
    },
    {
        buildingId: "B018",
        buildingName: "R栋",
        totalFloors: 11,
        totalHouseholds: 44,
        buildingArea: 5280.8,
        buildingStructure: "框架结构",
        constructionYear: "2017",
        drawingPath: "/drawings/R栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-17 16:25:00",
        personInCharge: "郭工程师",
        contactPhone: "189****1111",
        remarks: "老年公寓，配备无障碍设施",
    },
    {
        buildingId: "B019",
        buildingName: "S栋",
        totalFloors: 23,
        totalHouseholds: 92,
        buildingArea: 11040.3,
        buildingStructure: "钢筋混凝土结构",
        constructionYear: "2020",
        drawingPath: "/drawings/S栋_结构图_2024.pdf",
        status: "维修中",
        lastUpdateTime: "2024-11-15 09:35:00",
        personInCharge: "何工程师",
        contactPhone: "178****2222",
        remarks: "管道系统维护中",
    },
    {
        buildingId: "B020",
        buildingName: "T栋",
        totalFloors: 18,
        totalHouseholds: 72,
        buildingArea: 8640.6,
        buildingStructure: "剪力墙结构",
        constructionYear: "2019",
        drawingPath: "/drawings/T栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-20 10:50:00",
        personInCharge: "罗工程师",
        contactPhone: "185****0000",
        remarks: "精装修公寓，设施齐全",
    },
    {
        buildingId: "B021",
        buildingName: "U栋",
        totalFloors: 9,
        totalHouseholds: 36,
        buildingArea: 4320.4,
        buildingStructure: "砖混结构",
        constructionYear: "2014",
        drawingPath: "/drawings/U栋_结构图_2024.pdf",
        status: "待验收",
        lastUpdateTime: "2024-11-12 15:15:00",
        personInCharge: "韩工程师",
        contactPhone: "176****5555",
        remarks: "改造工程完工，准备验收",
    },
    {
        buildingId: "B022",
        buildingName: "V栋",
        totalFloors: 27,
        totalHouseholds: 108,
        buildingArea: 12960.9,
        buildingStructure: "钢结构",
        constructionYear: "2023",
        drawingPath: "/drawings/V栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-19 12:30:00",
        personInCharge: "邓工程师",
        contactPhone: "147****9999",
        remarks: "智能楼宇，自动化系统完善",
    },
    {
        buildingId: "B023",
        buildingName: "W栋",
        totalFloors: 15,
        totalHouseholds: 60,
        buildingArea: 7200.7,
        buildingStructure: "框架结构",
        constructionYear: "2018",
        drawingPath: "/drawings/W栋_结构图_2024.pdf",
        status: "装修中",
        lastUpdateTime: "2024-11-14 14:05:00",
        personInCharge: "曹工程师",
        contactPhone: "186****3333",
        remarks: "公共区域装修进行中",
    },
    {
        buildingId: "B024",
        buildingName: "X栋",
        totalFloors: 20,
        totalHouseholds: 80,
        buildingArea: 9600.2,
        buildingStructure: "钢筋混凝土结构",
        constructionYear: "2021",
        drawingPath: "/drawings/X栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-18 08:20:00",
        personInCharge: "彭工程师",
        contactPhone: "179****4444",
        remarks: "节能改造完成，能耗降低30%",
    },
    {
        buildingId: "B025",
        buildingName: "Y栋",
        totalFloors: 12,
        totalHouseholds: 48,
        buildingArea: 5760.5,
        buildingStructure: "砖混结构",
        constructionYear: "2015",
        drawingPath: "/drawings/Y栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-20 11:45:00",
        personInCharge: "萧工程师",
        contactPhone: "174****6666",
        remarks: "传统风格建筑，维护良好",
    },
    {
        buildingId: "B026",
        buildingName: "Z栋",
        totalFloors: 29,
        totalHouseholds: 116,
        buildingArea: 13920.8,
        buildingStructure: "剪力墙结构",
        constructionYear: "2022",
        drawingPath: "/drawings/Z栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-17 13:10:00",
        personInCharge: "袁工程师",
        contactPhone: "180****7777",
        remarks: "地标性建筑，配备观光电梯",
    },
    {
        buildingId: "B027",
        buildingName: "AA栋",
        totalFloors: 10,
        totalHouseholds: 40,
        buildingArea: 4800.3,
        buildingStructure: "框架结构",
        constructionYear: "2013",
        drawingPath: "/drawings/AA栋_结构图_2024.pdf",
        status: "维修中",
        lastUpdateTime: "2024-11-16 16:40:00",
        personInCharge: "侯工程师",
        contactPhone: "183****8888",
        remarks: "地基加固施工中",
    },
    {
        buildingId: "B028",
        buildingName: "AB栋",
        totalFloors: 32,
        totalHouseholds: 128,
        buildingArea: 15360.6,
        buildingStructure: "钢结构",
        constructionYear: "2024",
        drawingPath: "/drawings/AB栋_结构图_2024.pdf",
        status: "待验收",
        lastUpdateTime: "2024-11-11 10:25:00",
        personInCharge: "邵工程师",
        contactPhone: "181****9999",
        remarks: "最新建成，等待最终验收",
    },
    {
        buildingId: "B029",
        buildingName: "AC栋",
        totalFloors: 7,
        totalHouseholds: 28,
        buildingArea: 3360.4,
        buildingStructure: "砖混结构",
        constructionYear: "2011",
        drawingPath: "/drawings/AC栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-19 14:55:00",
        personInCharge: "崔工程师",
        contactPhone: "175****1111",
        remarks: "低层住宅，环境优美",
    },
    {
        buildingId: "B030",
        buildingName: "AD栋",
        totalFloors: 16,
        totalHouseholds: 64,
        buildingArea: 7680.9,
        buildingStructure: "钢筋混凝土结构",
        constructionYear: "2017",
        drawingPath: "/drawings/AD栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-18 09:40:00",
        personInCharge: "康工程师",
        contactPhone: "177****2222",
        remarks: "艺术装饰风格，特色鲜明",
    },
    {
        buildingId: "B031",
        buildingName: "AE栋",
        totalFloors: 22,
        totalHouseholds: 88,
        buildingArea: 10560.7,
        buildingStructure: "框架结构",
        constructionYear: "2020",
        drawingPath: "/drawings/AE栋_结构图_2024.pdf",
        status: "装修中",
        lastUpdateTime: "2024-11-15 12:50:00",
        personInCharge: "章工程师",
        contactPhone: "172****3333",
        remarks: "内部空间重新规划中",
    },
    {
        buildingId: "B032",
        buildingName: "AF栋",
        totalFloors: 14,
        totalHouseholds: 56,
        buildingArea: 6720.2,
        buildingStructure: "剪力墙结构",
        constructionYear: "2018",
        drawingPath: "/drawings/AF栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-20 15:30:00",
        personInCharge: "云工程师",
        contactPhone: "169****4444",
        remarks: "抗震加固完成，安全性高",
    },
    {
        buildingId: "B033",
        buildingName: "AG栋",
        totalFloors: 25,
        totalHouseholds: 100,
        buildingArea: 12000.5,
        buildingStructure: "钢结构",
        constructionYear: "2022",
        drawingPath: "/drawings/AG栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-17 11:20:00",
        personInCharge: "苏工程师",
        contactPhone: "173****5555",
        remarks: "环保材料建造，绿色建筑",
    },
    {
        buildingId: "B034",
        buildingName: "AH栋",
        totalFloors: 8,
        totalHouseholds: 32,
        buildingArea: 3840.8,
        buildingStructure: "砖混结构",
        constructionYear: "2012",
        drawingPath: "/drawings/AH栋_结构图_2024.pdf",
        status: "维修中",
        lastUpdateTime: "2024-11-13 13:45:00",
        personInCharge: "葛工程师",
        contactPhone: "184****6666",
        remarks: "外墙保温层改造施工中",
    },
    {
        buildingId: "B035",
        buildingName: "AI栋",
        totalFloors: 19,
        totalHouseholds: 76,
        buildingArea: 9120.3,
        buildingStructure: "框架结构",
        constructionYear: "2019",
        drawingPath: "/drawings/AI栋_结构图_2024.pdf",
        status: "正常使用",
        lastUpdateTime: "2024-11-19 16:10:00",
        personInCharge: "魏工程师",
        contactPhone: "178****7777",
        remarks: "智能安防系统全面升级",
    },
];
