import type { ReviewListItem } from "@01s-11comm/type";

/**
 * 合同审核模拟数据
 * Review mock data
 */
export const mockReviewData: ReviewListItem[] = [
	{
		id: "1",
		contractName: "2024年度办公用品采购合同",
		contractNumber: "HT-2024-006",
		contractType: "采购合同",
		partyA: "某某物业公司",
		partyB: "某某供应商有限公司",
		contractAmount: "50000.00",
		submitter: "张三",
		submitTime: "2024-12-01 10:00:00",
		reviewer: "李四",
		reviewTime: "2024-12-02 14:00:00",
		reviewStatus: "已通过",
		reviewOpinion: "合同条款清晰，金额合理，同意签订",
		currentNode: "已完成",
	},
	{
		id: "2",
		contractName: "设备维修服务合同",
		contractNumber: "HT-2024-007",
		contractType: "服务合同",
		partyA: "某某物业公司",
		partyB: "某某维修公司",
		contractAmount: "30000.00",
		submitter: "王五",
		submitTime: "2024-12-10 09:00:00",
		reviewer: "",
		reviewTime: "",
		reviewStatus: "待审核",
		currentNode: "部门经理审核",
	},
	{
		id: "3",
		contractName: "广告位租赁合同",
		contractNumber: "HT-2024-008",
		contractType: "租赁合同",
		partyA: "某某物业公司",
		partyB: "某某广告公司",
		contractAmount: "100000.00",
		submitter: "赵六",
		submitTime: "2024-12-08 15:00:00",
		reviewer: "孙七",
		reviewTime: "",
		reviewStatus: "审核中",
		currentNode: "法务审核",
	},
	{
		id: "4",
		contractName: "消防设备采购合同",
		contractNumber: "HT-2024-009",
		contractType: "采购合同",
		partyA: "某某物业公司",
		partyB: "某某消防公司",
		contractAmount: "200000.00",
		submitter: "周八",
		submitTime: "2024-12-05 11:00:00",
		reviewer: "李四",
		reviewTime: "2024-12-06 16:00:00",
		reviewStatus: "已驳回",
		reviewOpinion: "合同金额需重新核算，请修改后重新提交",
		currentNode: "已退回",
	},
	{
		id: "5",
		contractName: "清洁服务外包合同",
		contractNumber: "HT-2024-010",
		contractType: "服务合同",
		partyA: "某某物业公司",
		partyB: "某某清洁公司",
		contractAmount: "150000.00",
		submitter: "吴九",
		submitTime: "2024-12-12 10:00:00",
		reviewer: "",
		reviewTime: "",
		reviewStatus: "已撤回",
		reviewOpinion: "申请人主动撤回",
		currentNode: "已撤回",
	},
];
