import type { ReportComponent } from "@01s-11comm/type";

/**
 * 报表组件模拟数据
 */
export const mockReportComponentData: ReportComponent[] = [
	{
		id: "RPC001",
		componentName: "数据表格",
		componentCode: "DATA_TABLE",
		componentType: "表格",
		reportId: "RPT001",
		reportName: "月度物业费收费明细",
		componentConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名","width":120},{"prop":"roomNumber","label":"房号","width":100},{"prop":"feeAmount","label":"收费金额","width":120,"formatter":"currency"},{"prop":"payTime","label":"缴费时间","width":160}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true,"highlightCurrentRow":true}',
		eventConfig: '{"onSortChange":"handleSortChange","onRowClick":"handleRowClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC002",
		componentName: "柱状图",
		componentCode: "BAR_CHART",
		componentType: "图表",
		reportId: "RPT002",
		reportName: "年度收费统计汇总",
		componentConfig: '{"xAxis":{"type":"category","data":["阳光花园","绿城国际","华润凤凰城"]},"yAxis":{"type":"value"},"series":[{"name":"收费金额","type":"bar","data":[1200000,1500000,1800000]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"400px","width":"100%"}',
		eventConfig: '{"onClick":"handleChartClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC003",
		componentName: "统计卡片",
		componentCode: "STAT_CARD",
		componentType: "文本",
		reportId: "RPT002",
		reportName: "年度收费统计汇总",
		componentConfig: '{"items":[{"label":"收费总额","value":"4500000","unit":"元","color":"#409EFF"},{"label":"收费户数","value":"2880","unit":"户","color":"#67C23A"}]}',
		dataBinding: "data.summary",
		styleConfig: '{"display":"flex","gap":"20px"}',
		eventConfig: '{}',
		sortOrder: 2,
		isEnabled: true,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC004",
		componentName: "业主信息表格",
		componentCode: "OWNER_TABLE",
		componentType: "表格",
		reportId: "RPT003",
		reportName: "业主信息一览表",
		componentConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名","width":100},{"prop":"phone","label":"联系电话","width":130},{"prop":"roomNumber","label":"房号","width":100},{"prop":"idCard","label":"身份证号","width":180}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true}',
		eventConfig: '{"onSelectionChange":"handleSelectionChange"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "component_admin",
	},
	{
		id: "RPC005",
		componentName: "饼图",
		componentCode: "PIE_CHART",
		componentType: "图表",
		reportId: "RPT004",
		reportName: "车辆信息统计",
		componentConfig: '{"series":[{"name":"车辆类型","type":"pie","radius":"60%","data":[{"value":500,"name":"小型车"},{"value":200,"name":"大型车"},{"value":100,"name":"新能源车"}]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handlePieClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "component_admin",
	},
	{
		id: "RPC006",
		componentName: "维修工单状态表格",
		componentCode: "MAINTENANCE_TABLE",
		componentType: "表格",
		reportId: "RPT005",
		reportName: "维修工单处理统计",
		componentConfig: '{"columns":[{"prop":"status","label":"状态","width":100},{"prop":"count","label":"数量","width":100},{"prop":"percentage","label":"占比","width":100,"formatter":"percentage"}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":false}',
		eventConfig: '{}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-12 08:00:00",
		updateTime: "2024-01-22 16:45:00",
		operator: "component_admin",
	},
	{
		id: "RPC007",
		componentName: "巡检计划表格",
		componentCode: "PATROL_TABLE",
		componentType: "表格",
		reportId: "RPT006",
		reportName: "巡检计划执行情况",
		componentConfig: '{"columns":[{"prop":"planName","label":"计划名称","width":150},{"prop":"planDate","label":"计划日期","width":120},{"prop":"executor","label":"执行人","width":100},{"prop":"status","label":"状态","width":100}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true}',
		eventConfig: '{"onRowClick":"handleRowClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-13 08:00:00",
		updateTime: "2024-01-23 11:20:00",
		operator: "component_admin",
	},
	{
		id: "RPC008",
		componentName: "门禁记录表格",
		componentCode: "ACCESS_TABLE",
		componentType: "表格",
		reportId: "RPT007",
		reportName: "门禁刷卡记录",
		componentConfig: '{"columns":[{"prop":"cardNumber","label":"卡号","width":150},{"prop":"personName","label":"姓名","width":100},{"prop":"accessTime","label":"刷卡时间","width":160},{"prop":"gateName","label":"门禁点","width":150}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true,"height":"600px"}',
		eventConfig: '{"onRowClick":"handleRowClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-14 08:00:00",
		updateTime: "2024-01-24 15:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC009",
		componentName: "设备维护表格",
		componentCode: "EQUIPMENT_TABLE",
		componentType: "表格",
		reportId: "RPT008",
		reportName: "设备维护记录",
		componentConfig: '{"columns":[{"prop":"equipmentName","label":"设备名称","width":150},{"prop":"maintenanceType","label":"维护类型","width":120},{"prop":"maintenanceDate","label":"维护日期","width":120},{"prop":"technician","label":"技术人员","width":100}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true}',
		eventConfig: '{}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-15 08:00:00",
		updateTime: "2024-01-25 09:45:00",
		operator: "component_admin",
	},
	{
		id: "RPC010",
		componentName: "能耗统计图表",
		componentCode: "ENERGY_CHART",
		componentType: "图表",
		reportId: "RPT009",
		reportName: "月度能耗统计",
		componentConfig: '{"xAxis":{"type":"category","data":["1月","2月","3月","4月","5月","6月"]},"yAxis":{"type":"value"},"series":[{"name":"用电量","type":"line","data":[12000,13000,11000,14000,15000,16000]},{"name":"用水量","type":"line","data":[8000,7500,8200,7800,8500,9000]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"400px","width":"100%"}',
		eventConfig: '{"onLegendClick":"handleLegendClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-16 08:00:00",
		updateTime: "2024-01-26 13:20:00",
		operator: "component_admin",
	},
];
