import type { ReportComponent } from "@01s-11comm/type";

/**
 * 报表组件模拟数据
 */
export const mockReportComponentData: ReportComponent[] = [
	{
		id: "RPC001",
		componentName: "数据表格",
		componentCode: "DATA_TABLE",
		componentType: "表格",
		reportId: "RPT001",
		reportName: "月度物业费收费明细",
		componentConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名","width":120},{"prop":"roomNumber","label":"房号","width":100},{"prop":"feeAmount","label":"收费金额","width":120,"formatter":"currency"},{"prop":"payTime","label":"缴费时间","width":160}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true,"highlightCurrentRow":true}',
		eventConfig: '{"onSortChange":"handleSortChange","onRowClick":"handleRowClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC002",
		componentName: "柱状图",
		componentCode: "BAR_CHART",
		componentType: "图表",
		reportId: "RPT002",
		reportName: "年度收费统计汇总",
		componentConfig: '{"xAxis":{"type":"category","data":["阳光花园","绿城国际","华润凤凰城"]},"yAxis":{"type":"value"},"series":[{"name":"收费金额","type":"bar","data":[1200000,1500000,1800000]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"400px","width":"100%"}',
		eventConfig: '{"onClick":"handleChartClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC003",
		componentName: "统计卡片",
		componentCode: "STAT_CARD",
		componentType: "文本",
		reportId: "RPT002",
		reportName: "年度收费统计汇总",
		componentConfig: '{"items":[{"label":"收费总额","value":"4500000","unit":"元","color":"#409EFF"},{"label":"收费户数","value":"2880","unit":"户","color":"#67C23A"}]}',
		dataBinding: "data.summary",
		styleConfig: '{"display":"flex","gap":"20px"}',
		eventConfig: '{}',
		sortOrder: 2,
		isEnabled: true,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC004",
		componentName: "业主信息表格",
		componentCode: "OWNER_TABLE",
		componentType: "表格",
		reportId: "RPT003",
		reportName: "业主信息一览表",
		componentConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名","width":100},{"prop":"phone","label":"联系电话","width":130},{"prop":"roomNumber","label":"房号","width":100},{"prop":"idCard","label":"身份证号","width":180}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true}',
		eventConfig: '{"onSelectionChange":"handleSelectionChange"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "component_admin",
	},
	{
		id: "RPC005",
		componentName: "饼图",
		componentCode: "PIE_CHART",
		componentType: "图表",
		reportId: "RPT004",
		reportName: "车辆信息统计",
		componentConfig: '{"series":[{"name":"车辆类型","type":"pie","radius":"60%","data":[{"value":500,"name":"小型车"},{"value":200,"name":"大型车"},{"value":100,"name":"新能源车"}]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handlePieClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "component_admin",
	},
	{
		id: "RPC006",
		componentName: "维修工单状态表格",
		componentCode: "MAINTENANCE_TABLE",
		componentType: "表格",
		reportId: "RPT005",
		reportName: "维修工单处理统计",
		componentConfig: '{"columns":[{"prop":"status","label":"状态","width":100},{"prop":"count","label":"数量","width":100},{"prop":"percentage","label":"占比","width":100,"formatter":"percentage"}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":false}',
		eventConfig: '{}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-12 08:00:00",
		updateTime: "2024-01-22 16:45:00",
		operator: "component_admin",
	},
	{
		id: "RPC007",
		componentName: "巡检计划表格",
		componentCode: "PATROL_TABLE",
		componentType: "表格",
		reportId: "RPT006",
		reportName: "巡检计划执行情况",
		componentConfig: '{"columns":[{"prop":"planName","label":"计划名称","width":150},{"prop":"planDate","label":"计划日期","width":120},{"prop":"executor","label":"执行人","width":100},{"prop":"status","label":"状态","width":100}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true}',
		eventConfig: '{"onRowClick":"handleRowClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-13 08:00:00",
		updateTime: "2024-01-23 11:20:00",
		operator: "component_admin",
	},
	{
		id: "RPC008",
		componentName: "门禁记录表格",
		componentCode: "ACCESS_TABLE",
		componentType: "表格",
		reportId: "RPT007",
		reportName: "门禁刷卡记录",
		componentConfig: '{"columns":[{"prop":"cardNumber","label":"卡号","width":150},{"prop":"personName","label":"姓名","width":100},{"prop":"accessTime","label":"刷卡时间","width":160},{"prop":"gateName","label":"门禁点","width":150}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true,"height":"600px"}',
		eventConfig: '{"onRowClick":"handleRowClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-14 08:00:00",
		updateTime: "2024-01-24 15:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC009",
		componentName: "设备维护表格",
		componentCode: "EQUIPMENT_TABLE",
		componentType: "表格",
		reportId: "RPT008",
		reportName: "设备维护记录",
		componentConfig: '{"columns":[{"prop":"equipmentName","label":"设备名称","width":150},{"prop":"maintenanceType","label":"维护类型","width":120},{"prop":"maintenanceDate","label":"维护日期","width":120},{"prop":"technician","label":"技术人员","width":100}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true}',
		eventConfig: '{}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-15 08:00:00",
		updateTime: "2024-01-25 09:45:00",
		operator: "component_admin",
	},
	{
		id: "RPC010",
		componentName: "能耗统计图表",
		componentCode: "ENERGY_CHART",
		componentType: "图表",
		reportId: "RPT009",
		reportName: "月度能耗统计",
		componentConfig: '{"xAxis":{"type":"category","data":["1月","2月","3月","4月","5月","6月"]},"yAxis":{"type":"value"},"series":[{"name":"用电量","type":"line","data":[12000,13000,11000,14000,15000,16000]},{"name":"用水量","type":"line","data":[8000,7500,8200,7800,8500,9000]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"400px","width":"100%"}',
		eventConfig: '{"onLegendClick":"handleLegendClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-16 08:00:00",
		updateTime: "2024-01-26 13:20:00",
		operator: "component_admin",
	},
	{
		id: "RPC011",
		componentName: "访客统计图表",
		componentCode: "VISITOR_CHART",
		componentType: "图表",
		reportId: "RPT011",
		reportName: "访客进出统计",
		componentConfig: '{"xAxis":{"type":"category","data":["周一","周二","周三","周四","周五","周六","周日"]},"yAxis":{"type":"value"},"series":[{"name":"访客数量","type":"bar","data":[120,150,180,200,220,300,280]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handleChartClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-20 08:00:00",
		updateTime: "2024-01-30 10:15:00",
		operator: "component_admin",
	},
	{
		id: "RPC012",
		componentName: "车位使用率",
		componentCode: "PARKING_RATE",
		componentType: "图表",
		reportId: "RPT012",
		reportName: "车位使用率统计",
		componentConfig: '{"series":[{"name":"使用率","type":"pie","radius":"60%","data":[{"value":85,"name":"已使用"},{"value":15,"name":"空闲"}]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handlePieClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-21 08:00:00",
		updateTime: "2024-01-31 14:20:00",
		operator: "component_admin",
	},
	{
		id: "RPC013",
		componentName: "门禁记录表格",
		componentCode: "ACCESS_TABLE_V2",
		componentType: "表格",
		reportId: "RPT013",
		reportName: "门禁刷卡记录明细",
		componentConfig: '{"columns":[{"prop":"cardNumber","label":"卡号","width":150},{"prop":"personName","label":"姓名","width":100},{"prop":"accessTime","label":"刷卡时间","width":160},{"prop":"gateName","label":"门禁点","width":150}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true,"height":"600px"}',
		eventConfig: '{"onRowClick":"handleRowClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-22 08:00:00",
		updateTime: "2024-02-01 11:10:00",
		operator: "component_admin",
	},
	{
		id: "RPC014",
		componentName: "能耗对比图表",
		componentCode: "ENERGY_COMPARE",
		componentType: "图表",
		reportId: "RPT014",
		reportName: "月度能耗分析",
		componentConfig: '{"xAxis":{"type":"category","data":["1月","2月","3月","4月","5月","6月"]},"yAxis":{"type":"value"},"series":[{"name":"用电量","type":"line","data":[12000,13000,11000,14000,15000,16000]},{"name":"用水量","type":"line","data":[8000,7500,8200,7800,8500,9000]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"400px","width":"100%"}',
		eventConfig: '{"onLegendClick":"handleLegendClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-23 08:00:00",
		updateTime: "2024-02-02 16:40:00",
		operator: "component_admin",
	},
	{
		id: "RPC015",
		componentName: "消防检查记录表",
		componentCode: "FIRE_TABLE",
		componentType: "表格",
		reportId: "RPT015",
		reportName: "消防检查记录",
		componentConfig: '{"columns":[{"prop":"inspectionDate","label":"检查日期","width":120},{"prop":"inspector","label":"检查人","width":100},{"prop":"location","label":"检查位置","width":150},{"prop":"result","label":"检查结果","width":100}]}',
		dataBinding: "data.list",
		styleConfig: '{"border":true,"stripe":true}',
		eventConfig: '{}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-24 08:00:00",
		updateTime: "2024-02-03 09:25:00",
		operator: "component_admin",
	},
	{
		id: "RPC016",
		componentName: "绿化任务统计",
		componentCode: "GREENING_STAT",
		componentType: "图表",
		reportId: "RPT016",
		reportName: "绿化养护统计",
		componentConfig: '{"series":[{"name":"任务数量","type":"pie","radius":"60%","data":[{"value":45,"name":"修剪"},{"value":30,"name":"浇水"},{"value":25,"name":"施肥"}]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handlePieClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-25 08:00:00",
		updateTime: "2024-02-04 14:50:00",
		operator: "component_admin",
	},
	{
		id: "RPC017",
		componentName: "保洁完成率",
		componentCode: "CLEANING_RATE",
		componentType: "图表",
		reportId: "RPT017",
		reportName: "保洁任务完成率",
		componentConfig: '{"xAxis":{"type":"category","data":["A区","B区","C区","D区"]},"yAxis":{"type":"value"},"series":[{"name":"完成率","type":"bar","data":[95,88,92,98]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handleChartClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-26 08:00:00",
		updateTime: "2024-02-05 11:30:00",
		operator: "component_admin",
	},
	{
		id: "RPC018",
		componentName: "报修时效统计",
		componentCode: "REPAIR_TIME_STAT",
		componentType: "图表",
		reportId: "RPT018",
		reportName: "报修处理时效",
		componentConfig: '{"xAxis":{"type":"category","data":["水电","门窗","电梯","网络","其他"]},"yAxis":{"type":"value"},"series":[{"name":"平均时长(小时)","type":"bar","data":[2.5,3.2,4.5,1.8,2.0]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handleChartClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-27 08:00:00",
		updateTime: "2024-02-06 15:20:00",
		operator: "component_admin",
	},
	{
		id: "RPC019",
		componentName: "欠费金额统计",
		componentCode: "OVERDUE_AMOUNT",
		componentType: "图表",
		reportId: "RPT019",
		reportName: "欠费催缴统计",
		componentConfig: '{"series":[{"name":"欠费金额","type":"pie","radius":"60%","data":[{"value":150000,"name":"物业费"},{"value":80000,"name":"水电费"},{"value":50000,"name":"停车费"}]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"350px","width":"100%"}',
		eventConfig: '{"onClick":"handlePieClick"}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-28 08:00:00",
		updateTime: "2024-02-07 10:40:00",
		operator: "component_admin",
	},
	{
		id: "RPC020",
		componentName: "满意度评分",
		componentCode: "SATISFACTION_SCORE",
		componentType: "图表",
		reportId: "RPT020",
		reportName: "业主满意度调查",
		componentConfig: '{"xAxis":{"type":"category","data":["安保","保洁","绿化","维修","客服"]},"yAxis":{"type":"value","min":0,"max":5},"series":[{"name":"满意度评分","type":"radar","data":[{"value":[4.5,4.2,4.3,4.6,4.4],"name":"评分"}]}]}',
		dataBinding: "data.chartData",
		styleConfig: '{"height":"400px","width":"100%"}',
		eventConfig: '{}',
		sortOrder: 1,
		isEnabled: true,
		createTime: "2024-01-29 08:00:00",
		updateTime: "2024-02-08 16:10:00",
		operator: "component_admin",
	},
];
