import type { OptionsType } from "plus-pro-components";

/** 报表组件列表数据类型 */
export interface 报表组件_列表数据 {
	组件ID: string;
	组件名称: string;
	组件类型: string;
	查询方式: string;
	sql: string;
	java: string;
	描述: string;
}

/** 报表组件列表查询参数类型 */
export interface 报表组件_列表查询_VO {
	组件ID?: string;
	组件名称?: string;
	组件类型?: string;
	查询方式?: string;
}

/** 组件类型选项 */
export const 组件类型Options: OptionsType = [
	{ label: "表格", value: "表格" },
	{ label: "饼状图", value: "饼状图" },
	{ label: "柱状图", value: "柱状图" },
	{ label: "折线图", value: "折线图" },
	{ label: "数据卡片", value: "数据卡片" },
];

/** 查询方式选项 */
export const 查询方式Options: OptionsType = [
	{ label: "SQL", value: "sql" },
	{ label: "JAVA", value: "java" },
];

/** 表格假数据 */
export const tableData: 报表组件_列表数据[] = [
	{
		组件ID: "RC001",
		组件名称: "用户统计表格",
		组件类型: "表格",
		查询方式: "sql",
		sql: "SELECT * FROM users WHERE status = 'active'",
		java: "",
		描述: "展示活跃用户的统计信息表格组件",
	},
	{
		组件ID: "RC002",
		组件名称: "销售额饼状图",
		组件类型: "饼状图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.SalesAnalysisService",
		描述: "按部门展示销售额分布的饼状图组件",
	},
	{
		组件ID: "RC003",
		组件名称: "月度收入柱状图",
		组件类型: "柱状图",
		查询方式: "sql",
		sql: "SELECT month, SUM(revenue) FROM monthly_revenue GROUP BY month",
		java: "",
		描述: "展示各月度收入对比的柱状图组件",
	},
	{
		组件ID: "RC004",
		组件名称: "访问量趋势图",
		组件类型: "折线图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.TrafficAnalysisService",
		描述: "展示网站访问量变化趋势的折线图组件",
	},
	{
		组件ID: "RC005",
		组件名称: "订单统计卡片",
		组件类型: "数据卡片",
		查询方式: "sql",
		sql: "SELECT COUNT(*) as total_orders FROM orders WHERE DATE(created_at) = CURRENT_DATE",
		java: "",
		描述: "展示今日订单总数的数据卡片组件",
	},
	{
		组件ID: "RC006",
		组件名称: "产品分类表格",
		组件类型: "表格",
		查询方式: "sql",
		sql: "SELECT category, COUNT(*) as count FROM products GROUP BY category",
		java: "",
		描述: "按分类展示产品数量的表格组件",
	},
	{
		组件ID: "RC007",
		组件名称: "地区分布饼图",
		组件类型: "饼状图",
		查询方式: "sql",
		sql: "SELECT region, COUNT(user_id) FROM user_regions GROUP BY region",
		java: "",
		描述: "展示用户地区分布情况的饼状图组件",
	},
	{
		组件ID: "RC008",
		组件名称: "库存预警表格",
		组件类型: "表格",
		查询方式: "java",
		sql: "",
		java: "com.report.service.InventoryWarningService",
		描述: "展示低库存商品预警信息的表格组件",
	},
	{
		组件ID: "RC009",
		组件名称: "客户满意度图表",
		组件类型: "柱状图",
		查询方式: "sql",
		sql: "SELECT satisfaction_level, COUNT(*) FROM customer_feedback GROUP BY satisfaction_level",
		java: "",
		描述: "展示客户满意度调查结果的柱状图组件",
	},
	{
		组件ID: "RC010",
		组件名称: "实时在线用户卡片",
		组件类型: "数据卡片",
		查询方式: "java",
		sql: "",
		java: "com.report.service.OnlineUserService",
		描述: "实时显示当前在线用户数量的数据卡片组件",
	},
	{
		组件ID: "RC011",
		组件名称: "年度报告表格",
		组件类型: "表格",
		查询方式: "sql",
		sql: "SELECT * FROM annual_reports WHERE year = YEAR(CURRENT_DATE)",
		java: "",
		描述: "展示本年度各项业务指标的年度报告表格",
	},
	{
		组件ID: "RC012",
		组件名称: "设备状态饼图",
		组件类型: "饼状图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.DeviceStatusService",
		描述: "展示设备运行状态分布的饼状图组件",
	},
	{
		组件ID: "RC013",
		组件名称: "营收趋势折线图",
		组件类型: "折线图",
		查询方式: "sql",
		sql: "SELECT DATE(created_at) as date, SUM(amount) FROM transactions GROUP BY DATE(created_at) ORDER BY date",
		java: "",
		描述: "展示营业收入变化趋势的折线图组件",
	},
	{
		组件ID: "RC014",
		组件名称: "新增用户卡片",
		组件类型: "数据卡片",
		查询方式: "sql",
		sql: "SELECT COUNT(*) FROM users WHERE DATE(created_at) = CURRENT_DATE",
		java: "",
		描述: "展示今日新增用户数量的数据卡片组件",
	},
	{
		组件ID: "RC015",
		组件名称: "项目进度表格",
		组件类型: "表格",
		查询方式: "java",
		sql: "",
		java: "com.report.service.ProjectProgressService",
		描述: "展示项目完成进度情况的表格组件",
	},
	{
		组件ID: "RC016",
		组件名称: "支付方式分布图",
		组件类型: "饼状图",
		查询方式: "sql",
		sql: "SELECT payment_method, COUNT(*) FROM payments GROUP BY payment_method",
		java: "",
		描述: "展示不同支付方式使用分布的饼状图组件",
	},
	{
		组件ID: "RC017",
		组件名称: "错误日志统计图",
		组件类型: "柱状图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.ErrorLogService",
		描述: "统计系统错误日志数量的柱状图组件",
	},
	{
		组件ID: "RC018",
		组件名称: "API调用量趋势图",
		组件类型: "折线图",
		查询方式: "sql",
		sql: "SELECT DATE(call_time) as date, COUNT(*) FROM api_calls GROUP BY DATE(call_time)",
		java: "",
		描述: "展示API调用量变化趋势的折线图组件",
	},
	{
		组件ID: "RC019",
		组件名称: "存储空间使用卡片",
		组件类型: "数据卡片",
		查询方式: "java",
		sql: "",
		java: "com.report.service.StorageUsageService",
		描述: "显示当前存储空间使用情况的数据卡片组件",
	},
	{
		组件ID: "RC020",
		组件名称: "员工绩效表格",
		组件类型: "表格",
		查询方式: "sql",
		sql: "SELECT employee_id, name, performance_score FROM employee_performance ORDER BY performance_score DESC",
		java: "",
		描述: "展示员工绩效评估结果的表格组件",
	},
	{
		组件ID: "RC021",
		组件名称: "部门预算分配图",
		组件类型: "饼状图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.BudgetAllocationService",
		描述: "展示各部门预算分配情况的饼状图组件",
	},
	{
		组件ID: "RC022",
		组件名称: "系统性能监控图",
		组件类型: "折线图",
		查询方式: "sql",
		sql: "SELECT timestamp, cpu_usage, memory_usage FROM system_metrics ORDER BY timestamp",
		java: "",
		描述: "监控系统CPU和内存使用率的折线图组件",
	},
	{
		组件ID: "RC023",
		组件名称: "待办任务数卡片",
		组件类型: "数据卡片",
		查询方式: "sql",
		sql: "SELECT COUNT(*) FROM tasks WHERE status = 'pending'",
		java: "",
		描述: "显示当前待办任务数量的数据卡片组件",
	},
	{
		组件ID: "RC024",
		组件名称: "客户分级统计表",
		组件类型: "表格",
		查询方式: "java",
		sql: "",
		java: "com.report.service.CustomerSegmentService",
		描述: "按等级分类统计客户数量的表格组件",
	},
	{
		组件ID: "RC025",
		组件名称: "流量来源饼图",
		组件类型: "饼状图",
		查询方式: "sql",
		sql: "SELECT traffic_source, COUNT(*) FROM website_visits GROUP BY traffic_source",
		java: "",
		描述: "展示网站流量来源分布的饼状图组件",
	},
	{
		组件ID: "RC026",
		组件名称: "季度对比柱状图",
		组件类型: "柱状图",
		查询方式: "sql",
		sql: "SELECT QUARTER(date) as quarter, SUM(revenue) FROM quarterly_revenue GROUP BY QUARTER(date)",
		java: "",
		描述: "对比各季度业绩表现的柱状图组件",
	},
	{
		组件ID: "RC027",
		组件名称: "转化率趋势图",
		组件类型: "折线图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.ConversionRateService",
		描述: "展示转化率变化趋势的折线图组件",
	},
	{
		组件ID: "RC028",
		组件名称: "活跃用户数卡片",
		组件类型: "数据卡片",
		查询方式: "sql",
		sql: "SELECT COUNT(DISTINCT user_id) FROM user_activities WHERE DATE(activity_time) = CURRENT_DATE",
		java: "",
		描述: "显示今日活跃用户数量的数据卡片组件",
	},
	{
		组件ID: "RC029",
		组件名称: "商品销量排行表",
		组件类型: "表格",
		查询方式: "sql",
		sql: "SELECT product_name, SUM(quantity) as total_sales FROM order_items GROUP BY product_name ORDER BY total_sales DESC LIMIT 10",
		java: "",
		描述: "展示商品销量排行榜的表格组件",
	},
	{
		组件ID: "RC030",
		组件名称: "用户年龄分布图",
		组件类型: "柱状图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.UserDemographicsService",
		描述: "展示用户年龄段分布情况的柱状图组件",
	},
	{
		组件ID: "RC031",
		组件名称: "退货率趋势图",
		组件类型: "折线图",
		查询方式: "sql",
		sql: "SELECT DATE(return_date) as date, COUNT(*) as return_count FROM returns GROUP BY DATE(return_date) ORDER BY date",
		java: "",
		描述: "展示商品退货率变化趋势的折线图组件",
	},
	{
		组件ID: "RC032",
		组件名称: "库存总值卡片",
		组件类型: "数据卡片",
		查询方式: "sql",
		sql: "SELECT SUM(quantity * unit_price) FROM inventory",
		java: "",
		描述: "显示当前库存总价值的数据卡片组件",
	},
	{
		组件ID: "RC033",
		组件名称: "供应商评级表格",
		组件类型: "表格",
		查询方式: "java",
		sql: "",
		java: "com.report.service.SupplierRatingService",
		描述: "展示供应商评级信息的表格组件",
	},
	{
		组件ID: "RC034",
		组件名称: "费用支出分类图",
		组件类型: "饼状图",
		查询方式: "sql",
		sql: "SELECT expense_category, SUM(amount) FROM expenses GROUP BY expense_category",
		java: "",
		描述: "展示各类费用支出占比的饼状图组件",
	},
	{
		组件ID: "RC035",
		组件名称: "响应时间监控图",
		组件类型: "折线图",
		查询方式: "java",
		sql: "",
		java: "com.report.service.ResponseTimeService",
		描述: "监控系统响应时间变化的折线图组件",
	},
];
