import type { CommunityNoticeListItem } from "@01s-11comm/type";

/** Notice 模拟数据 */
export const mockNoticeData: CommunityNoticeListItem[] = [
	{
		id: "N001",
		headerImage: "/images/notice/spring-festival.jpg",
		noticeTitle: "关于春节期间安全管理的通知",
		noticeType: "notification",
		noticeTime: "2024-01-15 09:00:00",
		publisher: "物业服务中心",
	},
	{
		id: "N002",
		headerImage: "/images/notice/elevator-maintenance.jpg",
		noticeTitle: "关于电梯维护保养的通知",
		noticeType: "maintenance",
		noticeTime: "2024-01-16 10:00:00",
		publisher: "设备管理部",
	},
	{
		id: "N003",
		headerImage: "/images/notice/garbage-sorting.jpg",
		noticeTitle: "关于垃圾分类的通知",
		noticeType: "reminder",
		noticeTime: "2024-01-17 11:00:00",
		publisher: "环保宣传组",
	},
	{
		id: "N004",
		headerImage: "/images/notice/spring-gala.jpg",
		noticeTitle: "春节联欢晚会邀请函",
		noticeType: "activity",
		noticeTime: "2024-01-18 14:00:00",
		publisher: "社区活动中心",
	},
	{
		id: "N005",
		headerImage: "/images/notice/fire-safety.jpg",
		noticeTitle: "消防安全检查通知",
		noticeType: "safety",
		noticeTime: "2024-01-19 09:30:00",
		publisher: "安全管理部",
	},
	{
		id: "N006",
		headerImage: "/images/notice/parking-management.jpg",
		noticeTitle: "停车场管理系统升级通知",
		noticeType: "notification",
		noticeTime: "2024-01-20 15:00:00",
		publisher: "车辆管理部",
	},
	{
		id: "N007",
		headerImage: "/images/notice/water-supply.jpg",
		noticeTitle: "停水通知",
		noticeType: "notification",
		noticeTime: "2024-01-21 08:00:00",
		publisher: "设施维护部",
	},
	{
		id: "N008",
		headerImage: "/images/notice/community-activity.jpg",
		noticeTitle: "社区健康义诊活动",
		noticeType: "activity",
		noticeTime: "2024-01-22 10:30:00",
		publisher: "社区卫生站",
	},
	{
		id: "N009",
		headerImage: "/images/notice/electric-safety.jpg",
		noticeTitle: "夏季用电安全温馨提示",
		noticeType: "safety",
		noticeTime: "2024-01-23 11:45:00",
		publisher: "安全管理部",
	},
	{
		id: "N010",
		headerImage: "/images/notice/anniversary.jpg",
		noticeTitle: "小区成立十周年庆典公告",
		noticeType: "announcement",
		noticeTime: "2024-01-24 09:00:00",
		publisher: "业主委员会",
	},
	{
		id: "N011",
		headerImage: "/images/notice/repair-service.jpg",
		noticeTitle: "便民维修服务升级",
		noticeType: "notification",
		noticeTime: "2024-01-25 14:00:00",
		publisher: "维修服务中心",
	},
	{
		id: "N012",
		headerImage: "/images/notice/gas-safety.jpg",
		noticeTitle: "燃气安全使用须知",
		noticeType: "safety",
		noticeTime: "2024-01-26 10:00:00",
		publisher: "安全管理部",
	},
	{
		id: "N013",
		headerImage: "/images/notice/sports-meeting.jpg",
		noticeTitle: "社区运动会报名通知",
		noticeType: "activity",
		noticeTime: "2024-01-27 08:30:00",
		publisher: "社区活动中心",
	},
	{
		id: "N014",
		headerImage: "/images/notice/noise-control.jpg",
		noticeTitle: "关于噪音管理的规定",
		noticeType: "reminder",
		noticeTime: "2024-01-28 15:30:00",
		publisher: "物业服务中心",
	},
	{
		id: "N015",
		headerImage: "/images/notice/power-outage.jpg",
		noticeTitle: "计划停电通知",
		noticeType: "notification",
		noticeTime: "2024-01-29 09:15:00",
		publisher: "电力维修部",
	},
	{
		id: "N016",
		headerImage: "/images/notice/elevator-notice.jpg",
		noticeTitle: "电梯故障维修通知",
		noticeType: "maintenance",
		noticeTime: "2024-01-30 11:00:00",
		publisher: "设备管理部",
	},
	{
		id: "N017",
		headerImage: "/images/notice/spring-cleaning.jpg",
		noticeTitle: "春季大扫除活动通知",
		noticeType: "activity",
		noticeTime: "2024-01-31 10:00:00",
		publisher: "环保宣传组",
	},
	{
		id: "N018",
		headerImage: "/images/notice/fire-drill.jpg",
		noticeTitle: "消防演练公告",
		noticeType: "safety",
		noticeTime: "2024-02-01 14:30:00",
		publisher: "安全管理部",
	},
	{
		id: "N019",
		headerImage: "/images/notice/announcement-board.jpg",
		noticeTitle: "业主大会通知",
		noticeType: "announcement",
		noticeTime: "2024-02-02 09:00:00",
		publisher: "业主委员会",
	},
	{
		id: "N020",
		headerImage: "/images/notice/pest-control.jpg",
		noticeTitle: "春季病虫害防治通知",
		noticeType: "reminder",
		noticeTime: "2024-02-03 08:00:00",
		publisher: "绿化养护部",
	},
	{
		id: "N021",
		headerImage: "/images/notice/building-renovation.jpg",
		noticeTitle: "外墙翻新工程通知",
		noticeType: "maintenance",
		noticeTime: "2024-02-04 15:00:00",
		publisher: "工程维修部",
	},
	{
		id: "N022",
		headerImage: "/images/notice/child-safety.jpg",
		noticeTitle: "儿童安全温馨提示",
		noticeType: "safety",
		noticeTime: "2024-02-05 10:30:00",
		publisher: "安全管理部",
	},
	{
		id: "N023",
		headerImage: "/images/notice/cultural-festival.jpg",
		noticeTitle: "社区文化节活动预告",
		noticeType: "activity",
		noticeTime: "2024-02-06 11:45:00",
		publisher: "社区活动中心",
	},
	{
		id: "N024",
		headerImage: "/images/notice/water-quality.jpg",
		noticeTitle: "水质检测报告公示",
		noticeType: "announcement",
		noticeTime: "2024-02-07 09:00:00",
		publisher: "设施维护部",
	},
];
