# 写星号配置 是为了让其他工具可以读取该配置，实现匹配
# 匹配深度仅允许一层 写一个星号
# 如果写两个星号 会导致匹配范围过大 .vercel 内的垃圾文件也被匹配 误认为该文件夹也是工作区
packages:
  # 当前的主项目
  - "apps/*"
  # 用于参考的例子 交给AI阅读并动态拼接
  # 放弃将 examples 作为工作区
  # 避免在云环境安装依赖时 速度过慢
  - "!examples/*"
  # 忽略掉不需要的文件夹
  - "!.vercel/**"

overrides:
  "css-select@^5.2.1": "5.2.0"

allowedDeprecatedVersions:
  "are-we-there-yet": "*"
  "sourcemap-codec": "*"
  "lodash.isequal": "*"
  "domexception": "*"
  "w3c-hr-time": "*"
  "inflight": "*"
  "npmlog": "*"
  "rimraf": "*"
  "stable": "*"
  "gauge": "*"
  "abab": "*"
  "glob": "*"

onlyBuiltDependencies:
  "@parcel/watcher": true
  "core-js": true
  "es5-ext": true
  "esbuild": true
  "typeit": true
  "vue-demi": true
