packages:
  - apps/*
  - "!examples/*"
  - "!.vercel/**"

shamefullyHoist: true

allowBuilds:
  "@parcel/watcher": true
  "@uni-helper/unocss-preset-uni": true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  simple-git-hooks: true
  typeit: true
  vue-demi: true

allowedDeprecatedVersions:
  abab: "*"
  are-we-there-yet: "*"
  domexception: "*"
  gauge: "*"
  glob: "*"
  inflight: "*"
  lodash.isequal: "*"
  npmlog: "*"
  rimraf: "*"
  sourcemap-codec: "*"
  stable: "*"
  w3c-hr-time: "*"

onlyBuiltDependencies:
  - "@uni-helper/unocss-preset-uni"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - less
  - simple-git-hooks
  - typeit
  - vue-demi
  - vue3-danmaku

overrides:
  "@vitejs/plugin-vue-jsx": 5.1.5
  bin-wrapper: "npm:bin-wrapper-china"
  css-select@^5.2.1: 5.2.0
  drizzle-orm: 0.42.0

patchedDependencies:
  vite-plugin-mock-dev-server@2.1.1: apps/app/patches/vite-plugin-mock-dev-server@2.1.1.patch
  wot-design-uni@1.14.0: apps/app/patches/wot-design-uni@1.14.0.patch
