import type { RolePermission } from "@01s-11comm/type";

/**
 * 模拟角色权限数据
 */
export const mockRolePermissionData: RolePermission[] = [
	{
		id: "1",
		name: "系统管理员",
		code: "ADMIN",
		description: "拥有系统所有权限",
		enabled: true,
	},
	{
		id: "2",
		name: "物业经理",
		code: "PROPERTY_MANAGER",
		description: "物业管理相关权限",
		enabled: true,
	},
	{
		id: "3",
		name: "客服专员",
		code: "CUSTOMER_SERVICE",
		description: "客户服务相关权限",
		enabled: true,
	},
	{
		id: "4",
		name: "财务人员",
		code: "FINANCE",
		description: "财务相关权限",
		enabled: true,
	},
	{
		id: "5",
		name: "安保人员",
		code: "SECURITY",
		description: "安保相关权限",
		enabled: true,
	},
	{
		id: "6",
		name: "维修人员",
		code: "MAINTENANCE",
		description: "设备维修相关权限",
		enabled: true,
	},
	{
		id: "7",
		name: "市场专员",
		code: "MARKETING",
		description: "市场营销相关权限",
		enabled: true,
	},
	{
		id: "8",
		name: "行政人员",
		code: "ADMINISTRATION",
		description: "行政事务相关权限",
		enabled: true,
	},
	{
		id: "9",
		name: "保洁人员",
		code: "CLEANING",
		description: "保洁服务相关权限",
		enabled: true,
	},
	{
		id: "10",
		name: "绿化人员",
		code: "GREENING",
		description: "绿化养护相关权限",
		enabled: true,
	},
	{
		id: "11",
		name: "项目经理",
		code: "PROJECT_MANAGER",
		description: "项目管理相关权限",
		enabled: true,
	},
	{
		id: "12",
		name: "运营主管",
		code: "OPERATION_SUPERVISOR",
		description: "运营管理相关权限",
		enabled: true,
	},
	{
		id: "13",
		name: "数据分析师",
		code: "DATA_ANALYST",
		description: "数据分析相关权限",
		enabled: true,
	},
	{
		id: "14",
		name: "人事专员",
		code: "HR_SPECIALIST",
		description: "人事管理相关权限",
		enabled: true,
	},
	{
		id: "15",
		name: "采购专员",
		code: "PURCHASING",
		description: "采购管理相关权限",
		enabled: true,
	},
	{
		id: "16",
		name: "仓管人员",
		code: "WAREHOUSE",
		description: "仓库管理相关权限",
		enabled: true,
	},
	{
		id: "17",
		name: "前台接待",
		code: "RECEPTIONIST",
		description: "前台接待相关权限",
		enabled: true,
	},
	{
		id: "18",
		name: "IT支持",
		code: "IT_SUPPORT",
		description: "IT支持相关权限",
		enabled: true,
	},
	{
		id: "19",
		name: "法务专员",
		code: "LEGAL",
		description: "法务相关权限",
		enabled: true,
	},
	{
		id: "20",
		name: "客户经理",
		code: "ACCOUNT_MANAGER",
		description: "客户关系管理权限",
		enabled: true,
	},
];
