import type { OrganizationTreeNode, Employee } from "@01s-11comm/type";

/**
 * 模拟组织树数据
 */
export const mockOrganizationTreeData: OrganizationTreeNode[] = [
	{
		id: "1",
		name: "总公司",
		icon: "mdi:domain",
		children: [
			{
				id: "2",
				name: "物业部",
				parentId: "1",
				icon: "mdi:account-hard-hat",
				children: [
					{
						id: "2-1",
						name: "客服中心",
						parentId: "2",
						icon: "mdi:face-agent",
					},
					{
						id: "2-2",
						name: "工程部",
						parentId: "2",
						icon: "mdi:hammer-wrench",
					},
					{
						id: "2-3",
						name: "安保部",
						parentId: "2",
						icon: "mdi:shield-account",
					},
				],
			},
			{
				id: "3",
				name: "运营部",
				parentId: "1",
				icon: "mdi:chart-line",
				children: [
					{
						id: "3-1",
						name: "市场部",
						parentId: "3",
						icon: "mdi:storefront",
					},
					{
						id: "3-2",
						name: "财务部",
						parentId: "3",
						icon: "mdi:finance",
					},
				],
			},
			{
				id: "4",
				name: "行政部",
				parentId: "1",
				icon: "mdi:account-group",
			},
		],
	},
];

/**
 * 模拟员工数据
 */
export const mockEmployeeData: Employee[] = [
	{
		id: "101",
		name: "张三",
		phone: "13800138001",
		position: "物业经理",
		email: "zhangsan@example.com",
		address: "北京市朝阳区",
		gender: "男",
		orgId: "2",
	},
	{
		id: "102",
		name: "李四",
		phone: "13800138002",
		position: "客服主管",
		email: "lisi@example.com",
		address: "北京市海淀区",
		gender: "女",
		orgId: "2-1",
	},
	{
		id: "103",
		name: "王五",
		phone: "13800138003",
		position: "维修工",
		email: "wangwu@example.com",
		address: "北京市丰台区",
		gender: "男",
		orgId: "2-2",
	},
	{
		id: "104",
		name: "赵六",
		phone: "13800138004",
		position: "保安队长",
		email: "zhaoliu@example.com",
		address: "北京市昌平区",
		gender: "男",
		orgId: "2-3",
	},
	{
		id: "105",
		name: "钱七",
		phone: "13800138005",
		position: "市场专员",
		email: "qianqi@example.com",
		address: "北京市大兴区",
		gender: "女",
		orgId: "3-1",
	},
	{
		id: "106",
		name: "孙八",
		phone: "13800138006",
		position: "会计",
		email: "sunba@example.com",
		address: "北京市通州区",
		gender: "女",
		orgId: "3-2",
	},
	{
		id: "107",
		name: "周九",
		phone: "13800138007",
		position: "行政助理",
		email: "zhoujiu@example.com",
		address: "北京市房山区",
		gender: "女",
		orgId: "4",
	},
	{
		id: "108",
		name: "吴十",
		phone: "13800138008",
		position: "客服专员",
		email: "wushi@example.com",
		address: "北京市顺义区",
		gender: "男",
		orgId: "2-1",
	},
	{
		id: "109",
		name: "陈十一",
		phone: "13800138009",
		position: "维修主管",
		email: "chenshiyi@example.com",
		address: "北京市东城区",
		gender: "男",
		orgId: "2-2",
	},
	{
		id: "110",
		name: "赵十二",
		phone: "13800138010",
		position: "安保主管",
		email: "zhaoshier@example.com",
		address: "北京市西城区",
		gender: "男",
		orgId: "2-3",
	},
	{
		id: "111",
		name: "钱十三",
		phone: "13800138011",
		position: "市场主管",
		email: "qianshisan@example.com",
		address: "北京市崇文区",
		gender: "女",
		orgId: "3-1",
	},
	{
		id: "112",
		name: "孙十四",
		phone: "13800138012",
		position: "财务主管",
		email: "sunsishi@example.com",
		address: "北京市宣武区",
		gender: "女",
		orgId: "3-2",
	},
	{
		id: "113",
		name: "周十五",
		phone: "13800138013",
		position: "行政主管",
		email: "zhouwushi@example.com",
		address: "北京市石景山区",
		gender: "女",
		orgId: "4",
	},
	{
		id: "114",
		name: "吴十六",
		phone: "13800138014",
		position: "客服专员",
		email: "wushiliu@example.com",
		address: "北京市门头沟区",
		gender: "男",
		orgId: "2-1",
	},
	{
		id: "115",
		name: "陈十七",
		phone: "13800138015",
		position: "维修工程师",
		email: "chenshiqi@example.com",
		address: "北京市房山区",
		gender: "男",
		orgId: "2-2",
	},
	{
		id: "116",
		name: "赵十八",
		phone: "13800138016",
		position: "安保专员",
		email: "zhaoshiba@example.com",
		address: "北京市通州区",
		gender: "男",
		orgId: "2-3",
	},
	{
		id: "117",
		name: "钱十九",
		phone: "13800138017",
		position: "市场专员",
		email: "qianshijiu@example.com",
		address: "北京市大兴区",
		gender: "女",
		orgId: "3-1",
	},
	{
		id: "118",
		name: "孙二十",
		phone: "13800138018",
		position: "出纳",
		email: "sunershi@example.com",
		address: "北京市昌平区",
		gender: "女",
		orgId: "3-2",
	},
	{
		id: "119",
		name: "周廿一",
		phone: "13800138019",
		position: "行政专员",
		email: "zhoueryi@example.com",
		address: "北京市怀柔区",
		gender: "女",
		orgId: "4",
	},
	{
		id: "120",
		name: "吴廿二",
		phone: "13800138020",
		position: "保洁主管",
		email: "wuerer@example.com",
		address: "北京市平谷区",
		gender: "男",
		orgId: "4",
	},
];
