-- Auto-generated clean script
BEGIN;
TRUNCATE TABLE "pk_parking_lots" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "pk_carports" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "pk_owner_vehicles" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "pk_carport_applications" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "pk_parking_structures" RESTART IDENTITY CASCADE;
COMMIT;