-- Auto-generated clean script

TRUNCATE TABLE "dt_dictionaries" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_cache_configs" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_config_types" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_configs" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_config_items" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_dictionary_items" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_menu_groups" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_menu_catalogs" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "dt_menu_items" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "cm_communities" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "cm_notices" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "cm_handing_business" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "cm_house_decorations" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "cm_property_registers" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "cm_building_structures" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_organizations" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_roles" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_staff" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_data_permissions" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_permissions" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_role_permissions" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_staff_roles" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_shifts" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_scheduling_settings" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_system_configs" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_register_protocols" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_initialize_cells" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_change_password_records" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "sm_community_configurations" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_owners" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_site_managements" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_reserve_venues" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_owners_committees" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_houses" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_owner_members" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_owner_accounts" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_invoice_titles" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_invoices" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "hp_reserve_venue_orders" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_property_companies" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_merchants" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_community_info" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_community_configs" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_register_protocols" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_merchant_admins" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_report_groups" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_report_infos" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "op_report_components" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_first_parties" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_second_parties" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_templates" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_clauses" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_types" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_contracts" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_attachments" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_changes" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_archives" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_prints" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ct_reviews" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pk_parking_lots" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pk_carports" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pk_owner_vehicles" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pk_carport_applications" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pk_parking_structures" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_expense_items" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_meter_reading_types" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_meter_readings" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_payments" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_discount_types" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_discount_settings" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_discount_applications" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_payment_reviews" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_refund_reviews" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_cancel_fees" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_overdue_reminders" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_reprint_vouchers" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "ex_expense_summary_tables" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pt_patrol_plans" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pt_patrol_paths" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pt_patrol_points" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pt_patrol_items" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pt_patrol_tasks" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "pt_patrol_task_details" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rp_repair_orders" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rp_repair_types" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rp_repair_settings" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rp_phone_repair_reports" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rp_repair_order_histories" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rp_mandatory_return_issues" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rp_return_visits" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_expense_summaries" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_deposit_reports" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_payment_details" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_fee_reminders" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_no_charge_houses" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_outstanding_fees" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_patrol_reports" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_repair_reports" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_repair_summaries" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_statement_expenses" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
TRUNCATE TABLE "rpt_data_statistics" RESTART IDENTITY CASCADE;
/* STATEMENT_END */
