import type { ExpenseItemSettingListItem } from "@01s-11comm/type";

/** Expense Item Setting 模拟数据 */
export const mockExpenseItemSettingData: ExpenseItemSettingListItem[] = [
    {
        id: "1",
        code: "EXP001",
        feeType: "物业费",
        expenseItem: "住宅物业费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "面积 * 单价",
        billingUnitPrice: "2.5",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-01-15 09:00:00",
        updateTime: "2024-01-15 09:00:00",
        remark: "模拟数据 1",
    },
    {
        id: "2",
        code: "EXP002",
        feeType: "水费",
        expenseItem: "居民用水",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "用量 * 单价",
        billingUnitPrice: "3.5",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-01-16 10:30:00",
        updateTime: "2024-01-16 10:30:00",
        remark: "模拟数据 2",
    },
    {
        id: "3",
        code: "EXP003",
        feeType: "电费",
        expenseItem: "居民用电",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "用量 * 单价",
        billingUnitPrice: "0.6",
        fixedFee: "0",
        accountDeduction: "是",
        status: "禁用",
        createTime: "2024-01-17 11:45:00",
        updateTime: "2024-01-17 11:45:00",
        remark: "模拟数据 3",
    },
    {
        id: "4",
        code: "EXP004",
        feeType: "停车费",
        expenseItem: "车位租赁费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "固定金额",
        billingUnitPrice: "300",
        fixedFee: "0",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-01-18 08:20:00",
        updateTime: "2024-01-18 08:20:00",
        remark: "模拟数据 4",
    },
    {
        id: "5",
        code: "EXP005",
        feeType: "燃气费",
        expenseItem: "居民用气",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "用量 * 单价",
        billingUnitPrice: "2.8",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-01-19 14:10:00",
        updateTime: "2024-01-19 14:10:00",
        remark: "模拟数据 5",
    },
    {
        id: "6",
        code: "EXP006",
        feeType: "取暖费",
        expenseItem: "冬季取暖费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "季度",
        formula: "面积 * 单价",
        billingUnitPrice: "22",
        fixedFee: "0",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-01-20 09:30:00",
        updateTime: "2024-01-20 09:30:00",
        remark: "模拟数据 6",
    },
    {
        id: "7",
        code: "EXP007",
        feeType: "维修费",
        expenseItem: "公共维修费",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "实际维修费用",
        billingUnitPrice: "0",
        fixedFee: "100",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-01-21 11:00:00",
        updateTime: "2024-01-21 11:00:00",
        remark: "模拟数据 7",
    },
    {
        id: "8",
        code: "EXP008",
        feeType: "服务费",
        expenseItem: "家政服务费",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "服务时长 * 单价",
        billingUnitPrice: "50",
        fixedFee: "0",
        accountDeduction: "否",
        status: "禁用",
        createTime: "2024-01-22 16:40:00",
        updateTime: "2024-01-22 16:40:00",
        remark: "模拟数据 8",
    },
    {
        id: "9",
        code: "EXP009",
        feeType: "押金",
        expenseItem: "租房押金",
        expenseIdentifier: "一次性费用",
        paymentType: "预付费",
        paymentCycle: "一次性",
        formula: "固定金额",
        billingUnitPrice: "0",
        fixedFee: "2000",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-01-23 10:15:00",
        updateTime: "2024-01-23 10:15:00",
        remark: "模拟数据 9",
    },
    {
        id: "10",
        code: "EXP010",
        feeType: "租金",
        expenseItem: "房屋租金",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "固定金额",
        billingUnitPrice: "0",
        fixedFee: "2500",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-01-24 13:25:00",
        updateTime: "2024-01-24 13:25:00",
        remark: "模拟数据 10",
    },
    {
        id: "11",
        code: "EXP011",
        feeType: "公摊费",
        expenseItem: "公共区域电费分摊",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "面积分摊",
        billingUnitPrice: "0.5",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-01-25 09:45:00",
        updateTime: "2024-01-25 09:45:00",
        remark: "模拟数据 11",
    },
    {
        id: "12",
        code: "EXP012",
        feeType: "物业费",
        expenseItem: "商业物业费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "面积 * 单价",
        billingUnitPrice: "5",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-01-26 14:35:00",
        updateTime: "2024-01-26 14:35:00",
        remark: "模拟数据 12",
    },
    {
        id: "13",
        code: "EXP013",
        feeType: "停车费",
        expenseItem: "临时停车费",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "次",
        formula: "时长 * 单价",
        billingUnitPrice: "5",
        fixedFee: "0",
        accountDeduction: "否",
        status: "禁用",
        createTime: "2024-01-27 11:20:00",
        updateTime: "2024-01-27 11:20:00",
        remark: "模拟数据 13",
    },
    {
        id: "14",
        code: "EXP014",
        feeType: "水费",
        expenseItem: "商业用水",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "用量 * 单价",
        billingUnitPrice: "5",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-01-28 08:50:00",
        updateTime: "2024-01-28 08:50:00",
        remark: "模拟数据 14",
    },
    {
        id: "15",
        code: "EXP015",
        feeType: "电费",
        expenseItem: "商业用电",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "用量 * 单价",
        billingUnitPrice: "1",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-01-29 15:10:00",
        updateTime: "2024-01-29 15:10:00",
        remark: "模拟数据 15",
    },
    {
        id: "16",
        code: "EXP016",
        feeType: "其他",
        expenseItem: "快递代收费",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "件数 * 单价",
        billingUnitPrice: "1",
        fixedFee: "0",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-01-30 10:00:00",
        updateTime: "2024-01-30 10:00:00",
        remark: "模拟数据 16",
    },
    {
        id: "17",
        code: "EXP017",
        feeType: "服务费",
        expenseItem: "健身房使用费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "固定金额",
        billingUnitPrice: "0",
        fixedFee: "100",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-01-31 13:40:00",
        updateTime: "2024-01-31 13:40:00",
        remark: "模拟数据 17",
    },
    {
        id: "18",
        code: "EXP018",
        feeType: "物业费",
        expenseItem: "别墅物业费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "面积 * 单价",
        billingUnitPrice: "3.5",
        fixedFee: "0",
        accountDeduction: "是",
        status: "禁用",
        createTime: "2024-02-01 09:25:00",
        updateTime: "2024-02-01 09:25:00",
        remark: "模拟数据 18",
    },
    {
        id: "19",
        code: "EXP019",
        feeType: "维修费",
        expenseItem: "设备维护费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "季度",
        formula: "固定金额",
        billingUnitPrice: "0",
        fixedFee: "500",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-02-02 14:55:00",
        updateTime: "2024-02-02 14:55:00",
        remark: "模拟数据 19",
    },
    {
        id: "20",
        code: "EXP020",
        feeType: "停车费",
        expenseItem: "车位管理费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "固定金额",
        billingUnitPrice: "0",
        fixedFee: "50",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-02-03 11:35:00",
        updateTime: "2024-02-03 11:35:00",
        remark: "模拟数据 20",
    },
    {
        id: "21",
        code: "EXP021",
        feeType: "燃气费",
        expenseItem: "商业用气",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "月",
        formula: "用量 * 单价",
        billingUnitPrice: "4",
        fixedFee: "0",
        accountDeduction: "是",
        status: "启用",
        createTime: "2024-02-04 08:15:00",
        updateTime: "2024-02-04 08:15:00",
        remark: "模拟数据 21",
    },
    {
        id: "22",
        code: "EXP022",
        feeType: "取暖费",
        expenseItem: "商业取暖费",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "季度",
        formula: "面积 * 单价",
        billingUnitPrice: "30",
        fixedFee: "0",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-02-05 16:20:00",
        updateTime: "2024-02-05 16:20:00",
        remark: "模拟数据 22",
    },
    {
        id: "23",
        code: "EXP023",
        feeType: "公摊费",
        expenseItem: "公共区域水费分摊",
        expenseIdentifier: "周期性费用",
        paymentType: "预付费",
        paymentCycle: "月",
        formula: "面积分摊",
        billingUnitPrice: "0.3",
        fixedFee: "0",
        accountDeduction: "是",
        status: "禁用",
        createTime: "2024-02-06 10:50:00",
        updateTime: "2024-02-06 10:50:00",
        remark: "模拟数据 23",
    },
    {
        id: "24",
        code: "EXP024",
        feeType: "服务费",
        expenseItem: "游泳池使用费",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "次",
        formula: "固定金额",
        billingUnitPrice: "0",
        fixedFee: "20",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-02-07 15:30:00",
        updateTime: "2024-02-07 15:30:00",
        remark: "模拟数据 24",
    },
    {
        id: "25",
        code: "EXP025",
        feeType: "其他",
        expenseItem: "门禁卡工本费",
        expenseIdentifier: "一次性费用",
        paymentType: "后付费",
        paymentCycle: "次",
        formula: "固定金额",
        billingUnitPrice: "0",
        fixedFee: "30",
        accountDeduction: "否",
        status: "启用",
        createTime: "2024-02-08 12:10:00",
        updateTime: "2024-02-08 12:10:00",
        remark: "模拟数据 25",
    },
];
