import type { ExpenseItemSettingListItem } from "@01s-11comm/type";

/**
 * @description expense-item-setting模拟数据
 * ExpenseItemSetting mock data
 */
export const mockExpenseItemSettingData: ExpenseItemSettingListItem[] = [
	{
		id: "1",
		code: "F001",
		feeType: "物业费",
		expenseItem: "住宅物业费",
		expenseIdentifier: "周期性费用",
		paymentType: "预付费",
		paymentCycle: "1",
		formula: "单价*面积",
		billingUnitPrice: "2.5",
		fixedFee: "0",
		accountDeduction: "是",
		status: "启用",
		createTime: "2024-01-01 10:00:00",
		updateTime: "2024-01-01 10:00:00",
		remark: "这是示例数据1",
	},
	{
		id: "2",
		code: "F002",
		feeType: "水费",
		expenseItem: "居民用水",
		expenseIdentifier: "周期性费用",
		paymentType: "后付费",
		paymentCycle: "1",
		formula: "单价*用量",
		billingUnitPrice: "3.5",
		fixedFee: "0",
		accountDeduction: "是",
		status: "启用",
		createTime: "2024-01-02 11:00:00",
		updateTime: "2024-01-02 11:00:00",
		remark: "这是示例数据2",
	},
	{
		id: "3",
		code: "F003",
		feeType: "电费",
		expenseItem: "居民用电",
		expenseIdentifier: "周期性费用",
		paymentType: "后付费",
		paymentCycle: "1",
		formula: "单价*用量",
		billingUnitPrice: "0.6",
		fixedFee: "0",
		accountDeduction: "是",
		status: "禁用",
		createTime: "2024-01-03 12:00:00",
		updateTime: "2024-01-03 12:00:00",
		remark: "这是示例数据3",
	},
	{
		id: "4",
		code: "F004",
		feeType: "停车费",
		expenseItem: "地下车位费",
		expenseIdentifier: "周期性费用",
		paymentType: "预付费",
		paymentCycle: "1",
		formula: "固定金额",
		billingUnitPrice: "0",
		fixedFee: "300",
		accountDeduction: "是",
		status: "启用",
		createTime: "2024-01-04 13:00:00",
		updateTime: "2024-01-04 13:00:00",
	},
	{
		id: "5",
		code: "F005",
		feeType: "其他",
		expenseItem: "门禁卡费",
		expenseIdentifier: "一次性费用",
		paymentType: "预付费",
		paymentCycle: "0",
		formula: "固定金额",
		billingUnitPrice: "0",
		fixedFee: "50",
		accountDeduction: "否",
		status: "启用",
		createTime: "2024-01-05 14:00:00",
		updateTime: "2024-01-05 14:00:00",
		remark: "这是示例数据5",
	},
];
