import type { PropertyCompanyListItem } from "@01s-11comm/type";

/**
 * @description 物业公司模拟数据
 * Property company mock data
 */
export const mockPropertyCompanyData: PropertyCompanyListItem[] = [
	{
		companyId: "PM001",
		companyName: "中航物业管理有限公司",
		address: "深圳市南山区科技园南区中航大厦",
		administrator: "张伟华",
		phone: "0755-26888888",
		legalRepresentative: "李明强",
		establishmentDate: "2010-03-15",
		landmark: "中航大厦A座",
		createTime: "2024-01-15 09:30:00",
		communityCount: 15,
		companyType: "国企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "深圳本土知名物业公司",
	},
	{
		companyId: "PM002",
		companyName: "万科物业服务股份有限公司",
		address: "深圳市盐田区万科中心大厦",
		administrator: "王小丽",
		phone: "0755-25999999",
		legalRepresentative: "陈建国",
		establishmentDate: "2008-07-20",
		landmark: "万科中心",
		createTime: "2024-01-16 10:15:00",
		communityCount: 25,
		companyType: "民企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "全国领先物业公司",
	},
	{
		companyId: "PM003",
		companyName: "绿城物业服务集团有限公司",
		address: "杭州市西湖区绿城广场",
		administrator: "刘建平",
		phone: "0571-87654321",
		legalRepresentative: "赵志强",
		establishmentDate: "2012-05-08",
		landmark: "绿城广场",
		createTime: "2024-01-17 14:20:00",
		communityCount: 18,
		companyType: "民企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "杭州知名物业公司",
	},
	{
		companyId: "PM004",
		companyName: "碧桂园生活服务集团股份有限公司",
		address: "广东省佛山市顺德区碧桂园总部大楼",
		administrator: "周美琳",
		phone: "0757-26668888",
		legalRepresentative: "吴海军",
		establishmentDate: "2014-11-12",
		landmark: "碧桂园总部",
		createTime: "2024-01-18 16:45:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM005",
		companyName: "保利物业发展股份有限公司",
		address: "广州市海珠区保利中心",
		administrator: "马晓东",
		phone: "020-38888888",
		legalRepresentative: "孙建华",
		establishmentDate: "2009-09-25",
		landmark: "保利中心",
		createTime: "2024-01-19 11:30:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM006",
		companyName: "华润万象生活有限公司",
		address: "深圳市罗湖区华润大厦",
		administrator: "李雅芳",
		phone: "0755-82888888",
		legalRepresentative: "徐志明",
		establishmentDate: "2011-02-14",
		landmark: "华润大厦",
		createTime: "2024-01-20 08:45:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM007",
		companyName: "龙湖智慧服务有限公司",
		address: "重庆市渝北区龙湖时代天街",
		administrator: "钱志华",
		phone: "023-67777777",
		legalRepresentative: "田丽娟",
		establishmentDate: "2013-06-30",
		landmark: "时代天街",
		createTime: "2024-01-21 13:15:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM008",
		companyName: "招商积余投资管理有限公司",
		address: "深圳市南山区招商银行大厦",
		administrator: "何建国",
		phone: "0755-83666666",
		legalRepresentative: "郑小明",
		establishmentDate: "2015-04-18",
		landmark: "招商银行大厦",
		createTime: "2024-01-22 15:40:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM009",
		companyName: "融创服务控股有限公司",
		address: "天津市滨海新区融创中心",
		administrator: "朱丽华",
		phone: "022-58555555",
		legalRepresentative: "高志强",
		establishmentDate: "2016-08-22",
		landmark: "融创中心",
		createTime: "2024-01-23 09:20:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM010",
		companyName: "新城悦服务集团有限公司",
		address: "上海市长宁区新城控股中心",
		administrator: "林小燕",
		phone: "021-52444444",
		legalRepresentative: "黄志军",
		establishmentDate: "2017-12-05",
		landmark: "新城控股中心",
		createTime: "2024-01-24 12:10:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM011",
		companyName: "佳兆业物业集团有限公司",
		address: "深圳市罗湖区深南东路佳兆业中心",
		administrator: "陈家豪",
		phone: "0755-88886666",
		legalRepresentative: "李伟明",
		establishmentDate: "2016-06-18",
		landmark: "佳兆业中心",
		createTime: "2024-01-25 14:30:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM012",
		companyName: "雅居乐雅生活服务股份有限公司",
		address: "广州市番禺区雅居乐中心",
		administrator: "张丽华",
		phone: "020-38886666",
		legalRepresentative: "王志东",
		establishmentDate: "2015-09-22",
		landmark: "雅居乐中心",
		createTime: "2024-01-26 09:15:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM013",
		companyName: "蓝光嘉宝服务集团股份有限公司",
		address: "成都市高新区蓝光中心大厦",
		administrator: "刘建国",
		phone: "028-86668888",
		legalRepresentative: "赵志强",
		establishmentDate: "2014-12-08",
		landmark: "蓝光中心",
		createTime: "2024-01-27 11:45:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM014",
		companyName: "建业新生活集团有限公司",
		address: "郑州市郑东新区建业中心",
		administrator: "孙伟民",
		phone: "0371-69998888",
		legalRepresentative: "胡明辉",
		establishmentDate: "2013-05-15",
		landmark: "建业中心",
		createTime: "2024-01-28 16:20:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM015",
		companyName: "朗诗绿色生活服务有限公司",
		address: "南京市建邺区朗诗中心",
		administrator: "周文静",
		phone: "025-86668888",
		legalRepresentative: "田浩然",
		establishmentDate: "2012-08-28",
		landmark: "朗诗中心",
		createTime: "2024-01-29 10:30:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM016",
		companyName: "美的物业股份有限公司",
		address: "佛山市顺德区美的总部大厦",
		administrator: "黄海波",
		phone: "0757-26669999",
		legalRepresentative: "林金华",
		establishmentDate: "2011-11-12",
		landmark: "美的总部",
		createTime: "2024-01-30 13:50:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM017",
		companyName: "金科智慧服务集团股份有限公司",
		address: "重庆市渝北区金科中心",
		administrator: "杨晓峰",
		phone: "023-67778888",
		legalRepresentative: "陈晓龙",
		establishmentDate: "2010-04-20",
		landmark: "金科中心",
		createTime: "2024-01-31 15:40:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM018",
		companyName: "世茂服务控股有限公司",
		address: "上海市浦东新区世茂大厦",
		administrator: "张雪梅",
		phone: "021-58888888",
		legalRepresentative: "许荣茂",
		establishmentDate: "2009-07-15",
		landmark: "世茂大厦",
		createTime: "2024-02-01 08:25:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "一级",
		operationStatus: "正常运营",
		remarks: "",
	},
	{
		companyId: "PM019",
		companyName: "奥园健康生活集团有限公司",
		address: "广州市天河区奥园大厦",
		administrator: "李国华",
		phone: "020-38888888",
		legalRepresentative: "郭梓文",
		establishmentDate: "2008-10-08",
		landmark: "奥园大厦",
		createTime: "2024-02-02 11:10:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "二级",
		operationStatus: "暂停运营",
		remarks: "",
	},
	{
		companyId: "PM020",
		companyName: "宋都服务集团有限公司",
		address: "杭州市西湖区宋城大厦",
		administrator: "王秀兰",
		phone: "0571-87000000",
		legalRepresentative: "俞建午",
		establishmentDate: "2007-03-22",
		landmark: "宋城大厦",
		createTime: "2024-02-03 14:55:00",
		communityCount: 0,
		companyType: "民企",
		serviceLevel: "三级",
		operationStatus: "正常运营",
		remarks: "",
	},
];

