/**
 * @file 班次设置假数据
 * @description Shift setting mock data
 */

import type { ShiftSettingListItem } from "@01s-11comm/type";

/**
 * 班次设置假数据
 * Shift setting mock data
 */
export const mockShiftSettingData: ShiftSettingListItem[] = [
	{
		id: "1",
		name: "早班",
		type: "白班",
		startTime: "08:00",
		endTime: "16:00",
		enabled: true,
		description: "早班时间段",
	},
	{
		id: "2",
		name: "中班",
		type: "中班",
		startTime: "16:00",
		endTime: "24:00",
		enabled: true,
		description: "中班时间段",
	},
	{
		id: "3",
		name: "晚班",
		type: "夜班",
		startTime: "00:00",
		endTime: "08:00",
		enabled: true,
		description: "晚班时间段",
	},
	{
		id: "4",
		name: "全天班",
		type: "全天",
		startTime: "00:00",
		endTime: "23:59",
		enabled: true,
		description: "全天24小时",
	},
	{
		id: "5",
		name: "上午班",
		type: "白班",
		startTime: "09:00",
		endTime: "13:00",
		enabled: true,
		description: "上午工作时间",
	},
	{
		id: "6",
		name: "下午班",
		type: "白班",
		startTime: "14:00",
		endTime: "18:00",
		enabled: true,
		description: "下午工作时间",
	},
	{
		id: "7",
		name: "夜间巡逻",
		type: "夜班",
		startTime: "22:00",
		endTime: "06:00",
		enabled: true,
		description: "夜间安保巡逻",
	},
	{
		id: "8",
		name: "周末班",
		type: "白班",
		startTime: "10:00",
		endTime: "18:00",
		enabled: true,
		description: "周末值班时间",
	},
	{
		id: "9",
		name: "节假日班",
		type: "全天",
		startTime: "08:00",
		endTime: "20:00",
		enabled: true,
		description: "节假日值班",
	},
	{
		id: "10",
		name: "临时班",
		type: "中班",
		startTime: "12:00",
		endTime: "20:00",
		enabled: false,
		description: "临时调配班次",
	},
	{
		id: "11",
		name: "保洁早班",
		type: "白班",
		startTime: "06:00",
		endTime: "14:00",
		enabled: true,
		description: "保洁人员早班",
	},
	{
		id: "12",
		name: "保洁晚班",
		type: "夜班",
		startTime: "18:00",
		endTime: "02:00",
		enabled: true,
		description: "保洁人员晚班",
	},
	{
		id: "13",
		name: "安保A班",
		type: "白班",
		startTime: "08:00",
		endTime: "20:00",
		enabled: true,
		description: "安保A组白班",
	},
	{
		id: "14",
		name: "安保B班",
		type: "夜班",
		startTime: "20:00",
		endTime: "08:00",
		enabled: true,
		description: "安保B组夜班",
	},
	{
		id: "15",
		name: "维修班",
		type: "白班",
		startTime: "09:00",
		endTime: "17:00",
		enabled: true,
		description: "维修人员工作时间",
	},
	{
		id: "16",
		name: "客服班",
		type: "白班",
		startTime: "08:30",
		endTime: "17:30",
		enabled: true,
		description: "客服人员工作时间",
	},
	{
		id: "17",
		name: "紧急班",
		type: "全天",
		startTime: "00:00",
		endTime: "23:59",
		enabled: false,
		description: "紧急情况待命",
	},
	{
		id: "18",
		name: "轮休班",
		type: "中班",
		startTime: "10:00",
		endTime: "22:00",
		enabled: true,
		description: "轮休人员班次",
	},
	{
		id: "19",
		name: "培训班",
		type: "白班",
		startTime: "09:00",
		endTime: "12:00",
		enabled: true,
		description: "员工培训时间",
	},
	{
		id: "20",
		name: "备用班",
		type: "中班",
		startTime: "13:00",
		endTime: "21:00",
		enabled: false,
		description: "备用班次",
	},
];
