import type { ChangePasswordRecordListItem } from "@01s-11comm/type";

/** 密码修改记录模拟数据 */
export const mockChangePasswordRecordData: ChangePasswordRecordListItem[] = [
    {
        recordId: "REC001",
        username: "admin",
        realName: "系统管理员",
        userRole: "超级管理员",
        department: "技术部",
        phone: "138****0001",
        email: "admin@11comm.com",
        changeTime: "2024-11-20 09:15:30",
        ipAddress: "192.168.1.100",
        location: "北京市朝阳区总部",
        changeMethod: "用户自行修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "系统管理员",
        remark: "定期安全更新密码",
    },
    {
        recordId: "REC002",
        username: "operator001",
        realName: "张三",
        userRole: "运营团队",
        department: "运营部",
        phone: "139****0002",
        email: "zhangsan@11comm.com",
        changeTime: "2024-11-20 10:22:15",
        ipAddress: "192.168.1.101",
        location: "北京市朝阳区总部",
        changeMethod: "管理员重置",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "系统管理员",
        remark: "用户忘记密码，管理员协助重置",
    },
    {
        recordId: "REC003",
        username: "property001",
        realName: "李四",
        userRole: "物业团队",
        department: "物业部",
        phone: "137****0003",
        email: "lisi@11comm.com",
        changeTime: "2024-11-20 11:45:20",
        ipAddress: "192.168.1.102",
        location: "上海市浦东新区分公司",
        changeMethod: "忘记密码找回",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "李四",
        remark: "通过邮箱验证找回密码",
    },
    {
        recordId: "REC004",
        username: "service001",
        realName: "王五",
        userRole: "客服团队",
        department: "客服部",
        phone: "136****0004",
        email: "wangwu@11comm.com",
        changeTime: "2024-11-20 13:30:45",
        ipAddress: "192.168.1.103",
        location: "广州市天河区分公司",
        changeMethod: "首次登录修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "王五",
        remark: "新员工首次登录系统修改初始密码",
    },
    {
        recordId: "REC005",
        username: "finance001",
        realName: "赵六",
        userRole: "财务团队",
        department: "财务部",
        phone: "135****0005",
        email: "zhaoliu@11comm.com",
        changeTime: "2024-11-20 14:15:10",
        ipAddress: "192.168.1.104",
        location: "深圳市南山区分公司",
        changeMethod: "定期强制修改",
        status: "失败",
        success: "否",
        failureReason: "新密码不符合复杂度要求",
        operator: "赵六",
        remark: "密码强度不足，需要包含大小写字母、数字和特殊字符",
    },
    {
        recordId: "REC006",
        username: "repair001",
        realName: "孙七",
        userRole: "维修团队",
        department: "维修部",
        phone: "134****0006",
        email: "sunqi@11comm.com",
        changeTime: "2024-11-20 15:20:25",
        ipAddress: "192.168.1.105",
        location: "成都市高新区分公司",
        changeMethod: "用户自行修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "孙七",
        remark: "定期安全更新",
    },
    {
        recordId: "REC007",
        username: "security001",
        realName: "周八",
        userRole: "保安团队",
        department: "保安部",
        phone: "133****0007",
        email: "zhouba@11comm.com",
        changeTime: "2024-11-20 16:05:40",
        ipAddress: "192.168.1.106",
        location: "杭州市西湖区分公司",
        changeMethod: "管理员重置",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "系统管理员",
        remark: "账户异常，强制重置密码",
    },
    {
        recordId: "REC008",
        username: "user001",
        realName: "吴九",
        userRole: "普通用户",
        department: "行政部",
        phone: "132****0008",
        email: "wujiu@11comm.com",
        changeTime: "2024-11-20 17:10:55",
        ipAddress: "192.168.1.107",
        location: "南京市建邺区分公司",
        changeMethod: "忘记密码找回",
        status: "处理中",
        success: "否",
        failureReason: "",
        operator: "吴九",
        remark: "正在通过手机验证码找回密码",
    },
    {
        recordId: "REC009",
        username: "operator002",
        realName: "郑十",
        userRole: "运营团队",
        department: "运营部",
        phone: "131****0009",
        email: "zhengshi@11comm.com",
        changeTime: "2024-11-19 09:30:15",
        ipAddress: "192.168.1.108",
        location: "武汉市洪山区分公司",
        changeMethod: "用户自行修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "郑十",
        remark: "个人安全设置更新",
    },
    {
        recordId: "REC010",
        username: "property002",
        realName: "陈一",
        userRole: "物业团队",
        department: "物业部",
        phone: "130****0010",
        email: "chenyi@11comm.com",
        changeTime: "2024-11-19 10:45:30",
        ipAddress: "192.168.1.109",
        location: "西安市雁塔区分公司",
        changeMethod: "定期强制修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "陈一",
        remark: "系统强制90天更新密码",
    },
    {
        recordId: "REC011",
        username: "service002",
        realName: "林二",
        userRole: "客服团队",
        department: "客服部",
        phone: "139****0011",
        email: "liner@11comm.com",
        changeTime: "2024-11-19 11:20:45",
        ipAddress: "192.168.1.110",
        location: "重庆市渝中区分公司",
        changeMethod: "管理员重置",
        status: "失败",
        success: "否",
        failureReason: "邮箱验证码已过期",
        operator: "系统管理员",
        remark: "用户未及时输入验证码，需要重新申请",
    },
    {
        recordId: "REC012",
        username: "finance002",
        realName: "黄三",
        userRole: "财务团队",
        department: "财务部",
        phone: "138****0012",
        email: "huangsan@11comm.com",
        changeTime: "2024-11-19 14:30:20",
        ipAddress: "192.168.1.111",
        location: "天津市和平区分公司",
        changeMethod: "首次登录修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "黄三",
        remark: "新员工入职初始化密码",
    },
    {
        recordId: "REC013",
        username: "repair002",
        realName: "张四",
        userRole: "维修团队",
        department: "维修部",
        phone: "137****0013",
        email: "zhangsi@11comm.com",
        changeTime: "2024-11-19 15:15:35",
        ipAddress: "192.168.1.112",
        location: "苏州市工业园区分公司",
        changeMethod: "用户自行修改",
        status: "已取消",
        success: "否",
        failureReason: "",
        operator: "张四",
        remark: "用户主动取消修改操作",
    },
    {
        recordId: "REC014",
        username: "security002",
        realName: "李五",
        userRole: "保安团队",
        department: "保安部",
        phone: "136****0014",
        email: "liwu@11comm.com",
        changeTime: "2024-11-19 16:40:10",
        ipAddress: "192.168.1.113",
        location: "青岛市市南区办事处",
        changeMethod: "忘记密码找回",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "李五",
        remark: "通过手机短信验证成功找回密码",
    },
    {
        recordId: "REC015",
        username: "user002",
        realName: "王六",
        userRole: "普通用户",
        department: "技术部",
        phone: "135****0015",
        email: "wangliu@11comm.com",
        changeTime: "2024-11-19 17:25:50",
        ipAddress: "192.168.1.114",
        location: "大连市中山区办事处",
        changeMethod: "定期强制修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "王六",
        remark: "符合安全规范的密码更新",
    },
    {
        recordId: "REC016",
        username: "operator003",
        realName: "赵七",
        userRole: "运营团队",
        department: "运营部",
        phone: "134****0016",
        email: "zhaoqi@11comm.com",
        changeTime: "2024-11-18 09:10:25",
        ipAddress: "192.168.1.115",
        location: "厦门市思明区办事处",
        changeMethod: "用户自行修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "赵七",
        remark: "怀疑账户泄露，主动修改密码",
    },
    {
        recordId: "REC017",
        username: "property003",
        realName: "孙八",
        userRole: "物业团队",
        department: "物业部",
        phone: "133****0017",
        email: "sunba@11comm.com",
        changeTime: "2024-11-18 10:35:40",
        ipAddress: "192.168.1.116",
        location: "长沙市岳麓区办事处",
        changeMethod: "管理员重置",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "系统管理员",
        remark: "多次登录失败，账户被锁定，管理员重置",
    },
    {
        recordId: "REC018",
        username: "service003",
        realName: "周九",
        userRole: "客服团队",
        department: "客服部",
        phone: "132****0018",
        email: "zhoujiu@11comm.com",
        changeTime: "2024-11-18 13:50:15",
        ipAddress: "192.168.1.117",
        location: "佛山市南海区办事处",
        changeMethod: "首次登录修改",
        status: "失败",
        success: "否",
        failureReason: "原密码输入错误",
        operator: "周九",
        remark: "用户忘记了初始密码",
    },
    {
        recordId: "REC019",
        username: "finance003",
        realName: "吴十",
        userRole: "财务团队",
        department: "财务部",
        phone: "131****0019",
        email: "wushi@11comm.com",
        changeTime: "2024-11-18 14:20:30",
        ipAddress: "192.168.1.118",
        location: "东莞市东城区办事处",
        changeMethod: "忘记密码找回",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "吴十",
        remark: "通过密保问题验证找回密码",
    },
    {
        recordId: "REC020",
        username: "repair003",
        realName: "郑一",
        userRole: "维修团队",
        department: "维修部",
        phone: "130****0020",
        email: "zhengyi@11comm.com",
        changeTime: "2024-11-18 15:45:55",
        ipAddress: "192.168.1.119",
        location: "合肥市蜀山区办事处",
        changeMethod: "定期强制修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "郑一",
        remark: "系统定期安全检查要求",
    },
    {
        recordId: "REC021",
        username: "security003",
        realName: "陈二",
        userRole: "保安团队",
        department: "保安部",
        phone: "139****0021",
        email: "chener@11comm.com",
        changeTime: "2024-11-18 16:30:20",
        ipAddress: "192.168.1.120",
        location: "济南市历下区办事处",
        changeMethod: "用户自行修改",
        status: "处理中",
        success: "否",
        failureReason: "",
        operator: "陈二",
        remark: "正在进行短信验证",
    },
    {
        recordId: "REC022",
        username: "user003",
        realName: "林三",
        userRole: "普通用户",
        department: "行政部",
        phone: "138****0022",
        email: "linsan@11comm.com",
        changeTime: "2024-11-18 17:15:45",
        ipAddress: "192.168.1.121",
        location: "郑州市金水区办事处",
        changeMethod: "管理员重置",
        status: "已取消",
        success: "否",
        failureReason: "",
        operator: "林三",
        remark: "用户主动联系管理员取消操作",
    },
    {
        recordId: "REC023",
        username: "temp_user001",
        realName: "临时用户",
        userRole: "普通用户",
        department: "客服部",
        phone: "137****0023",
        email: "temp001@11comm.com",
        changeTime: "2024-11-17 09:40:10",
        ipAddress: "192.168.1.122",
        location: "石家庄市长安区办事处",
        changeMethod: "首次登录修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "临时用户",
        remark: "临时账户初始化密码",
    },
    {
        recordId: "REC024",
        username: "guest_user001",
        realName: "访客用户",
        userRole: "普通用户",
        department: "行政部",
        phone: "136****0024",
        email: "guest001@11comm.com",
        changeTime: "2024-11-17 10:55:25",
        ipAddress: "192.168.1.123",
        location: "太原市小店区办事处",
        changeMethod: "忘记密码找回",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "访客用户",
        remark: "访客账户密码找回",
    },
    {
        recordId: "REC025",
        username: "test_user001",
        realName: "测试用户",
        userRole: "普通用户",
        department: "技术部",
        phone: "135****0025",
        email: "test001@11comm.com",
        changeTime: "2024-11-17 13:20:40",
        ipAddress: "192.168.1.124",
        location: "呼和浩特市赛罕区办事处",
        changeMethod: "用户自行修改",
        status: "失败",
        success: "否",
        failureReason: "网络连接超时",
        operator: "测试用户",
        remark: "网络不稳定导致操作失败",
    },
    {
        recordId: "REC026",
        username: "admin_assistant",
        realName: "管理员助理",
        userRole: "运营团队",
        department: "运营部",
        phone: "134****0026",
        email: "assistant@11comm.com",
        changeTime: "2024-11-17 14:45:15",
        ipAddress: "192.168.1.125",
        location: "沈阳市沈河区办事处",
        changeMethod: "定期强制修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "管理员助理",
        remark: "助理权限账户密码更新",
    },
    {
        recordId: "REC027",
        username: "property_manager",
        realName: "物业经理",
        userRole: "物业团队",
        department: "物业部",
        phone: "133****0027",
        email: "manager@11comm.com",
        changeTime: "2024-11-17 15:30:50",
        ipAddress: "192.168.1.126",
        location: "长春市朝阳区办事处",
        changeMethod: "管理员重置",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "系统管理员",
        remark: "权限变更，强制密码重置",
    },
    {
        recordId: "REC028",
        username: "service_lead",
        realName: "客服主管",
        userRole: "客服团队",
        department: "客服部",
        phone: "132****0028",
        email: "lead@11comm.com",
        changeTime: "2024-11-17 16:15:35",
        ipAddress: "192.168.1.127",
        location: "哈尔滨市道里区办事处",
        changeMethod: "用户自行修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "客服主管",
        remark: "主管权限账户安全更新",
    },
    {
        recordId: "REC029",
        username: "finance_director",
        realName: "财务总监",
        userRole: "财务团队",
        department: "财务部",
        phone: "131****0029",
        email: "director@11comm.com",
        changeTime: "2024-11-17 17:40:20",
        ipAddress: "192.168.1.128",
        location: "福州市鼓楼区办事处",
        changeMethod: "忘记密码找回",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "财务总监",
        remark: "高级管理人员账户密码恢复",
    },
    {
        recordId: "REC030",
        username: "repair_chief",
        realName: "维修主管",
        userRole: "维修团队",
        department: "维修部",
        phone: "130****0030",
        email: "chief@11comm.com",
        changeTime: "2024-11-16 09:25:45",
        ipAddress: "192.168.1.129",
        location: "南昌市西湖区办事处",
        changeMethod: "首次登录修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "维修主管",
        remark: "新任主管首次登录系统",
    },
    {
        recordId: "REC031",
        username: "security_captain",
        realName: "保安队长",
        userRole: "保安团队",
        department: "保安部",
        phone: "139****0031",
        email: "captain@11comm.com",
        changeTime: "2024-11-16 10:50:30",
        ipAddress: "192.168.1.130",
        location: "贵阳市南明区办事处",
        changeMethod: "定期强制修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "保安队长",
        remark: "安全岗位强制密码策略",
    },
    {
        recordId: "REC032",
        username: "auditor001",
        realName: "审计员",
        userRole: "财务团队",
        department: "财务部",
        phone: "138****0032",
        email: "auditor@11comm.com",
        changeTime: "2024-11-16 13:15:55",
        ipAddress: "192.168.1.131",
        location: "昆明市五华区办事处",
        changeMethod: "用户自行修改",
        status: "失败",
        success: "否",
        failureReason: "密码与历史密码重复",
        operator: "审计员",
        remark: "系统检测到新密码与最近5次密码重复",
    },
    {
        recordId: "REC033",
        username: "compliance001",
        realName: "合规专员",
        userRole: "运营团队",
        department: "运营部",
        phone: "137****0033",
        email: "compliance@11comm.com",
        changeTime: "2024-11-16 14:40:10",
        ipAddress: "192.168.1.132",
        location: "兰州市城关区办事处",
        changeMethod: "管理员重置",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "系统管理员",
        remark: "合规审计要求重置密码",
    },
    {
        recordId: "REC034",
        username: "trainee001",
        realName: "实习生",
        userRole: "普通用户",
        department: "客服部",
        phone: "136****0034",
        email: "trainee@11comm.com",
        changeTime: "2024-11-16 15:05:25",
        ipAddress: "192.168.1.133",
        location: "西宁市城西区办事处",
        changeMethod: "首次登录修改",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "实习生",
        remark: "实习生入职首次登录",
    },
    {
        recordId: "REC035",
        username: "vendor001",
        realName: "供应商用户",
        userRole: "普通用户",
        department: "财务部",
        phone: "135****0035",
        email: "vendor@11comm.com",
        changeTime: "2024-11-16 16:30:40",
        ipAddress: "192.168.1.134",
        location: "银川市兴庆区办事处",
        changeMethod: "忘记密码找回",
        status: "成功",
        success: "是",
        failureReason: "",
        operator: "供应商用户",
        remark: "供应商系统访问密码恢复",
    },
];
