import type { InitializeCellListItem } from "@01s-11comm/type";

/** 初始化单元格模拟数据 */
export const mockInitializeCellData: InitializeCellListItem[] = [
    {
        cellId: "CELL001",
        cellName: "A栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD001",
        buildingName: "A栋住宅楼",
        floor: "1-18层",
        unitNumber: "1单元",
        houseCount: 72,
        status: "已初始化",
        description: "A栋1单元，标准住宅单元，共计72户",
        createTime: "2024-01-01 08:00:00",
        updateTime: "2024-01-15 14:30:00",
        creator: "系统管理员",
        updater: "张三",
    },
    {
        cellId: "CELL002",
        cellName: "A栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD001",
        buildingName: "A栋住宅楼",
        floor: "1-18层",
        unitNumber: "2单元",
        houseCount: 72,
        status: "已初始化",
        description: "A栋2单元，标准住宅单元，共计72户",
        createTime: "2024-01-01 08:00:00",
        updateTime: "2024-01-15 14:30:00",
        creator: "系统管理员",
        updater: "张三",
    },
    {
        cellId: "CELL003",
        cellName: "B栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD002",
        buildingName: "B栋住宅楼",
        floor: "1-24层",
        unitNumber: "1单元",
        houseCount: 96,
        status: "已初始化",
        description: "B栋1单元，高层住宅单元，共计96户",
        createTime: "2024-01-02 09:00:00",
        updateTime: "2024-01-16 10:15:00",
        creator: "系统管理员",
        updater: "李四",
    },
    {
        cellId: "CELL004",
        cellName: "B栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD002",
        buildingName: "B栋住宅楼",
        floor: "1-24层",
        unitNumber: "2单元",
        houseCount: 96,
        status: "已初始化",
        description: "B栋2单元，高层住宅单元，共计96户",
        createTime: "2024-01-02 09:00:00",
        updateTime: "2024-01-16 10:15:00",
        creator: "系统管理员",
        updater: "李四",
    },
    {
        cellId: "CELL005",
        cellName: "C栋商业单元",
        cellType: "商业单元",
        buildingId: "BUILD003",
        buildingName: "C栋商业楼",
        floor: "1-5层",
        unitNumber: "商业区",
        houseCount: 20,
        status: "已初始化",
        description: "C栋商业单元，商铺区域，共计20个商铺",
        createTime: "2024-01-03 10:00:00",
        updateTime: "2024-01-17 11:20:00",
        creator: "系统管理员",
        updater: "王五",
    },
    {
        cellId: "CELL006",
        cellName: "D栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD004",
        buildingName: "D栋住宅楼",
        floor: "1-15层",
        unitNumber: "1单元",
        houseCount: 60,
        status: "已初始化",
        description: "D栋1单元，中层住宅单元，共计60户",
        createTime: "2024-01-04 11:00:00",
        updateTime: "2024-01-18 12:30:00",
        creator: "系统管理员",
        updater: "赵六",
    },
    {
        cellId: "CELL007",
        cellName: "D栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD004",
        buildingName: "D栋住宅楼",
        floor: "1-15层",
        unitNumber: "2单元",
        houseCount: 60,
        status: "已初始化",
        description: "D栋2单元，中层住宅单元，共计60户",
        createTime: "2024-01-04 11:00:00",
        updateTime: "2024-01-18 12:30:00",
        creator: "系统管理员",
        updater: "赵六",
    },
    {
        cellId: "CELL008",
        cellName: "E栋地下车库",
        cellType: "车库单元",
        buildingId: "BUILD005",
        buildingName: "E栋综合楼",
        floor: "地下1-2层",
        unitNumber: "车库A区",
        houseCount: 150,
        status: "已初始化",
        description: "E栋地下车库A区，停车位150个",
        createTime: "2024-01-05 12:00:00",
        updateTime: "2024-01-19 13:40:00",
        creator: "系统管理员",
        updater: "孙七",
    },
    {
        cellId: "CELL009",
        cellName: "E栋地下车库B区",
        cellType: "车库单元",
        buildingId: "BUILD005",
        buildingName: "E栋综合楼",
        floor: "地下1-2层",
        unitNumber: "车库B区",
        houseCount: 120,
        status: "已初始化",
        description: "E栋地下车库B区，停车位120个",
        createTime: "2024-01-05 12:00:00",
        updateTime: "2024-01-19 13:40:00",
        creator: "系统管理员",
        updater: "孙七",
    },
    {
        cellId: "CELL010",
        cellName: "F栋办公单元",
        cellType: "办公单元",
        buildingId: "BUILD006",
        buildingName: "F栋办公楼",
        floor: "1-12层",
        unitNumber: "办公区",
        houseCount: 48,
        status: "已初始化",
        description: "F栋办公单元，办公区域，共计48个办公单元",
        createTime: "2024-01-06 13:00:00",
        updateTime: "2024-01-20 14:50:00",
        creator: "系统管理员",
        updater: "周八",
    },
    {
        cellId: "CELL011",
        cellName: "G栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD007",
        buildingName: "G栋住宅楼",
        floor: "1-20层",
        unitNumber: "1单元",
        houseCount: 80,
        status: "已初始化",
        description: "G栋1单元，高层住宅单元，共计80户",
        createTime: "2024-01-07 14:00:00",
        updateTime: "2024-01-21 15:25:00",
        creator: "系统管理员",
        updater: "吴九",
    },
    {
        cellId: "CELL012",
        cellName: "G栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD007",
        buildingName: "G栋住宅楼",
        floor: "1-20层",
        unitNumber: "2单元",
        houseCount: 80,
        status: "已初始化",
        description: "G栋2单元，高层住宅单元，共计80户",
        createTime: "2024-01-07 14:00:00",
        updateTime: "2024-01-21 15:25:00",
        creator: "系统管理员",
        updater: "吴九",
    },
    {
        cellId: "CELL013",
        cellName: "H栋会所单元",
        cellType: "会所单元",
        buildingId: "BUILD008",
        buildingName: "H栋会所",
        floor: "1-3层",
        unitNumber: "会所区",
        houseCount: 8,
        status: "已初始化",
        description: "H栋会所单元，休闲娱乐区域，共计8个功能单元",
        createTime: "2024-01-08 15:00:00",
        updateTime: "2024-01-22 16:10:00",
        creator: "系统管理员",
        updater: "郑十",
    },
    {
        cellId: "CELL014",
        cellName: "I栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD009",
        buildingName: "I栋住宅楼",
        floor: "1-16层",
        unitNumber: "1单元",
        houseCount: 64,
        status: "已初始化",
        description: "I栋1单元，标准住宅单元，共计64户",
        createTime: "2024-01-09 16:00:00",
        updateTime: "2024-01-23 17:35:00",
        creator: "系统管理员",
        updater: "陈一",
    },
    {
        cellId: "CELL015",
        cellName: "I栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD009",
        buildingName: "I栋住宅楼",
        floor: "1-16层",
        unitNumber: "2单元",
        houseCount: 64,
        status: "已初始化",
        description: "I栋2单元，标准住宅单元，共计64户",
        createTime: "2024-01-09 16:00:00",
        updateTime: "2024-01-23 17:35:00",
        creator: "系统管理员",
        updater: "陈一",
    },
    {
        cellId: "CELL016",
        cellName: "J栋商铺单元",
        cellType: "商业单元",
        buildingId: "BUILD010",
        buildingName: "J栋商业街",
        floor: "1-2层",
        unitNumber: "商铺街",
        houseCount: 32,
        status: "已初始化",
        description: "J栋商铺单元，沿街商铺区域，共计32个商铺",
        createTime: "2024-01-10 17:00:00",
        updateTime: "2024-01-24 18:20:00",
        creator: "系统管理员",
        updater: "林二",
    },
    {
        cellId: "CELL017",
        cellName: "K栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD011",
        buildingName: "K栋住宅楼",
        floor: "1-22层",
        unitNumber: "1单元",
        houseCount: 88,
        status: "已初始化",
        description: "K栋1单元，超高层住宅单元，共计88户",
        createTime: "2024-01-11 18:00:00",
        updateTime: "2024-01-25 19:15:00",
        creator: "系统管理员",
        updater: "黄三",
    },
    {
        cellId: "CELL018",
        cellName: "K栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD011",
        buildingName: "K栋住宅楼",
        floor: "1-22层",
        unitNumber: "2单元",
        houseCount: 88,
        status: "已初始化",
        description: "K栋2单元，超高层住宅单元，共计88户",
        createTime: "2024-01-11 18:00:00",
        updateTime: "2024-01-25 19:15:00",
        creator: "系统管理员",
        updater: "黄三",
    },
    {
        cellId: "CELL019",
        cellName: "L栋物业单元",
        cellType: "物业单元",
        buildingId: "BUILD012",
        buildingName: "L栋物业中心",
        floor: "1-4层",
        unitNumber: "物业区",
        houseCount: 16,
        status: "已初始化",
        description: "L栋物业单元，物业管理中心，共计16个功能单元",
        createTime: "2024-01-12 19:00:00",
        updateTime: "2024-01-26 20:30:00",
        creator: "系统管理员",
        updater: "张四",
    },
    {
        cellId: "CELL020",
        cellName: "M栋运动单元",
        cellType: "运动单元",
        buildingId: "BUILD013",
        buildingName: "M栋运动中心",
        floor: "1-3层",
        unitNumber: "运动区",
        houseCount: 12,
        status: "已初始化",
        description: "M栋运动单元，运动健身区域，共计12个功能单元",
        createTime: "2024-01-13 20:00:00",
        updateTime: "2024-01-27 21:40:00",
        creator: "系统管理员",
        updater: "李五",
    },
    {
        cellId: "CELL021",
        cellName: "N栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD014",
        buildingName: "N栋住宅楼",
        floor: "1-14层",
        unitNumber: "1单元",
        houseCount: 56,
        status: "已初始化",
        description: "N栋1单元，低层住宅单元，共计56户",
        createTime: "2024-01-14 21:00:00",
        updateTime: "2024-01-28 22:50:00",
        creator: "系统管理员",
        updater: "王六",
    },
    {
        cellId: "CELL022",
        cellName: "N栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD014",
        buildingName: "N栋住宅楼",
        floor: "1-14层",
        unitNumber: "2单元",
        houseCount: 56,
        status: "已初始化",
        description: "N栋2单元，低层住宅单元，共计56户",
        createTime: "2024-01-14 21:00:00",
        updateTime: "2024-01-28 22:50:00",
        creator: "系统管理员",
        updater: "王六",
    },
    {
        cellId: "CELL023",
        cellName: "O栋教育单元",
        cellType: "教育单元",
        buildingId: "BUILD015",
        buildingName: "O栋教育中心",
        floor: "1-5层",
        unitNumber: "教育区",
        houseCount: 24,
        status: "已初始化",
        description: "O栋教育单元，教育培训区域，共计24个功能单元",
        createTime: "2024-01-15 22:00:00",
        updateTime: "2024-01-29 23:25:00",
        creator: "系统管理员",
        updater: "赵七",
    },
    {
        cellId: "CELL024",
        cellName: "P栋医疗单元",
        cellType: "医疗单元",
        buildingId: "BUILD016",
        buildingName: "P栋医疗中心",
        floor: "1-6层",
        unitNumber: "医疗区",
        houseCount: 30,
        status: "已初始化",
        description: "P栋医疗单元，社区医疗服务，共计30个功能单元",
        createTime: "2024-01-16 23:00:00",
        updateTime: "2024-01-30 00:10:00",
        creator: "系统管理员",
        updater: "孙八",
    },
    {
        cellId: "CELL025",
        cellName: "Q栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD017",
        buildingName: "Q栋住宅楼",
        floor: "1-19层",
        unitNumber: "1单元",
        houseCount: 76,
        status: "已初始化",
        description: "Q栋1单元，中高层住宅单元，共计76户",
        createTime: "2024-01-17 08:30:00",
        updateTime: "2024-01-31 09:45:00",
        creator: "系统管理员",
        updater: "周九",
    },
    {
        cellId: "CELL026",
        cellName: "Q栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD017",
        buildingName: "Q栋住宅楼",
        floor: "1-19层",
        unitNumber: "2单元",
        houseCount: 76,
        status: "已初始化",
        description: "Q栋2单元，中高层住宅单元，共计76户",
        createTime: "2024-01-17 08:30:00",
        updateTime: "2024-01-31 09:45:00",
        creator: "系统管理员",
        updater: "周九",
    },
    {
        cellId: "CELL027",
        cellName: "R栋餐饮单元",
        cellType: "商业单元",
        buildingId: "BUILD018",
        buildingName: "R栋餐饮街",
        floor: "1-3层",
        unitNumber: "餐饮区",
        houseCount: 40,
        status: "已初始化",
        description: "R栋餐饮单元，美食餐饮区域，共计40个商铺",
        createTime: "2024-01-18 09:30:00",
        updateTime: "2024-02-01 10:55:00",
        creator: "系统管理员",
        updater: "吴十",
    },
    {
        cellId: "CELL028",
        cellName: "S栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD019",
        buildingName: "S栋住宅楼",
        floor: "1-13层",
        unitNumber: "1单元",
        houseCount: 52,
        status: "已初始化",
        description: "S栋1单元，小高层住宅单元，共计52户",
        createTime: "2024-01-19 10:30:00",
        updateTime: "2024-02-02 11:40:00",
        creator: "系统管理员",
        updater: "郑一",
    },
    {
        cellId: "CELL029",
        cellName: "S栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD019",
        buildingName: "S栋住宅楼",
        floor: "1-13层",
        unitNumber: "2单元",
        houseCount: 52,
        status: "已初始化",
        description: "S栋2单元，小高层住宅单元，共计52户",
        createTime: "2024-01-19 10:30:00",
        updateTime: "2024-02-02 11:40:00",
        creator: "系统管理员",
        updater: "郑一",
    },
    {
        cellId: "CELL030",
        cellName: "T栋仓储单元",
        cellType: "仓储单元",
        buildingId: "BUILD020",
        buildingName: "T栋仓储中心",
        floor: "1-2层",
        unitNumber: "仓储区",
        houseCount: 28,
        status: "已初始化",
        description: "T栋仓储单元，物流仓储区域，共计28个仓储单元",
        createTime: "2024-01-20 11:30:00",
        updateTime: "2024-02-03 12:50:00",
        creator: "系统管理员",
        updater: "陈二",
    },
    {
        cellId: "CELL031",
        cellName: "U栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD021",
        buildingName: "U栋住宅楼",
        floor: "1-17层",
        unitNumber: "1单元",
        houseCount: 68,
        status: "已初始化",
        description: "U栋1单元，中高层住宅单元，共计68户",
        createTime: "2024-01-21 12:30:00",
        updateTime: "2024-02-04 13:25:00",
        creator: "系统管理员",
        updater: "林三",
    },
    {
        cellId: "CELL032",
        cellName: "U栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD021",
        buildingName: "U栋住宅楼",
        floor: "1-17层",
        unitNumber: "2单元",
        houseCount: 68,
        status: "已初始化",
        description: "U栋2单元，中高层住宅单元，共计68户",
        createTime: "2024-01-21 12:30:00",
        updateTime: "2024-02-04 13:25:00",
        creator: "系统管理员",
        updater: "林三",
    },
    {
        cellId: "CELL033",
        cellName: "V栋文化单元",
        cellType: "文化单元",
        buildingId: "BUILD022",
        buildingName: "V栋文化中心",
        floor: "1-4层",
        unitNumber: "文化区",
        houseCount: 20,
        status: "已初始化",
        description: "V栋文化单元，文化艺术区域，共计20个功能单元",
        createTime: "2024-01-22 13:30:00",
        updateTime: "2024-02-05 14:40:00",
        creator: "系统管理员",
        updater: "黄四",
    },
    {
        cellId: "CELL034",
        cellName: "W栋1单元",
        cellType: "住宅单元",
        buildingId: "BUILD023",
        buildingName: "W栋住宅楼",
        floor: "1-21层",
        unitNumber: "1单元",
        houseCount: 84,
        status: "已初始化",
        description: "W栋1单元，高层住宅单元，共计84户",
        createTime: "2024-01-23 14:30:00",
        updateTime: "2024-02-06 15:15:00",
        creator: "系统管理员",
        updater: "张五",
    },
    {
        cellId: "CELL035",
        cellName: "W栋2单元",
        cellType: "住宅单元",
        buildingId: "BUILD023",
        buildingName: "W栋住宅楼",
        floor: "1-21层",
        unitNumber: "2单元",
        houseCount: 84,
        status: "已初始化",
        description: "W栋2单元，高层住宅单元，共计84户",
        createTime: "2024-01-23 14:30:00",
        updateTime: "2024-02-06 15:15:00",
        creator: "系统管理员",
        updater: "张五",
    },
];
