import type { StaffInfo } from "@01s-11comm/type";

export const mockStaffInfoData: StaffInfo[] = [
	{
		id: "1",
		employeeNumber: "EMP001",
		name: "张三",
		gender: "男",
		position: "物业经理",
		email: "zhangsan@example.com",
		phone: "13800138001",
		address: "北京市朝阳区",
		orgId: "2",
		orgName: "物业部",
	},
	{
		id: "2",
		employeeNumber: "EMP002",
		name: "李四",
		gender: "女",
		position: "客服主管",
		email: "lisi@example.com",
		phone: "13800138002",
		address: "北京市海淀区",
		orgId: "2-1",
		orgName: "客服中心",
	},
	{
		id: "3",
		employeeNumber: "EMP003",
		name: "王五",
		gender: "男",
		position: "维修工",
		email: "wangwu@example.com",
		phone: "13800138003",
		address: "北京市丰台区",
		orgId: "2-2",
		orgName: "工程部",
	},
	{
		id: "4",
		employeeNumber: "EMP004",
		name: "赵六",
		gender: "男",
		position: "保安队长",
		email: "zhaoliu@example.com",
		phone: "13800138004",
		address: "北京市昌平区",
		orgId: "2-3",
		orgName: "安保部",
	},
	{
		id: "5",
		employeeNumber: "EMP005",
		name: "钱七",
		gender: "女",
		position: "市场专员",
		email: "qianqi@example.com",
		phone: "13800138005",
		address: "北京市大兴区",
		orgId: "3-1",
		orgName: "市场部",
	},
	{
		id: "6",
		employeeNumber: "EMP006",
		name: "孙八",
		gender: "女",
		position: "会计",
		email: "sunba@example.com",
		phone: "13800138006",
		address: "北京市通州区",
		orgId: "3-2",
		orgName: "财务部",
	},
	{
		id: "7",
		employeeNumber: "EMP007",
		name: "周九",
		gender: "女",
		position: "行政助理",
		email: "zhoujiu@example.com",
		phone: "13800138007",
		address: "北京市房山区",
		orgId: "4",
		orgName: "行政部",
	},
];
