import type { StaffInfo } from "@01s-11comm/type";

export const mockStaffInfoData: StaffInfo[] = [
	{
		id: "1",
		employeeNumber: "EMP001",
		name: "张三",
		gender: "男",
		position: "物业经理",
		email: "zhangsan@example.com",
		phone: "13800138001",
		address: "北京市朝阳区",
		orgId: "2",
		orgName: "物业部",
	},
	{
		id: "2",
		employeeNumber: "EMP002",
		name: "李四",
		gender: "女",
		position: "客服主管",
		email: "lisi@example.com",
		phone: "13800138002",
		address: "北京市海淀区",
		orgId: "2-1",
		orgName: "客服中心",
	},
	{
		id: "3",
		employeeNumber: "EMP003",
		name: "王五",
		gender: "男",
		position: "维修工",
		email: "wangwu@example.com",
		phone: "13800138003",
		address: "北京市丰台区",
		orgId: "2-2",
		orgName: "工程部",
	},
	{
		id: "4",
		employeeNumber: "EMP004",
		name: "赵六",
		gender: "男",
		position: "保安队长",
		email: "zhaoliu@example.com",
		phone: "13800138004",
		address: "北京市昌平区",
		orgId: "2-3",
		orgName: "安保部",
	},
	{
		id: "5",
		employeeNumber: "EMP005",
		name: "钱七",
		gender: "女",
		position: "市场专员",
		email: "qianqi@example.com",
		phone: "13800138005",
		address: "北京市大兴区",
		orgId: "3-1",
		orgName: "市场部",
	},
	{
		id: "6",
		employeeNumber: "EMP006",
		name: "孙八",
		gender: "女",
		position: "会计",
		email: "sunba@example.com",
		phone: "13800138006",
		address: "北京市通州区",
		orgId: "3-2",
		orgName: "财务部",
	},
	{
		id: "7",
		employeeNumber: "EMP007",
		name: "周九",
		gender: "女",
		position: "行政助理",
		email: "zhoujiu@example.com",
		phone: "13800138007",
		address: "北京市房山区",
		orgId: "4",
		orgName: "行政部",
	},
	{
		id: "8",
		employeeNumber: "EMP008",
		name: "吴十",
		gender: "男",
		position: "客服专员",
		email: "wushi@example.com",
		phone: "13800138008",
		address: "北京市顺义区",
		orgId: "2-1",
		orgName: "客服中心",
	},
	{
		id: "9",
		employeeNumber: "EMP009",
		name: "陈十一",
		gender: "男",
		position: "维修主管",
		email: "chenshiyi@example.com",
		phone: "13800138009",
		address: "北京市东城区",
		orgId: "2-2",
		orgName: "工程部",
	},
	{
		id: "10",
		employeeNumber: "EMP010",
		name: "赵十二",
		gender: "男",
		position: "安保主管",
		email: "zhaoshier@example.com",
		phone: "13800138010",
		address: "北京市西城区",
		orgId: "2-3",
		orgName: "安保部",
	},
	{
		id: "11",
		employeeNumber: "EMP011",
		name: "钱十三",
		gender: "女",
		position: "市场主管",
		email: "qianshisan@example.com",
		phone: "13800138011",
		address: "北京市崇文区",
		orgId: "3-1",
		orgName: "市场部",
	},
	{
		id: "12",
		employeeNumber: "EMP012",
		name: "孙十四",
		gender: "女",
		position: "财务主管",
		email: "sunsishi@example.com",
		phone: "13800138012",
		address: "北京市宣武区",
		orgId: "3-2",
		orgName: "财务部",
	},
	{
		id: "13",
		employeeNumber: "EMP013",
		name: "周十五",
		gender: "女",
		position: "行政主管",
		email: "zhouwushi@example.com",
		phone: "13800138013",
		address: "北京市石景山区",
		orgId: "4",
		orgName: "行政部",
	},
	{
		id: "14",
		employeeNumber: "EMP014",
		name: "吴十六",
		gender: "男",
		position: "客服专员",
		email: "wushiliu@example.com",
		phone: "13800138014",
		address: "北京市门头沟区",
		orgId: "2-1",
		orgName: "客服中心",
	},
	{
		id: "15",
		employeeNumber: "EMP015",
		name: "陈十七",
		gender: "男",
		position: "维修工程师",
		email: "chenshiqi@example.com",
		phone: "13800138015",
		address: "北京市房山区",
		orgId: "2-2",
		orgName: "工程部",
	},
	{
		id: "16",
		employeeNumber: "EMP016",
		name: "赵十八",
		gender: "男",
		position: "安保专员",
		email: "zhaoshiba@example.com",
		phone: "13800138016",
		address: "北京市通州区",
		orgId: "2-3",
		orgName: "安保部",
	},
	{
		id: "17",
		employeeNumber: "EMP017",
		name: "钱十九",
		gender: "女",
		position: "市场专员",
		email: "qianshijiu@example.com",
		phone: "13800138017",
		address: "北京市大兴区",
		orgId: "3-1",
		orgName: "市场部",
	},
	{
		id: "18",
		employeeNumber: "EMP018",
		name: "孙二十",
		gender: "女",
		position: "出纳",
		email: "sunershi@example.com",
		phone: "13800138018",
		address: "北京市昌平区",
		orgId: "3-2",
		orgName: "财务部",
	},
	{
		id: "19",
		employeeNumber: "EMP019",
		name: "周廿一",
		gender: "女",
		position: "行政专员",
		email: "zhoueryi@example.com",
		phone: "13800138019",
		address: "北京市怀柔区",
		orgId: "4",
		orgName: "行政部",
	},
	{
		id: "20",
		employeeNumber: "EMP020",
		name: "吴廿二",
		gender: "男",
		position: "保洁主管",
		email: "wuerer@example.com",
		phone: "13800138020",
		address: "北京市平谷区",
		orgId: "4",
		orgName: "行政部",
	},
];
