import { describe, expect, test } from "vitest";

import { createEndpointRegistry, findEndpointDefinition } from "../../server/shared/runtime/endpoint-registry";
import { runtimeEndpointDefinitions } from "../../server/shared/runtime/runtime-endpoints";

const migratedOrGuardedRuntimePaths = [
	["GET", "/app/activities.listActivitiess"],
	["POST", "/app/activities.likeActivity"],
	["POST", "/app/activities.increaseView"],
	["POST", "/app/activities.updateStatus"],
	["POST", "/app/activities.updateLike"],
	["POST", "/app/activities.updateCollect"],
	["POST", "/app/activities.saveActivities"],
	["POST", "/app/activities.updateActivities"],
	["POST", "/app/activities.deleteActivities"],
	["GET", "/app/communitySpace.listCommunitySpaceConfirmOrder"],
	["POST", "/app/communitySpace.saveCommunitySpaceConfirmOrder"],
	["GET", "/app/auditUser.listAuditComplaints"],
	["GET", "/app/contact.listContacts"],
	["GET", "/app/floor.queryFloors"],
	["GET", "/app/notice.listNotices"],
	["GET", "/app/iot/listChargeMachineBmoImpl"],
	["GET", "/app/iot/listChargeMachineOrderBmoImpl"],
	["GET", "/app/iot/listChargeMachinePortBmoImpl"],
	["GET", "/app/machine/listMachineRecords"],
	["GET", "/app/feeDiscount/queryFeeDiscount"],
	["GET", "/app/applyRoomDiscountRecord/queryApplyRoomDiscountRecordDetail"],
	["GET", "/app/itemRelease.getItemRelease"],
	["POST", "/app/itemRelease.getItemRelease"],
	["GET", "/app/itemRelease.getItemReleaseRes"],
	["POST", "/app/itemRelease.getItemReleaseRes"],
	["GET", "/app/itemRelease.queryOaWorkflowUser"],
	["POST", "/app/itemRelease.queryOaWorkflowUser"],
	["GET", "/app/itemRelease.queryUndoItemReleaseV2"],
	["POST", "/app/itemRelease.queryUndoItemReleaseV2"],
	["GET", "/app/itemRelease.queryFinishItemReleaseV2"],
	["POST", "/app/itemRelease.queryFinishItemReleaseV2"],
	["POST", "/app/itemRelease.auditItemRelease"],
	["POST", "/app/profile.changeCommunity"],
	["POST", "/app/profile.changePassword"],
	["POST", "/app/visit.auditVisit"],
	["POST", "/app/purchase/updatePurchaseApply"],
	["GET", "/app/resourceStore.listResourceStores"],
	["POST", "/app/purchase/purchaseApply"],
	["POST", "/app/purchase/urgentPurchaseApply"],
	["GET", "/app/resourceStore.listStorehouses"],
	["GET", "/app/resourceStore.listAllocationStorehouseApplys"],
	["POST", "/app/resourceStore.saveAllocationStorehouse"],
	["GET", "/app/purchaseApply.listPurchaseApplys"],
	["GET", "/app/itemRelease.listItemRelease"],
	["GET", "/app/purchaseApply.listMyAuditOrders"],
	["GET", "/app/itemRelease.queryUndoItemRelease"],
	["GET", "/app/resourceStore.listAllocationStoreAuditOrders"],
	["GET", "/app/resourceStore.listAllocationStorehouses"],
	["GET", "/app/resourceStore.queryMyResourceStoreInfo"],
	["POST", "/app/purchaseApply.auditApplyOrder"],
	["POST", "/app/itemRelease.auditUndoItemRelease"],
	["POST", "/app/resourceStore.auditAllocationStoreOrder"],
	["GET", "/app/owner.queryOwnerCars"],
	["GET", "/app/parkingArea.listParkingAreas"],
	["GET", "/app/machine.listParkingAreaMachines"],
	["GET", "/app/carInout.listCarInParkingAreaCmd"],
	["GET", "/app/parkingCoupon.listParkingCouponCar"],
	["GET", "/app/tempCarFee.getTempCarFeeOrder"],
	["GET", "/app/carInoutDetail.listCarInoutDetail"],
	["GET", "/app/carInoutPayment.listCarInoutPayment"],
	["GET", "/app/machine.getBarrierCloudVideo"],
	["POST", "/app/machine/openDoor"],
	["POST", "/app/machine/closeDoor"],
	["POST", "/app/machine.customCarInOutCmd"],
	["GET", "/app/ownerRepair.listOwnerRepairs"],
	["GET", "/app/dict.queryPayTypes"],
	["GET", "/app/ownerRepair.getRepairStatistics"],
	["GET", "/app/ownerRepair.listRepairStaffRecords"],
	["GET", "/app/ownerRepair.listRepairStaffs"],
	["GET", "/app/repair.listRepairTypeUsers"],
	["GET", "/app/resourceStore.listResources"],
	["GET", "/app/staff.listStaffs"],
	["GET", "/app/staff/organizations"],
	["GET", "/app/staff/online"],
	["GET", "/app/staff/by-department"],
	["POST", "/app/staff/by-department"],
	["GET", "/app/query.staff.infos"],
	["POST", "/app/query.staff.infos"],
	["GET", "/app/staff/search"],
	["POST", "/app/staff/search"],
	["GET", "/app/staff/STAFF_001"],
	["POST", "/app/staff/update-online-status"],
	["POST", "/app/staff/add"],
	["GET", "/app/inspection.getTodayReport"],
	["GET", "/app/inspection.listInspectionItemTitles"],
	["GET", "/app/inspection.listInspectionTasks"],
	["GET", "/app/inspection.listInspectionTaskDetails"],
	["POST", "/app/inspection.submitInspection"],
	["POST", "/app/inspection.transferTask"],
	["GET", "/app/meter.queryFeeTypes"],
	["GET", "/app/meter.queryFeeTypesItems"],
	["GET", "/app/meter.listMeterType"],
	["GET", "/app/meter.listMeterWaters"],
	["GET", "/app/meter.queryPreMeterWater"],
	["GET", "/app/meter.listFloorShareReading"],
	["GET", "/app/meter.listFloorShareMeter"],
	["POST", "/app/meter.saveMeterWater"],
	["POST", "/app/meter.saveFloorShareReading"],
	["POST", "/app/meter.auditFloorShareReading"],
	["GET", "/app/workorder/todo/list"],
	["POST", "/app/workorder/create"],
	["POST", "/app/workorder/update"],
	["POST", "/app/workorder/start"],
	["POST", "/app/workorder/complete"],
	["POST", "/app/workorder/audit"],
	["POST", "/app/workorder/cancel"],
	["POST", "/app/workorder/copy/finish"],
	["GET", "/app/couponProperty.listCouponPropertyUserDetail"],
	["POST", "/app/couponProperty.listCouponPropertyUserDetail"],
	["GET", "/app/integral.listIntegralSetting"],
	["POST", "/app/integral.listIntegralSetting"],
	["GET", "/app/integral.listIntegralUserDetail"],
	["POST", "/app/integral.listIntegralUserDetail"],
	["POST", "/app/couponProperty.writeOffCouponPropertyUser"],
	["POST", "/app/integral.useIntegral"],
	["GET", "/app/reserveOrder.listReserveGoodsConfirmOrder"],
	["POST", "/app/reserveOrder.listReserveGoodsConfirmOrder"],
	["POST", "/app/reserveOrder.saveReserveGoodsConfirmOrder"],
	["GET", "/app/maintenance.listMaintenanceTasks"],
	["POST", "/app/maintenance.listMaintenanceTasks"],
	["GET", "/app/maintenance.queryMaintenanceTask"],
	["POST", "/app/maintenance.queryMaintenanceTask"],
	["GET", "/app/maintenance.listMaintenanceTaskDetails"],
	["POST", "/app/maintenance.listMaintenanceTaskDetails"],
	["POST", "/app/maintenance.startMaintenanceTask"],
	["POST", "/app/maintenance.completeMaintenanceTask"],
	["POST", "/app/maintenance.submitMaintenanceSingle"],
	["POST", "/app/maintenance.transferMaintenanceTask"],
	["GET", "/callComponent/core/list"],
] as const;

const remainingAppLegacyGapPaths = [
	["GET", "/app/oa/workflow/query"],
	["GET", "/app/oa/workflow/form/query"],
	["GET", "/app/oa/workflow/form/data/query"],
	["POST", "/app/oa/workflow/form/save"],
	["POST", "/app/oa/workflow/form/update"],
	["GET", "/app/oa/workflow/task/undo/query"],
	["GET", "/app/oa/workflow/task/his/query"],
	["GET", "/app/oa/workflow/user/query"],
	["GET", "/app/oa/workflow/image/run"],
	["GET", "/app/oa/workflow/task/next"],
	["POST", "/app/oa/workflow/audit"],
	["GET", "/app/oa/workflow/undo/next-deal-user"],
	["POST", "/app/oa/workflow/undo/audit"],
	["GET", "/app/applyRoomDiscount/queryApplyRoomDiscount"],
	["POST", "/app/applyRoomDiscount/updateApplyRoomDiscount"],
	["POST", "/app/applyRoomDiscount/updateReviewApplyRoomDiscount"],
	["GET", "/app/applyRoomDiscountRecord/queryApplyRoomDiscountRecord"],
	["POST", "/app/applyRoomDiscountRecord/addApplyRoomDiscountRecord"],
	["POST", "/app/applyRoomDiscountRecord/cutApplyRoomDiscountRecord"],
	["GET", "/app/roomRenovation/queryRoomRenovation"],
	["POST", "/app/roomRenovation/updateRoomToExamine"],
	["POST", "/app/roomRenovation/saveRoomRenovationDetail"],
	["POST", "/app/roomRenovation/updateRoomRenovationState"],
	["GET", "/app/roomRenovation/queryRoomRenovationRecord"],
	["GET", "/app/roomRenovation/queryRoomRenovationRecordDetail"],
	["POST", "/app/roomRenovation/updateRoomDecorationRecord"],
	["POST", "/app/roomRenovation/deleteRoomRenovationRecord"],
	["GET", "/app/resourceStoreType.listResourceStoreTypes"],
	["POST", "/app/collection/resourceOut"],
	["POST", "/app/purchase/resourceEnter"],
	["POST", "/app/purchaseApply.deletePurchaseApply"],
	["POST", "/app/resourceStore.deleteAllocationStorehouse"],
	["POST", "/app/resourceStore.allocationStoreEnter"],
	["POST", "/app/resourceStore.saveAllocationUserStorehouse"],
	["POST", "/app/resourceStore.saveResourceReturn"],
	["POST", "/app/resourceStore.saveResourceScrap"],
] as const;

const retiredAppDiagnosticPaths = [
	["GET", "/test"],
	["GET", "/test/params"],
	["POST", "/test/params"],
	["GET", "/test/error"],
] as const;

describe("app legacy runtime gap registry", () => {
	test.each(migratedOrGuardedRuntimePaths)(
		"keeps already migrated or guarded app runtime path registered: %s %s",
		(method, path) => {
			const registry = createEndpointRegistry(runtimeEndpointDefinitions);

			expect(findEndpointDefinition(registry, method, path)).toBeTruthy();
		},
	);

	test.each(remainingAppLegacyGapPaths)("keeps task437-task439 gap path unregistered: %s %s", (method, path) => {
		const registry = createEndpointRegistry(runtimeEndpointDefinitions);

		expect(findEndpointDefinition(registry, method, path)).toBeUndefined();
	});

	test.each(retiredAppDiagnosticPaths)(
		"does not expose retired app diagnostic test endpoint: %s %s",
		(method, path) => {
			const registry = createEndpointRegistry(runtimeEndpointDefinitions);

			expect(findEndpointDefinition(registry, method, path)).toBeUndefined();
		},
	);
});
