ALTER TABLE "hp_houses" ADD COLUMN "rent" numeric(12, 2);--> statement-breakpoint
ALTER TABLE "hp_houses" ADD COLUMN "valid_until" date;--> statement-breakpoint
ALTER TABLE "hp_invoices" ADD COLUMN "code" varchar(50);--> statement-breakpoint
ALTER TABLE "hp_invoices" ADD COLUMN "owner_name" varchar(50);--> statement-breakpoint
ALTER TABLE "hp_invoices" ADD COLUMN "applicant" varchar(50);--> statement-breakpoint
ALTER TABLE "hp_invoices" ADD COLUMN "invoice_title" varchar(200);--> statement-breakpoint
ALTER TABLE "hp_invoices" ADD COLUMN "taxpayer_id" varchar(50);--> statement-breakpoint
ALTER TABLE "hp_invoices" ADD COLUMN "audit_status" varchar(20) DEFAULT 'pending';--> statement-breakpoint
ALTER TABLE "hp_invoices" ADD COLUMN "application_time" timestamp;--> statement-breakpoint
ALTER TABLE "hp_owner_members" ADD COLUMN "creator" varchar(50);--> statement-breakpoint
ALTER TABLE "hp_owners" ADD COLUMN "emergency_contact_phone" varchar(20);--> statement-breakpoint
ALTER TABLE "hp_owners" ADD COLUMN "access_key" varchar(100);--> statement-breakpoint
ALTER TABLE "hp_owners_committees" ADD COLUMN "full_name" varchar(50);--> statement-breakpoint
ALTER TABLE "hp_owners_committees" ADD COLUMN "gender" "gender";--> statement-breakpoint
ALTER TABLE "hp_owners_committees" ADD COLUMN "id_number" varchar(18);--> statement-breakpoint
ALTER TABLE "hp_owners_committees" ADD COLUMN "address" text;--> statement-breakpoint
ALTER TABLE "hp_owners_committees" ADD COLUMN "post" varchar(50);--> statement-breakpoint
ALTER TABLE "hp_owners_committees" ADD COLUMN "status" varchar(20);--> statement-breakpoint
ALTER TABLE "hp_reserve_venue_orders" ADD COLUMN "reservation_time" timestamp;--> statement-breakpoint
ALTER TABLE "hp_reserve_venue_orders" ADD COLUMN "start_time" timestamp;--> statement-breakpoint
ALTER TABLE "hp_reserve_venue_orders" ADD COLUMN "end_time" timestamp;--> statement-breakpoint
ALTER TABLE "hp_reserve_venue_orders" ADD COLUMN "number_of_users" integer;--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "contract_name" varchar(200);--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "contract_number" varchar(100);--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "contract_type" varchar(50);--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "party_a" varchar(200);--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "party_b" varchar(200);--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "changer" varchar(50);--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "apply_time" timestamp;--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "ct_changes" ADD COLUMN "status" varchar(50);--> statement-breakpoint
ALTER TABLE "ex_expense_items" ADD COLUMN "expense_identifier" varchar(50);--> statement-breakpoint
ALTER TABLE "ex_expense_items" ADD COLUMN "prepayment_period" integer;--> statement-breakpoint
ALTER TABLE "ex_expense_items" ADD COLUMN "unit" varchar(20);--> statement-breakpoint
ALTER TABLE "ex_meter_reading_types" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "ex_vehicle_charges" ADD COLUMN "owner_name" varchar(50);--> statement-breakpoint
ALTER TABLE "ex_vehicle_charges" ADD COLUMN "parking_space_status" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_data_permissions" ADD COLUMN "name" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_data_permissions" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "sm_data_permissions" ADD COLUMN "level" integer;--> statement-breakpoint
ALTER TABLE "sm_data_permissions" ADD COLUMN "enabled" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "sm_data_permissions" ADD COLUMN "resource_type" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_data_permissions" ADD COLUMN "custom_range" jsonb;--> statement-breakpoint
ALTER TABLE "sm_initialize_cells" ADD COLUMN "community_id" uuid;--> statement-breakpoint
ALTER TABLE "sm_initialize_cells" ADD COLUMN "community_name" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_initialize_cells" ADD COLUMN "nearby_landmark" varchar(200);--> statement-breakpoint
ALTER TABLE "sm_initialize_cells" ADD COLUMN "city_code" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_initialize_cells" ADD COLUMN "status" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_initialize_cells" ADD COLUMN "cell_name" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_initialize_cells" ADD COLUMN "code" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "name" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "type" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "cycle" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "effective_time" timestamp;--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "staff" text;--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "status" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "org_id" uuid;--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "rule_name" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "cycle_type" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_scheduling_settings" ADD COLUMN "shift_ids" jsonb;--> statement-breakpoint
ALTER TABLE "sm_shifts" ADD COLUMN "type" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_shifts" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "sm_shifts" ADD COLUMN "enabled" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "title" varchar(200);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "subtitle" varchar(200);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "short_name" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "company_name" varchar(200);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "logo_url" text;--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "static_url" text;--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "default_community_code" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "owner_title" varchar(200);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "property_mobile_title" varchar(200);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "qq_map_key" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_system_configs" ADD COLUMN "mall_url" text;--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "name" varchar(100);--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "type" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "start_time" time;--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "end_time" time;--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "weekday" integer;--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "manager_name" varchar(50);--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "phone" varchar(20);--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "enabled" boolean DEFAULT true;--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "work_date" date;--> statement-breakpoint
ALTER TABLE "sm_working_schedules" ADD COLUMN "status" varchar(50);