import type { ReportInfo } from "@01s-11comm/type";

/**
 * 报表信息模拟数据
 */
export const mockReportInfoData: ReportInfo[] = [
	{
		id: "RPT001",
		reportName: "月度物业费收费明细",
		reportCode: "PROPERTY_FEE_MONTHLY",
		groupId: "RPG001",
		groupName: "物业收费报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM property_fee WHERE fee_date BETWEEN ? AND ?",
		description: "统计指定月份的物业费收费明细",
		fieldConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名"},{"prop":"roomNumber","label":"房号"},{"prop":"feeAmount","label":"收费金额"},{"prop":"payTime","label":"缴费时间"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "report_admin",
	},
	{
		id: "RPT002",
		reportName: "年度收费统计汇总",
		reportCode: "PROPERTY_FEE_YEARLY_SUMMARY",
		groupId: "RPG001",
		groupName: "物业收费报表",
		reportType: "汇总报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT community_name, SUM(fee_amount) FROM property_fee WHERE YEAR(fee_date)=? GROUP BY community_name",
		description: "按小区统计年度收费汇总",
		fieldConfig: '{"columns":[{"prop":"communityName","label":"小区名称"},{"prop":"totalAmount","label":"收费总额"},{"prop":"houseCount","label":"收费户数"}]}',
		parameterConfig: '{"params":[{"name":"year","type":"number","label":"年份"}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 2,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "report_admin",
	},
	{
		id: "RPT003",
		reportName: "业主信息一览表",
		reportCode: "OWNER_INFO_LIST",
		groupId: "RPG002",
		groupName: "业主信息报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM owner_info WHERE community_id IN (?)",
		description: "业主基本信息明细表",
		fieldConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名"},{"prop":"phone","label":"联系电话"},{"prop":"roomNumber","label":"房号"},{"prop":"idCard","label":"身份证号"}]}',
		parameterConfig: '{"params":[{"name":"communityIds","type":"select","label":"小区","multiple":true}]}',
		isCache: false,
		cacheDuration: 0,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "report_admin",
	},
	{
		id: "RPT004",
		reportName: "车辆信息统计",
		reportCode: "VEHICLE_INFO_STAT",
		groupId: "RPG002",
		groupName: "业主信息报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT vehicle_type, COUNT(*) as count FROM vehicle_info GROUP BY vehicle_type",
		description: "统计各类车辆数量",
		fieldConfig: '{"columns":[{"prop":"vehicleType","label":"车辆类型"},{"prop":"count","label":"数量"}]}',
		parameterConfig: '{"params":[{"name":"communityId","type":"select","label":"小区"}]}',
		isCache: true,
		cacheDuration: 1800,
		isEnabled: true,
		sortOrder: 2,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "report_admin",
	},
	{
		id: "RPT005",
		reportName: "维修工单处理统计",
		reportCode: "MAINTENANCE_WORKORDER_STAT",
		groupId: "RPG003",
		groupName: "维修服务报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT status, COUNT(*) as count FROM maintenance_workorder WHERE create_time BETWEEN ? AND ? GROUP BY status",
		description: "统计维修工单处理情况",
		fieldConfig: '{"columns":[{"prop":"status","label":"状态"},{"prop":"count","label":"数量"},{"prop":"percentage","label":"占比"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-12 08:00:00",
		updateTime: "2024-01-22 16:45:00",
		operator: "report_admin",
	},
	{
		id: "RPT006",
		reportName: "巡检计划执行情况",
		reportCode: "PATROL_PLAN_EXECUTION",
		groupId: "RPG004",
		groupName: "巡检管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM patrol_plan WHERE plan_date BETWEEN ? AND ?",
		description: "巡检计划及执行情况明细",
		fieldConfig: '{"columns":[{"prop":"planName","label":"计划名称"},{"prop":"planDate","label":"计划日期"},{"prop":"executor","label":"执行人"},{"prop":"status","label":"状态"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: false,
		cacheDuration: 0,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-13 08:00:00",
		updateTime: "2024-01-23 11:20:00",
		operator: "report_admin",
	},
	{
		id: "RPT007",
		reportName: "门禁刷卡记录",
		reportCode: "ACCESS_CARD_RECORD",
		groupId: "RPG005",
		groupName: "安全管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM access_record WHERE access_time BETWEEN ? AND ?",
		description: "门禁刷卡出入记录",
		fieldConfig: '{"columns":[{"prop":"cardNumber","label":"卡号"},{"prop":"personName","label":"姓名"},{"prop":"accessTime","label":"刷卡时间"},{"prop":"gateName","label":"门禁点"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: false,
		cacheDuration: 0,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-14 08:00:00",
		updateTime: "2024-01-24 15:30:00",
		operator: "report_admin",
	},
	{
		id: "RPT008",
		reportName: "设备维护记录",
		reportCode: "EQUIPMENT_MAINTENANCE_RECORD",
		groupId: "RPG006",
		groupName: "设备管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM equipment_maintenance WHERE maintenance_date BETWEEN ? AND ?",
		description: "设备维护保养记录明细",
		fieldConfig: '{"columns":[{"prop":"equipmentName","label":"设备名称"},{"prop":"maintenanceType","label":"维护类型"},{"prop":"maintenanceDate","label":"维护日期"},{"prop":"technician","label":"技术人员"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-15 08:00:00",
		updateTime: "2024-01-25 09:45:00",
		operator: "report_admin",
	},
	{
		id: "RPT009",
		reportName: "月度能耗统计",
		reportCode: "MONTHLY_ENERGY_STAT",
		groupId: "RPG007",
		groupName: "能耗统计报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT energy_type, SUM(consumption) as total FROM energy_consumption WHERE month=? GROUP BY energy_type",
		description: "月度水电能耗统计",
		fieldConfig: '{"columns":[{"prop":"energyType","label":"能耗类型"},{"prop":"total","label":"总消耗"},{"prop":"unit","label":"单位"}]}',
		parameterConfig: '{"params":[{"name":"month","type":"month","label":"月份"}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-16 08:00:00",
		updateTime: "2024-01-26 13:20:00",
		operator: "report_admin",
	},
	{
		id: "RPT010",
		reportName: "客服工单处理统计",
		reportCode: "CUSTOMER_SERVICE_WORKORDER",
		groupId: "RPG009",
		groupName: "客服服务报表",
		reportType: "图表报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT category, status, COUNT(*) as count FROM customer_service GROUP BY category, status",
		description: "客服工单分类统计",
		fieldConfig: '{"columns":[{"prop":"category","label":"工单类别"},{"prop":"status","label":"处理状态"},{"prop":"count","label":"数量"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-18 08:00:00",
		updateTime: "2024-01-28 14:10:00",
		operator: "report_admin",
	},
	{
		id: "RPT011",
		reportName: "访客进出统计",
		reportCode: "VISITOR_TRAFFIC_STAT",
		groupId: "RPG011",
		groupName: "访客管理报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT visit_date, COUNT(*) as count FROM visitor_record GROUP BY visit_date",
		description: "每日访客进出统计",
		fieldConfig: '{"columns":[{"prop":"visitDate","label":"日期"},{"prop":"count","label":"访客数量"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-20 08:00:00",
		updateTime: "2024-01-30 10:15:00",
		operator: "report_admin",
	},
	{
		id: "RPT012",
		reportName: "车位使用率统计",
		reportCode: "PARKING_USAGE_STAT",
		groupId: "RPG012",
		groupName: "停车管理报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT parking_lot, usage_rate FROM parking_lot_stats",
		description: "各车位使用率统计",
		fieldConfig: '{"columns":[{"prop":"parkingLot","label":"停车场"},{"prop":"usageRate","label":"使用率"}]}',
		parameterConfig: '{"params":[{"name":"month","type":"month","label":"月份"}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-21 08:00:00",
		updateTime: "2024-01-31 14:20:00",
		operator: "report_admin",
	},
	{
		id: "RPT013",
		reportName: "门禁刷卡记录明细",
		reportCode: "ACCESS_CARD_DETAIL",
		groupId: "RPG013",
		groupName: "门禁管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM access_card_record WHERE access_time BETWEEN ? AND ?",
		description: "门禁刷卡记录明细表",
		fieldConfig: '{"columns":[{"prop":"cardNumber","label":"卡号"},{"prop":"personName","label":"姓名"},{"prop":"accessTime","label":"刷卡时间"},{"prop":"gateName","label":"门禁点"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: false,
		cacheDuration: 0,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-22 08:00:00",
		updateTime: "2024-02-01 11:10:00",
		operator: "report_admin",
	},
	{
		id: "RPT014",
		reportName: "月度能耗分析",
		reportCode: "MONTHLY_ENERGY_ANALYSIS",
		groupId: "RPG014",
		groupName: "能耗管理报表",
		reportType: "图表报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT energy_type, SUM(consumption) as total FROM energy_consumption WHERE month=? GROUP BY energy_type",
		description: "月度水电能耗分析",
		fieldConfig: '{"columns":[{"prop":"energyType","label":"能耗类型"},{"prop":"total","label":"总消耗"},{"prop":"unit","label":"单位"}]}',
		parameterConfig: '{"params":[{"name":"month","type":"month","label":"月份"}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-23 08:00:00",
		updateTime: "2024-02-02 16:40:00",
		operator: "report_admin",
	},
	{
		id: "RPT015",
		reportName: "消防检查记录",
		reportCode: "FIRE_INSPECTION_RECORD",
		groupId: "RPG015",
		groupName: "消防管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM fire_inspection WHERE inspection_date BETWEEN ? AND ?",
		description: "消防检查记录明细",
		fieldConfig: '{"columns":[{"prop":"inspectionDate","label":"检查日期"},{"prop":"inspector","label":"检查人"},{"prop":"location","label":"检查位置"},{"prop":"result","label":"检查结果"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-24 08:00:00",
		updateTime: "2024-02-03 09:25:00",
		operator: "report_admin",
	},
	{
		id: "RPT016",
		reportName: "绿化养护统计",
		reportCode: "GREENING_MAINTENANCE_STAT",
		groupId: "RPG016",
		groupName: "绿化管理报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT task_type, COUNT(*) as count FROM greening_task GROUP BY task_type",
		description: "绿化养护任务统计",
		fieldConfig: '{"columns":[{"prop":"taskType","label":"任务类型"},{"prop":"count","label":"完成数量"}]}',
		parameterConfig: '{"params":[{"name":"year","type":"number","label":"年份"}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-25 08:00:00",
		updateTime: "2024-02-04 14:50:00",
		operator: "report_admin",
	},
	{
		id: "RPT017",
		reportName: "保洁任务完成率",
		reportCode: "CLEANING_COMPLETION_RATE",
		groupId: "RPG017",
		groupName: "保洁管理报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT area, SUM(completed) / SUM(total) * 100 as rate FROM cleaning_task GROUP BY area",
		description: "各区域保洁任务完成率",
		fieldConfig: '{"columns":[{"prop":"area","label":"区域"},{"prop":"rate","label":"完成率"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-26 08:00:00",
		updateTime: "2024-02-05 11:30:00",
		operator: "report_admin",
	},
	{
		id: "RPT018",
		reportName: "报修处理时效",
		reportCode: "REPAIR_PROCESSING_TIME",
		groupId: "RPG018",
		groupName: "工程维修报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT category, AVG(TIMESTAMPDIFF(HOUR, create_time, complete_time)) as avg_hours FROM repair_order GROUP BY category",
		description: "各类报修处理平均时效",
		fieldConfig: '{"columns":[{"prop":"category","label":"报修类别"},{"prop":"avgHours","label":"平均时长(小时)"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-27 08:00:00",
		updateTime: "2024-02-06 15:20:00",
		operator: "report_admin",
	},
	{
		id: "RPT019",
		reportName: "欠费催缴统计",
		reportCode: "OVERDUE_FEE_STAT",
		groupId: "RPG019",
		groupName: "财务收费报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT fee_type, SUM(overdue_amount) as total FROM fee_overdue GROUP BY fee_type",
		description: "各类欠费金额统计",
		fieldConfig: '{"columns":[{"prop":"feeType","label":"费用类型"},{"prop":"total","label":"欠费金额"}]}',
		parameterConfig: '{"params":[{"name":"communityId","type":"select","label":"小区"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-28 08:00:00",
		updateTime: "2024-02-07 10:40:00",
		operator: "report_admin",
	},
	{
		id: "RPT020",
		reportName: "业主满意度调查",
		reportCode: "OWNER_SATISFACTION_SURVEY",
		groupId: "RPG020",
		groupName: "综合服务报表",
		reportType: "图表报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT service_type, AVG(score) as avg_score FROM satisfaction_survey GROUP BY service_type",
		description: "各服务类型满意度评分",
		fieldConfig: '{"columns":[{"prop":"serviceType","label":"服务类型"},{"prop":"avgScore","label":"平均评分"}]}',
		parameterConfig: '{"params":[{"name":"quarter","type":"select","label":"季度","options":[{"label":"第一季度","value":"Q1"},{"label":"第二季度","value":"Q2"},{"label":"第三季度","value":"Q3"},{"label":"第四季度","value":"Q4"}]}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-29 08:00:00",
		updateTime: "2024-02-08 16:10:00",
		operator: "report_admin",
	},
];
