import type { ReportInfo } from "@01s-11comm/type";

/**
 * 报表信息模拟数据
 */
export const mockReportInfoData: ReportInfo[] = [
	{
		id: "RPT001",
		reportName: "月度物业费收费明细",
		reportCode: "PROPERTY_FEE_MONTHLY",
		groupId: "RPG001",
		groupName: "物业收费报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM property_fee WHERE fee_date BETWEEN ? AND ?",
		description: "统计指定月份的物业费收费明细",
		fieldConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名"},{"prop":"roomNumber","label":"房号"},{"prop":"feeAmount","label":"收费金额"},{"prop":"payTime","label":"缴费时间"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "report_admin",
	},
	{
		id: "RPT002",
		reportName: "年度收费统计汇总",
		reportCode: "PROPERTY_FEE_YEARLY_SUMMARY",
		groupId: "RPG001",
		groupName: "物业收费报表",
		reportType: "汇总报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT community_name, SUM(fee_amount) FROM property_fee WHERE YEAR(fee_date)=? GROUP BY community_name",
		description: "按小区统计年度收费汇总",
		fieldConfig: '{"columns":[{"prop":"communityName","label":"小区名称"},{"prop":"totalAmount","label":"收费总额"},{"prop":"houseCount","label":"收费户数"}]}',
		parameterConfig: '{"params":[{"name":"year","type":"number","label":"年份"}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 2,
		createTime: "2024-01-10 08:00:00",
		updateTime: "2024-01-20 14:30:00",
		operator: "report_admin",
	},
	{
		id: "RPT003",
		reportName: "业主信息一览表",
		reportCode: "OWNER_INFO_LIST",
		groupId: "RPG002",
		groupName: "业主信息报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM owner_info WHERE community_id IN (?)",
		description: "业主基本信息明细表",
		fieldConfig: '{"columns":[{"prop":"ownerName","label":"业主姓名"},{"prop":"phone","label":"联系电话"},{"prop":"roomNumber","label":"房号"},{"prop":"idCard","label":"身份证号"}]}',
		parameterConfig: '{"params":[{"name":"communityIds","type":"select","label":"小区","multiple":true}]}',
		isCache: false,
		cacheDuration: 0,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "report_admin",
	},
	{
		id: "RPT004",
		reportName: "车辆信息统计",
		reportCode: "VEHICLE_INFO_STAT",
		groupId: "RPG002",
		groupName: "业主信息报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT vehicle_type, COUNT(*) as count FROM vehicle_info GROUP BY vehicle_type",
		description: "统计各类车辆数量",
		fieldConfig: '{"columns":[{"prop":"vehicleType","label":"车辆类型"},{"prop":"count","label":"数量"}]}',
		parameterConfig: '{"params":[{"name":"communityId","type":"select","label":"小区"}]}',
		isCache: true,
		cacheDuration: 1800,
		isEnabled: true,
		sortOrder: 2,
		createTime: "2024-01-11 08:00:00",
		updateTime: "2024-01-21 10:15:00",
		operator: "report_admin",
	},
	{
		id: "RPT005",
		reportName: "维修工单处理统计",
		reportCode: "MAINTENANCE_WORKORDER_STAT",
		groupId: "RPG003",
		groupName: "维修服务报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT status, COUNT(*) as count FROM maintenance_workorder WHERE create_time BETWEEN ? AND ? GROUP BY status",
		description: "统计维修工单处理情况",
		fieldConfig: '{"columns":[{"prop":"status","label":"状态"},{"prop":"数量"},{"prop":"percentage","label":"占比"}":"count","label]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-12 08:00:00",
		updateTime: "2024-01-22 16:45:00",
		operator: "report_admin",
	},
	{
		id: "RPT006",
		reportName: "巡检计划执行情况",
		reportCode: "PATROL_PLAN_EXECUTION",
		groupId: "RPG004",
		groupName: "巡检管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM patrol_plan WHERE plan_date BETWEEN ? AND ?",
		description: "巡检计划及执行情况明细",
		fieldConfig: '{"columns":[{"prop":"planName","label":"计划名称"},{"prop":"planDate","label":"计划日期"},{"prop":"executor","label":"执行人"},{"prop":"status","label":"状态"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: false,
		cacheDuration: 0,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-13 08:00:00",
		updateTime: "2024-01-23 11:20:00",
		operator: "report_admin",
	},
	{
		id: "RPT007",
		reportName: "门禁刷卡记录",
		reportCode: "ACCESS_CARD_RECORD",
		groupId: "RPG005",
		groupName: "安全管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM access_record WHERE access_time BETWEEN ? AND ?",
		description: "门禁刷卡出入记录",
		fieldConfig: '{"columns":[{"prop":"cardNumber","label":"卡号"},{"prop":"personName","label":"姓名"},{"prop":"accessTime","label":"刷卡时间"},{"prop":"gateName","label":"门禁点"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: false,
		cacheDuration: 0,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-14 08:00:00",
		updateTime: "2024-01-24 15:30:00",
		operator: "report_admin",
	},
	{
		id: "RPT008",
		reportName: "设备维护记录",
		reportCode: "EQUIPMENT_MAINTENANCE_RECORD",
		groupId: "RPG006",
		groupName: "设备管理报表",
		reportType: "明细报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT * FROM equipment_maintenance WHERE maintenance_date BETWEEN ? AND ?",
		description: "设备维护保养记录明细",
		fieldConfig: '{"columns":[{"prop":"equipmentName","label":"设备名称"},{"prop":"maintenanceType","label":"维护类型"},{"prop":"maintenanceDate","label":"维护日期"},{"prop":"technician","label":"技术人员"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-15 08:00:00",
		updateTime: "2024-01-25 09:45:00",
		operator: "report_admin",
	},
	{
		id: "RPT009",
		reportName: "月度能耗统计",
		reportCode: "MONTHLY_ENERGY_STAT",
		groupId: "RPG007",
		groupName: "能耗统计报表",
		reportType: "统计报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT energy_type, SUM(consumption) as total FROM energy_consumption WHERE month=? GROUP BY energy_type",
		description: "月度水电能耗统计",
		fieldConfig: '{"columns":[{"prop":"energyType","label":"能耗类型"},{"prop":"total","label":"总消耗"},{"prop":"unit","label":"单位"}]}',
		parameterConfig: '{"params":[{"name":"month","type":"month","label":"月份"}]}',
		isCache: true,
		cacheDuration: 7200,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-16 08:00:00",
		updateTime: "2024-01-26 13:20:00",
		operator: "report_admin",
	},
	{
		id: "RPT010",
		reportName: "客服工单处理统计",
		reportCode: "CUSTOMER_SERVICE_WORKORDER",
		groupId: "RPG009",
		groupName: "客服服务报表",
		reportType: "图表报表",
		dataSource: "主数据库",
		sqlQuery: "SELECT category, status, COUNT(*) as count FROM customer_service GROUP BY category, status",
		description: "客服工单分类统计",
		fieldConfig: '{"columns":[{"prop":"category","label":"工单类别"},{"prop":"status","label":"处理状态"},{"prop":"count","label":"数量"}]}',
		parameterConfig: '{"params":[{"name":"startDate","type":"date","label":"开始日期"},{"name":"endDate","type":"date","label":"结束日期"}]}',
		isCache: true,
		cacheDuration: 3600,
		isEnabled: true,
		sortOrder: 1,
		createTime: "2024-01-18 08:00:00",
		updateTime: "2024-01-28 14:10:00",
		operator: "report_admin",
	},
];
