import type { MenuItemListItem } from "@01s-11comm/type";

/**
 * @description 菜单项模拟数据
 * Menu item mock data
 */
export const mockMenuItemData: MenuItemListItem[] = [
	{
		menuId: "MENU001",
		menuName: "系统管理",
		parentMenu: "根菜单",
		menuType: "目录",
		routePath: "/system",
		componentPath: "",
		permissionKey: "system:manage",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-15 09:00:00",
		icon: "mdi:cog",
	},
	{
		menuId: "MENU002",
		menuName: "用户管理",
		parentMenu: "系统管理",
		menuType: "菜单",
		routePath: "/system/user",
		componentPath: "/pages/system/user/index",
		permissionKey: "system:user:list",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-15 10:30:00",
		icon: "mdi:account",
	},
	{
		menuId: "MENU003",
		menuName: "角色管理",
		parentMenu: "系统管理",
		menuType: "菜单",
		routePath: "/system/role",
		componentPath: "/pages/system/role/index",
		permissionKey: "system:role:list",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-15 11:45:00",
		icon: "mdi:shield-account",
	},
	{
		menuId: "MENU004",
		menuName: "菜单管理",
		parentMenu: "系统管理",
		menuType: "菜单",
		routePath: "/system/menu",
		componentPath: "/pages/system/menu/index",
		permissionKey: "system:menu:list",
		sortNo: 3,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-15 14:20:00",
		icon: "mdi:menu",
	},
	{
		menuId: "MENU005",
		menuName: "权限管理",
		parentMenu: "系统管理",
		menuType: "菜单",
		routePath: "/system/permission",
		componentPath: "/pages/system/permission/index",
		permissionKey: "system:permission:list",
		sortNo: 4,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-15 16:10:00",
		icon: "mdi:key",
	},
	{
		menuId: "MENU006",
		menuName: "用户查询",
		parentMenu: "用户管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:user:query",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-15 17:30:00",
		icon: "",
	},
	{
		menuId: "MENU007",
		menuName: "用户新增",
		parentMenu: "用户管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:user:add",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-15 18:45:00",
		icon: "",
	},
	{
		menuId: "MENU008",
		menuName: "用户修改",
		parentMenu: "用户管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:user:edit",
		sortNo: 3,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-15 19:15:00",
		icon: "",
	},
	{
		menuId: "MENU009",
		menuName: "用户删除",
		parentMenu: "用户管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:user:remove",
		sortNo: 4,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-15 20:00:00",
		icon: "",
	},
	{
		menuId: "MENU010",
		menuName: "角色查询",
		parentMenu: "角色管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:role:query",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-16 09:30:00",
		icon: "",
	},
	{
		menuId: "MENU011",
		menuName: "角色新增",
		parentMenu: "角色管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:role:add",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-16 10:45:00",
		icon: "",
	},
	{
		menuId: "MENU012",
		menuName: "监控管理",
		parentMenu: "根菜单",
		menuType: "目录",
		routePath: "/monitor",
		componentPath: "",
		permissionKey: "monitor:manage",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-16 13:20:00",
		icon: "mdi:monitor",
	},
	{
		menuId: "MENU013",
		menuName: "在线用户",
		parentMenu: "监控管理",
		menuType: "菜单",
		routePath: "/monitor/online",
		componentPath: "/pages/monitor/online/index",
		permissionKey: "monitor:online:list",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-16 14:50:00",
		icon: "mdi:account-group",
	},
	{
		menuId: "MENU014",
		menuName: "定时任务",
		parentMenu: "监控管理",
		menuType: "菜单",
		routePath: "/monitor/job",
		componentPath: "/pages/monitor/job/index",
		permissionKey: "monitor:job:list",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-16 16:30:00",
		icon: "mdi:clock",
	},
	{
		menuId: "MENU015",
		menuName: "数据监控",
		parentMenu: "监控管理",
		menuType: "菜单",
		routePath: "/monitor/data",
		componentPath: "/pages/monitor/data/index",
		permissionKey: "monitor:data:list",
		sortNo: 3,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-16 18:15:00",
		icon: "mdi:chart-line",
	},
	{
		menuId: "MENU016",
		menuName: "服务监控",
		parentMenu: "监控管理",
		menuType: "菜单",
		routePath: "/monitor/server",
		componentPath: "/pages/monitor/server/index",
		permissionKey: "monitor:server:list",
		sortNo: 4,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-17 09:00:00",
		icon: "mdi:server",
	},
	{
		menuId: "MENU017",
		menuName: "缓存监控",
		parentMenu: "监控管理",
		menuType: "菜单",
		routePath: "/monitor/cache",
		componentPath: "/pages/monitor/cache/index",
		permissionKey: "monitor:cache:list",
		sortNo: 5,
		status: "禁用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-17 10:30:00",
		icon: "mdi:database",
	},
	{
		menuId: "MENU018",
		menuName: "系统工具",
		parentMenu: "根菜单",
		menuType: "目录",
		routePath: "/tool",
		componentPath: "",
		permissionKey: "tool:manage",
		sortNo: 3,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-17 14:00:00",
		icon: "mdi:tools",
	},
	{
		menuId: "MENU019",
		menuName: "表单构建",
		parentMenu: "系统工具",
		menuType: "菜单",
		routePath: "/tool/build",
		componentPath: "/pages/tool/build/index",
		permissionKey: "tool:build:list",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-17 15:45:00",
		icon: "mdi:form",
	},
	{
		menuId: "MENU020",
		menuName: "代码生成",
		parentMenu: "系统工具",
		menuType: "菜单",
		routePath: "/tool/gen",
		componentPath: "/pages/tool/gen/index",
		permissionKey: "tool:gen:list",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-17 17:20:00",
		icon: "mdi:code",
	},
	{
		menuId: "MENU021",
		menuName: "系统接口",
		parentMenu: "系统工具",
		menuType: "菜单",
		routePath: "/tool/swagger",
		componentPath: "/pages/tool/swagger/index",
		permissionKey: "tool:swagger:list",
		sortNo: 3,
		status: "启用",
		isExternal: "是",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-18 09:15:00",
		icon: "mdi:api",
	},
	{
		menuId: "MENU022",
		menuName: "开发文档",
		parentMenu: "系统工具",
		menuType: "菜单",
		routePath: "http://doc.ruoyi.vip",
		componentPath: "",
		permissionKey: "tool:doc:list",
		sortNo: 4,
		status: "启用",
		isExternal: "是",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-18 11:30:00",
		icon: "mdi:file-document",
	},
	{
		menuId: "MENU023",
		menuName: "日志管理",
		parentMenu: "根菜单",
		menuType: "目录",
		routePath: "/log",
		componentPath: "",
		permissionKey: "log:manage",
		sortNo: 4,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "是",
		createTime: "2024-03-18 14:45:00",
		icon: "mdi:note-text",
	},
	{
		menuId: "MENU024",
		menuName: "操作日志",
		parentMenu: "日志管理",
		menuType: "菜单",
		routePath: "/log/operlog",
		componentPath: "/pages/log/operlog/index",
		permissionKey: "log:operlog:list",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-18 16:10:00",
		icon: "mdi:history",
	},
	{
		menuId: "MENU025",
		menuName: "登录日志",
		parentMenu: "日志管理",
		menuType: "菜单",
		routePath: "/log/loginlog",
		componentPath: "/pages/log/loginlog/index",
		permissionKey: "log:loginlog:list",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-18 18:30:00",
		icon: "mdi:login",
	},
	{
		menuId: "MENU026",
		menuName: "系统设置",
		parentMenu: "根菜单",
		menuType: "目录",
		routePath: "/config",
		componentPath: "",
		permissionKey: "config:manage",
		sortNo: 5,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "是",
		createTime: "2024-03-19 09:00:00",
		icon: "mdi:settings",
	},
	{
		menuId: "MENU027",
		menuName: "参数设置",
		parentMenu: "系统设置",
		menuType: "菜单",
		routePath: "/config/param",
		componentPath: "/pages/config/param/index",
		permissionKey: "config:param:list",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-19 10:15:00",
		icon: "mdi:tune",
	},
	{
		menuId: "MENU028",
		menuName: "通知公告",
		parentMenu: "系统设置",
		menuType: "菜单",
		routePath: "/config/notice",
		componentPath: "/pages/config/notice/index",
		permissionKey: "config:notice:list",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-19 13:45:00",
		icon: "mdi:bell",
	},
	{
		menuId: "MENU029",
		menuName: "字典管理",
		parentMenu: "系统设置",
		menuType: "菜单",
		routePath: "/config/dict",
		componentPath: "/pages/config/dict/index",
		permissionKey: "config:dict:list",
		sortNo: 3,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-19 15:20:00",
		icon: "mdi:book",
	},
	{
		menuId: "MENU030",
		menuName: "部门管理",
		parentMenu: "系统管理",
		menuType: "菜单",
		routePath: "/system/dept",
		componentPath: "/pages/system/dept/index",
		permissionKey: "system:dept:list",
		sortNo: 5,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-19 17:30:00",
		icon: "mdi:office-building",
	},
	{
		menuId: "MENU031",
		menuName: "岗位管理",
		parentMenu: "系统管理",
		menuType: "菜单",
		routePath: "/system/post",
		componentPath: "/pages/system/post/index",
		permissionKey: "system:post:list",
		sortNo: 6,
		status: "启用",
		isExternal: "否",
		isCached: "是",
		isHidden: "否",
		createTime: "2024-03-20 09:45:00",
		icon: "mdi:badge",
	},
	{
		menuId: "MENU032",
		menuName: "字典类型",
		parentMenu: "字典管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:dict:type",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-20 11:00:00",
		icon: "",
	},
	{
		menuId: "MENU033",
		menuName: "字典数据",
		parentMenu: "字典管理",
		menuType: "按钮",
		routePath: "",
		componentPath: "",
		permissionKey: "system:dict:data",
		sortNo: 2,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-20 12:30:00",
		icon: "",
	},
	{
		menuId: "MENU034",
		menuName: "通知公告接口",
		parentMenu: "通知公告",
		menuType: "接口",
		routePath: "",
		componentPath: "",
		permissionKey: "config:notice:api",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-20 14:15:00",
		icon: "",
	},
	{
		menuId: "MENU035",
		menuName: "参数设置接口",
		parentMenu: "参数设置",
		menuType: "接口",
		routePath: "",
		componentPath: "",
		permissionKey: "config:param:api",
		sortNo: 1,
		status: "启用",
		isExternal: "否",
		isCached: "否",
		isHidden: "否",
		createTime: "2024-03-20 16:45:00",
		icon: "",
	},
];
