import type { HandingBusinessListItem } from "@01s-11comm/type";

/** Handing Business 模拟数据 */
export const mockHandingBusinessData: HandingBusinessListItem[] = [
    {
        feeItem: "物业费",
        feeId: "FEE001",
        feeType: "周期费用",
        amountReceivable: "500.00",
        accountCreationTime: "2024-01-01",
        receivablePeriod: "2024年1月",
        description: "1月份物业管理费",
        status: "待缴费",
    },
    {
        feeItem: "水电费",
        feeId: "FEE002",
        feeType: "周期费用",
        amountReceivable: "320.50",
        accountCreationTime: "2024-01-05",
        receivablePeriod: "2024年1月",
        description: "1月份水电费",
        status: "已缴费",
    },
    {
        feeItem: "停车费",
        feeId: "FEE003",
        feeType: "周期费用",
        amountReceivable: "300.00",
        accountCreationTime: "2024-01-01",
        receivablePeriod: "2024年1月",
        description: "1月份地下车位停车费",
        status: "已缴费",
    },
    {
        feeItem: "电梯维保费",
        feeId: "FEE004",
        feeType: "临时费用",
        amountReceivable: "1500.00",
        accountCreationTime: "2024-01-10",
        receivablePeriod: "2024年1季度",
        description: "电梯季度维保费用",
        status: "待缴费",
    },
    {
        feeItem: "装修押金",
        feeId: "FEE005",
        feeType: "押金",
        amountReceivable: "2000.00",
        accountCreationTime: "2024-01-08",
        receivablePeriod: "2024年1月",
        description: "3号楼装修押金",
        status: "已减免",
    },
    {
        feeItem: "滞纳金",
        feeId: "FEE006",
        feeType: "违约金",
        amountReceivable: "50.00",
        accountCreationTime: "2024-01-15",
        receivablePeriod: "2023年12月",
        description: "12月物业费滞纳金",
        status: "已逾期",
    },
    {
        feeItem: "物业费",
        feeId: "FEE007",
        feeType: "周期费用",
        amountReceivable: "500.00",
        accountCreationTime: "2024-02-01",
        receivablePeriod: "2024年2月",
        description: "2月份物业管理费",
        status: "待缴费",
    },
    {
        feeItem: "水电费",
        feeId: "FEE008",
        feeType: "周期费用",
        amountReceivable: "280.00",
        accountCreationTime: "2024-02-05",
        receivablePeriod: "2024年2月",
        description: "2月份水电费",
        status: "已缴费",
    },
    {
        feeItem: "停车费",
        feeId: "FEE009",
        feeType: "周期费用",
        amountReceivable: "300.00",
        accountCreationTime: "2024-02-01",
        receivablePeriod: "2024年2月",
        description: "2月份地下车位停车费",
        status: "待缴费",
    },
    {
        feeItem: "绿化养护费",
        feeId: "FEE010",
        feeType: "临时费用",
        amountReceivable: "800.00",
        accountCreationTime: "2024-02-10",
        receivablePeriod: "2024年春季",
        description: "春季小区绿化养护费",
        status: "待缴费",
    },
    {
        feeItem: "装修押金",
        feeId: "FEE011",
        feeType: "押金",
        amountReceivable: "2000.00",
        accountCreationTime: "2024-02-12",
        receivablePeriod: "2024年2月",
        description: "5号楼装修押金",
        status: "待缴费",
    },
    {
        feeItem: "物业费",
        feeId: "FEE012",
        feeType: "周期费用",
        amountReceivable: "550.00",
        accountCreationTime: "2024-03-01",
        receivablePeriod: "2024年3月",
        description: "3月份物业管理费",
        status: "待缴费",
    },
    {
        feeItem: "水电费",
        feeId: "FEE013",
        feeType: "周期费用",
        amountReceivable: "350.00",
        accountCreationTime: "2024-03-05",
        receivablePeriod: "2024年3月",
        description: "3月份水电费",
        status: "待缴费",
    },
    {
        feeItem: "停车费",
        feeId: "FEE014",
        feeType: "周期费用",
        amountReceivable: "300.00",
        accountCreationTime: "2024-03-01",
        receivablePeriod: "2024年3月",
        description: "3月份地下车位停车费",
        status: "待缴费",
    },
    {
        feeItem: "垃圾处理费",
        feeId: "FEE015",
        feeType: "临时费用",
        amountReceivable: "200.00",
        accountCreationTime: "2024-03-10",
        receivablePeriod: "2024年1季度",
        description: "1季度垃圾处理费",
        status: "已缴费",
    },
    {
        feeItem: "物业费",
        feeId: "FEE016",
        feeType: "周期费用",
        amountReceivable: "500.00",
        accountCreationTime: "2023-12-01",
        receivablePeriod: "2023年12月",
        description: "12月份物业管理费",
        status: "已逾期",
    },
    {
        feeItem: "水电费",
        feeId: "FEE017",
        feeType: "周期费用",
        amountReceivable: "290.00",
        accountCreationTime: "2023-12-05",
        receivablePeriod: "2023年12月",
        description: "12月份水电费",
        status: "已缴费",
    },
    {
        feeItem: "停车费",
        feeId: "FEE018",
        feeType: "周期费用",
        amountReceivable: "300.00",
        accountCreationTime: "2023-12-01",
        receivablePeriod: "2023年12月",
        description: "12月份地下车位停车费",
        status: "已作废",
    },
    {
        feeItem: "公共维修金",
        feeId: "FEE019",
        feeType: "周期费用",
        amountReceivable: "200.00",
        accountCreationTime: "2024-01-01",
        receivablePeriod: "2024年全年",
        description: "2024年度公共维修基金",
        status: "待缴费",
    },
    {
        feeItem: "宽带接入费",
        feeId: "FEE020",
        feeType: "临时费用",
        amountReceivable: "1000.00",
        accountCreationTime: "2024-01-20",
        receivablePeriod: "一次性",
        description: "小区宽带接入初装费",
        status: "已缴费",
    },
    {
        feeItem: "物业费",
        feeId: "FEE021",
        feeType: "周期费用",
        amountReceivable: "480.00",
        accountCreationTime: "2024-04-01",
        receivablePeriod: "2024年4月",
        description: "4月份物业管理费",
        status: "待缴费",
    },
    {
        feeItem: "水电费",
        feeId: "FEE022",
        feeType: "周期费用",
        amountReceivable: "310.00",
        accountCreationTime: "2024-04-05",
        receivablePeriod: "2024年4月",
        description: "4月份水电费",
        status: "待缴费",
    },
    {
        feeItem: "停车费",
        feeId: "FEE023",
        feeType: "周期费用",
        amountReceivable: "300.00",
        accountCreationTime: "2024-04-01",
        receivablePeriod: "2024年4月",
        description: "4月份地下车位停车费",
        status: "待缴费",
    },
    {
        feeItem: "门禁系统费",
        feeId: "FEE024",
        feeType: "临时费用",
        amountReceivable: "500.00",
        accountCreationTime: "2024-04-15",
        receivablePeriod: "一次性",
        description: "智能门禁系统升级费",
        status: "待缴费",
    },
];
