import type { AttachmentListItem } from "@01s-11comm/type";

/**
 * 合同附件模拟数据
 * Attachment mock data
 */
export const mockAttachmentData: AttachmentListItem[] = [
	{
		id: "1",
		attachmentName: "采购合同正本扫描件",
		contractNumber: "HT-2024-001",
		contractName: "2024年度办公用品采购合同",
		attachmentType: "合同正本",
		fileSize: "2.5MB",
		fileFormat: "PDF",
		uploader: "张三",
		uploadTime: "2024-01-02 10:00:00",
		status: "正常",
		remark: "已盖章扫描件",
	},
	{
		id: "2",
		attachmentName: "营业执照复印件",
		contractNumber: "HT-2024-001",
		contractName: "2024年度办公用品采购合同",
		attachmentType: "资质证明",
		fileSize: "1.2MB",
		fileFormat: "PDF",
		uploader: "张三",
		uploadTime: "2024-01-02 10:05:00",
		status: "正常",
	},
	{
		id: "3",
		attachmentName: "物业服务合同副本",
		contractNumber: "HT-2024-002",
		contractName: "物业服务合同",
		attachmentType: "合同副本",
		fileSize: "3.8MB",
		fileFormat: "PDF",
		uploader: "李四",
		uploadTime: "2024-01-05 14:00:00",
		status: "正常",
		remark: "乙方存档副本",
	},
	{
		id: "4",
		attachmentName: "补充协议-付款方式变更",
		contractNumber: "HT-2024-002",
		contractName: "物业服务合同",
		attachmentType: "补充协议",
		fileSize: "0.8MB",
		fileFormat: "PDF",
		uploader: "李四",
		uploadTime: "2024-06-15 09:00:00",
		status: "正常",
	},
	{
		id: "5",
		attachmentName: "授权委托书",
		contractNumber: "HT-2024-003",
		contractName: "电梯维保合同",
		attachmentType: "授权文件",
		fileSize: "0.5MB",
		fileFormat: "PDF",
		uploader: "王五",
		uploadTime: "2024-03-01 11:00:00",
		status: "已删除",
		remark: "已更新新版本",
	},
	{
		id: "6",
		attachmentName: "电梯维保合同正本",
		contractNumber: "HT-2024-003",
		contractName: "电梯维保合同",
		attachmentType: "合同正本",
		fileSize: "2.1MB",
		fileFormat: "PDF",
		uploader: "王五",
		uploadTime: "2024-03-01 11:05:00",
		status: "正常",
	},
	{
		id: "7",
		attachmentName: "维保资质证明",
		contractNumber: "HT-2024-003",
		contractName: "电梯维保合同",
		attachmentType: "资质证明",
		fileSize: "1.5MB",
		fileFormat: "PDF",
		uploader: "王五",
		uploadTime: "2024-03-01 11:10:00",
		status: "正常",
	},
	{
		id: "8",
		attachmentName: "绿化养护合同副本",
		contractNumber: "HT-2024-004",
		contractName: "绿化养护合同",
		attachmentType: "合同副本",
		fileSize: "2.0MB",
		fileFormat: "PDF",
		uploader: "赵六",
		uploadTime: "2024-01-05 15:00:00",
		status: "正常",
	},
	{
		id: "9",
		attachmentName: "园林公司资质",
		contractNumber: "HT-2024-004",
		contractName: "绿化养护合同",
		attachmentType: "资质证明",
		fileSize: "3.2MB",
		fileFormat: "PDF",
		uploader: "赵六",
		uploadTime: "2024-01-05 15:05:00",
		status: "正常",
	},
	{
		id: "10",
		attachmentName: "安保服务合同正本",
		contractNumber: "HT-2024-005",
		contractName: "安保服务合同",
		attachmentType: "合同正本",
		fileSize: "2.8MB",
		fileFormat: "PDF",
		uploader: "周八",
		uploadTime: "2024-01-08 16:00:00",
		status: "正常",
	},
	{
		id: "11",
		attachmentName: "保安公司营业执照",
		contractNumber: "HT-2024-005",
		contractName: "安保服务合同",
		attachmentType: "资质证明",
		fileSize: "1.0MB",
		fileFormat: "PDF",
		uploader: "周八",
		uploadTime: "2024-01-08 16:05:00",
		status: "正常",
	},
	{
		id: "12",
		attachmentName: "安保人员备案证明",
		contractNumber: "HT-2024-005",
		contractName: "安保服务合同",
		attachmentType: "授权文件",
		fileSize: "0.6MB",
		fileFormat: "PDF",
		uploader: "周八",
		uploadTime: "2024-01-08 16:10:00",
		status: "正常",
	},
	{
		id: "13",
		attachmentName: "保洁服务合同副本",
		contractNumber: "HT-2024-006",
		contractName: "保洁服务合同",
		attachmentType: "合同副本",
		fileSize: "2.3MB",
		fileFormat: "PDF",
		uploader: "吴九",
		uploadTime: "2024-02-02 10:00:00",
		status: "正常",
	},
	{
		id: "14",
		attachmentName: "保洁公司资质证明",
		contractNumber: "HT-2024-006",
		contractName: "保洁服务合同",
		attachmentType: "资质证明",
		fileSize: "1.8MB",
		fileFormat: "PDF",
		uploader: "吴九",
		uploadTime: "2024-02-02 10:05:00",
		status: "正常",
	},
	{
		id: "15",
		attachmentName: "补充协议-服务内容变更",
		contractNumber: "HT-2024-006",
		contractName: "保洁服务合同",
		attachmentType: "补充协议",
		fileSize: "0.7MB",
		fileFormat: "PDF",
		uploader: "吴九",
		uploadTime: "2024-06-01 14:00:00",
		status: "正常",
	},
	{
		id: "16",
		attachmentName: "消防设备采购合同正本",
		contractNumber: "HT-2024-007",
		contractName: "消防设备采购合同",
		attachmentType: "合同正本",
		fileSize: "2.6MB",
		fileFormat: "PDF",
		uploader: "郑十",
		uploadTime: "2024-04-02 11:00:00",
		status: "正常",
	},
	{
		id: "17",
		attachmentName: "消防产品检测报告",
		contractNumber: "HT-2024-007",
		contractName: "消防设备采购合同",
		attachmentType: "资质证明",
		fileSize: "4.5MB",
		fileFormat: "PDF",
		uploader: "郑十",
		uploadTime: "2024-04-02 11:05:00",
		status: "正常",
	},
	{
		id: "18",
		attachmentName: "安装验收报告",
		contractNumber: "HT-2024-007",
		contractName: "消防设备采购合同",
		attachmentType: "其他",
		fileSize: "1.2MB",
		fileFormat: "PDF",
		uploader: "郑十",
		uploadTime: "2024-06-30 16:00:00",
		status: "正常",
	},
	{
		id: "19",
		attachmentName: "广告位租赁合同正本",
		contractNumber: "HT-2024-008",
		contractName: "广告位租赁合同",
		attachmentType: "合同正本",
		fileSize: "2.0MB",
		fileFormat: "PDF",
		uploader: "钱十一",
		uploadTime: "2024-05-02 14:00:00",
		status: "正常",
	},
	{
		id: "20",
		attachmentName: "广告位示意图",
		contractNumber: "HT-2024-008",
		contractName: "广告位租赁合同",
		attachmentType: "其他",
		fileSize: "3.5MB",
		fileFormat: "PDF",
		uploader: "钱十一",
		uploadTime: "2024-05-02 14:05:00",
		status: "正常",
	},
];
