import type { HouseListItem } from "@01s-11comm/type";

/**
 * @description 房屋管理模拟数据
 * House mock data
 */
export const mockHouseData: HouseListItem[] = [
	{
		houseCode: "A栋101",
		floor: "1楼",
		owner: "张先生",
		houseType: "住宅",
		houseArea: "120㎡",
		rent: "3000元/月",
		houseStatus: "已入住",
		validUntil: "2025-12-31",
		ownerMembers: "3人",
		ownerVehicles: "1辆",
		ownerHouses: "1套",
		complaints: "0次",
		repairs: "2次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
	{
		houseCode: "A栋102",
		floor: "1楼",
		owner: "李女士",
		houseType: "住宅",
		houseArea: "98㎡",
		rent: "2500元/月",
		houseStatus: "已出租",
		validUntil: "2024-12-31",
		ownerMembers: "2人",
		ownerVehicles: "1辆",
		ownerHouses: "1套",
		complaints: "1次",
		repairs: "1次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
	{
		houseCode: "A栋201",
		floor: "2楼",
		owner: "王总",
		houseType: "住宅",
		houseArea: "150㎡",
		rent: "4500元/月",
		houseStatus: "已装修",
		validUntil: "2025-06-30",
		ownerMembers: "4人",
		ownerVehicles: "2辆",
		ownerHouses: "1套",
		complaints: "0次",
		repairs: "0次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
	{
		houseCode: "A栋202",
		floor: "2楼",
		owner: "赵经理",
		houseType: "办公室",
		houseArea: "80㎡",
		rent: "3500元/月",
		houseStatus: "空闲",
		validUntil: "2024-12-31",
		ownerMembers: "0人",
		ownerVehicles: "0辆",
		ownerHouses: "0套",
		complaints: "0次",
		repairs: "0次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "无",
	},
	{
		houseCode: "B栋101",
		floor: "1楼",
		owner: "孙设计师",
		houseType: "住宅",
		houseArea: "110㎡",
		rent: "2800元/月",
		houseStatus: "装修中",
		validUntil: "2025-03-31",
		ownerMembers: "2人",
		ownerVehicles: "1辆",
		ownerHouses: "1套",
		complaints: "0次",
		repairs: "1次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
	{
		houseCode: "B栋102",
		floor: "1楼",
		owner: "周工",
		houseType: "住宅",
		houseArea: "125㎡",
		rent: "3200元/月",
		houseStatus: "已入住",
		validUntil: "2025-12-31",
		ownerMembers: "3人",
		ownerVehicles: "1辆",
		ownerHouses: "1套",
		complaints: "0次",
		repairs: "3次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
	{
		houseCode: "B栋201",
		floor: "2楼",
		owner: "吴董事长",
		houseType: "住宅",
		houseArea: "180㎡",
		rent: "5500元/月",
		houseStatus: "已出售",
		validUntil: "2026-12-31",
		ownerMembers: "5人",
		ownerVehicles: "2辆",
		ownerHouses: "1套",
		complaints: "0次",
		repairs: "2次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
	{
		houseCode: "B栋202",
		floor: "2楼",
		owner: "郑总监",
		houseType: "办公室",
		houseArea: "90㎡",
		rent: "2800元/月",
		houseStatus: "已交房",
		validUntil: "2024-12-31",
		ownerMembers: "0人",
		ownerVehicles: "0辆",
		ownerHouses: "0套",
		complaints: "0次",
		repairs: "0次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
	{
		houseCode: "C栋101",
		floor: "1楼",
		owner: "陈店长",
		houseType: "储物间",
		houseArea: "25㎡",
		rent: "500元/月",
		houseStatus: "空闲",
		validUntil: "2024-12-31",
		ownerMembers: "0人",
		ownerVehicles: "0辆",
		ownerHouses: "0套",
		complaints: "0次",
		repairs: "0次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "无",
	},
	{
		houseCode: "C栋102",
		floor: "1楼",
		owner: "林设计师",
		houseType: "住宅",
		houseArea: "105㎡",
		rent: "2600元/月",
		houseStatus: "未入住",
		validUntil: "2025-12-31",
		ownerMembers: "2人",
		ownerVehicles: "1辆",
		ownerHouses: "1套",
		complaints: "0次",
		repairs: "1次",
		houseArrears: "0元",
		ownerArrears: "0元",
		houseContract: "有效",
	},
];

