import type { HouseListItem } from "@01s-11comm/type";

/** House 模拟数据 */
export const mockHouseHouseData: HouseListItem[] = [
    {
        houseCode: "A-101",
        floor: "1",
        owner: "张三",
        houseType: "住宅",
        houseArea: "120",
        rent: "3500",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "3",
        ownerVehicles: "1",
        ownerHouses: "1",
        complaints: "0",
        repairs: "1",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "A-102",
        floor: "1",
        owner: "李四",
        houseType: "住宅",
        houseArea: "85",
        rent: "2800",
        houseStatus: "已出租",
        validUntil: "2025-06-30",
        ownerMembers: "2",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "1",
        repairs: "0",
        houseArrears: "1200",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "A-201",
        floor: "2",
        owner: "王五",
        houseType: "住宅",
        houseArea: "120",
        rent: "3600",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "4",
        ownerVehicles: "2",
        ownerHouses: "1",
        complaints: "0",
        repairs: "2",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "A-202",
        floor: "2",
        owner: "赵六",
        houseType: "办公室",
        houseArea: "150",
        rent: "5000",
        houseStatus: "已交房",
        validUntil: "2025-09-30",
        ownerMembers: "0",
        ownerVehicles: "1",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "A-301",
        floor: "3",
        owner: "钱七",
        houseType: "住宅",
        houseArea: "95",
        rent: "3000",
        houseStatus: "未销售",
        validUntil: "",
        ownerMembers: "0",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "无",
    },
    {
        houseCode: "A-302",
        floor: "3",
        owner: "孙八",
        houseType: "住宅",
        houseArea: "110",
        rent: "3400",
        houseStatus: "已装修",
        validUntil: "2025-03-15",
        ownerMembers: "3",
        ownerVehicles: "1",
        ownerHouses: "1",
        complaints: "0",
        repairs: "3",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "B-101",
        floor: "1",
        owner: "周九",
        houseType: "住宅",
        houseArea: "125",
        rent: "3800",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "2",
        ownerVehicles: "1",
        ownerHouses: "1",
        complaints: "1",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "B-102",
        floor: "1",
        owner: "吴十",
        houseType: "宿舍",
        houseArea: "60",
        rent: "1800",
        houseStatus: "已出租",
        validUntil: "2025-08-31",
        ownerMembers: "1",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "2",
        repairs: "1",
        houseArrears: "600",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "B-201",
        floor: "2",
        owner: "郑十一",
        houseType: "住宅",
        houseArea: "130",
        rent: "4000",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "5",
        ownerVehicles: "2",
        ownerHouses: "1",
        complaints: "0",
        repairs: "1",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "B-202",
        floor: "2",
        owner: "冯十二",
        houseType: "储物间",
        houseArea: "20",
        rent: "500",
        houseStatus: "空闲",
        validUntil: "",
        ownerMembers: "0",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "无",
    },
    {
        houseCode: "B-301",
        floor: "3",
        owner: "陈十三",
        houseType: "住宅",
        houseArea: "115",
        rent: "3500",
        houseStatus: "已出售",
        validUntil: "2024-06-30",
        ownerMembers: "3",
        ownerVehicles: "1",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "B-302",
        floor: "3",
        owner: "楚十四",
        houseType: "住宅",
        houseArea: "105",
        rent: "3200",
        houseStatus: "装修中",
        validUntil: "2025-04-30",
        ownerMembers: "2",
        ownerVehicles: "1",
        ownerHouses: "1",
        complaints: "0",
        repairs: "2",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "C-101",
        floor: "1",
        owner: "魏十五",
        houseType: "办公室",
        houseArea: "200",
        rent: "8000",
        houseStatus: "已交房",
        validUntil: "2026-01-01",
        ownerMembers: "0",
        ownerVehicles: "3",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "C-102",
        floor: "1",
        owner: "蒋十六",
        houseType: "住宅",
        houseArea: "90",
        rent: "2800",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "2",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "1",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "C-201",
        floor: "2",
        owner: "沈十七",
        houseType: "住宅",
        houseArea: "140",
        rent: "4200",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "4",
        ownerVehicles: "2",
        ownerHouses: "1",
        complaints: "0",
        repairs: "1",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "C-202",
        floor: "2",
        owner: "韩十八",
        houseType: "住宅",
        houseArea: "88",
        rent: "2700",
        houseStatus: "已出租",
        validUntil: "2025-07-31",
        ownerMembers: "1",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "900",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "C-301",
        floor: "3",
        owner: "杨十九",
        houseType: "住宅",
        houseArea: "100",
        rent: "3100",
        houseStatus: "未入住",
        validUntil: "2024-12-31",
        ownerMembers: "0",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "3100",
        houseContract: "有",
    },
    {
        houseCode: "C-302",
        floor: "3",
        owner: "朱二十",
        houseType: "住宅",
        houseArea: "118",
        rent: "3600",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "3",
        ownerVehicles: "1",
        ownerHouses: "1",
        complaints: "1",
        repairs: "1",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "D-101",
        floor: "1",
        owner: "秦二十一",
        houseType: "住宅",
        houseArea: "125",
        rent: "3800",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "4",
        ownerVehicles: "2",
        ownerHouses: "1",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "D-102",
        floor: "1",
        owner: "许二十二",
        houseType: "住宅",
        houseArea: "95",
        rent: "2900",
        houseStatus: "已出租",
        validUntil: "2025-05-31",
        ownerMembers: "2",
        ownerVehicles: "1",
        ownerHouses: "0",
        complaints: "0",
        repairs: "1",
        houseArrears: "580",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "D-201",
        floor: "2",
        owner: "何二十三",
        houseType: "住宅",
        houseArea: "110",
        rent: "3400",
        houseStatus: "已装修",
        validUntil: "2025-02-28",
        ownerMembers: "2",
        ownerVehicles: "1",
        ownerHouses: "1",
        complaints: "0",
        repairs: "2",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "D-202",
        floor: "2",
        owner: "吕二十四",
        houseType: "办公室",
        houseArea: "180",
        rent: "6500",
        houseStatus: "已交房",
        validUntil: "2025-12-31",
        ownerMembers: "0",
        ownerVehicles: "2",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "D-301",
        floor: "3",
        owner: "施二十五",
        houseType: "住宅",
        houseArea: "135",
        rent: "4100",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "3",
        ownerVehicles: "1",
        ownerHouses: "1",
        complaints: "1",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
    {
        houseCode: "D-302",
        floor: "3",
        owner: "张二十六",
        houseType: "住宅",
        houseArea: "105",
        rent: "3200",
        houseStatus: "空闲",
        validUntil: "",
        ownerMembers: "0",
        ownerVehicles: "0",
        ownerHouses: "0",
        complaints: "0",
        repairs: "0",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "无",
    },
    {
        houseCode: "E-101",
        floor: "1",
        owner: "孔二十七",
        houseType: "住宅",
        houseArea: "120",
        rent: "3600",
        houseStatus: "已入住",
        validUntil: "2025-12-31",
        ownerMembers: "4",
        ownerVehicles: "2",
        ownerHouses: "1",
        complaints: "0",
        repairs: "1",
        houseArrears: "0",
        ownerArrears: "0",
        houseContract: "有",
    },
];
