import type { WorkingSchedule } from "@01s-11comm/type";

/**
 * 模拟排班表数据
 */
export const mockWorkingScheduleData: WorkingSchedule[] = [
	{
		id: "1",
		name: "客服中心早班",
		type: "morning",
		startTime: "08:00",
		endTime: "16:00",
		weekday: 1,
		managerName: "张三",
		phone: "13800138001",
		enabled: true,
		description: "客服中心早班排班",
	},
	{
		id: "2",
		name: "客服中心中班",
		type: "afternoon",
		startTime: "16:00",
		endTime: "24:00",
		weekday: 1,
		managerName: "李四",
		phone: "13800138002",
		enabled: true,
		description: "客服中心中班排班",
	},
	{
		id: "3",
		name: "工程部维修班",
		type: "morning",
		startTime: "09:00",
		endTime: "18:00",
		weekday: 2,
		managerName: "王五",
		phone: "13800138003",
		enabled: true,
		description: "工程部日常维修班",
	},
	{
		id: "4",
		name: "安保部夜班",
		type: "night",
		startTime: "00:00",
		endTime: "08:00",
		weekday: 3,
		managerName: "赵六",
		phone: "13800138004",
		enabled: true,
		description: "安保部夜班巡逻",
	},
	{
		id: "5",
		name: "物业办公室全天班",
		type: "全天",
		startTime: "09:00",
		endTime: "18:00",
		weekday: 4,
		managerName: "钱七",
		phone: "13800138005",
		enabled: true,
		description: "物业办公室正常工作班",
	},
	{
		id: "6",
		name: "保洁部晚班",
		type: "evening",
		startTime: "18:00",
		endTime: "22:00",
		weekday: 5,
		managerName: "孙八",
		phone: "13800138006",
		enabled: true,
		description: "保洁部晚班清洁",
	},
	{
		id: "7",
		name: "客服中心周末班",
		type: "morning",
		startTime: "10:00",
		endTime: "16:00",
		weekday: 6,
		managerName: "周九",
		phone: "13800138007",
		enabled: true,
		description: "客服中心周末值班",
	},
];
