import type { RefreshCacheListItem } from "@01s-11comm/type";

/**
 * @description 刷新缓存模拟数据
 * Refresh cache mock data
 */
export const mockRefreshCacheData: RefreshCacheListItem[] = [
	{
		cacheId: "CACHE_001",
		cacheCode: "REDIS_001",
		cacheName: "用户信息缓存",
		cacheKey: "user:info:{userId}",
		cacheType: "Redis",
		cacheGroup: "user",
		expirationTime: 3600,
		cacheDescription: "存储用户基本信息，包括用户名、头像、权限等级等核心数据",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-08-15 09:30:00",
		lastUpdateTime: "2024-09-12 18:20:00",
	},
	{
		cacheId: "CACHE_002",
		cacheCode: "REDIS_002",
		cacheName: "商品详情缓存",
		cacheKey: "product:detail:{productId}",
		cacheType: "Redis",
		cacheGroup: "product",
		expirationTime: 7200,
		cacheDescription: "商品详情页数据缓存，包含商品基本信息、价格、库存等",
		refreshStrategy: "事件触发刷新",
		status: "启用",
		createTime: "2024-08-08 11:05:00",
		lastUpdateTime: "2024-09-05 15:42:00",
	},
	{
		cacheId: "CACHE_003",
		cacheCode: "MEMORY_003",
		cacheName: "系统配置缓存",
		cacheKey: "system:config:{module}",
		cacheType: "Memory",
		cacheGroup: "system",
		expirationTime: 86400,
		cacheDescription: "系统全局配置参数，包括数据库连接、API接口地址等配置信息",
		refreshStrategy: "手动刷新",
		status: "启用",
		createTime: "2024-07-20 10:12:00",
		lastUpdateTime: "2024-08-28 13:18:00",
	},
	{
		cacheId: "CACHE_004",
		cacheCode: "REDIS_004",
		cacheName: "订单状态缓存",
		cacheKey: "order:status:{orderId}",
		cacheType: "Redis",
		cacheGroup: "order",
		expirationTime: 1800,
		cacheDescription: "订单处理状态缓存，跟踪订单从创建到完成的整个生命周期",
		refreshStrategy: "事件触发刷新",
		status: "启用",
		createTime: "2024-08-01 14:05:00",
		lastUpdateTime: "2024-09-10 16:26:00",
	},
	{
		cacheId: "CACHE_005",
		cacheCode: "CAFFEINE_005",
		cacheName: "权限验证缓存",
		cacheKey: "auth:permission:{userId}:{resource}",
		cacheType: "Caffeine",
		cacheGroup: "auth",
		expirationTime: 600,
		cacheDescription: "用户权限验证结果缓存，提升系统安全校验性能",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-08-03 08:55:00",
		lastUpdateTime: "2024-09-01 12:10:00",
	},
	{
		cacheId: "CACHE_006",
		cacheCode: "REDIS_006",
		cacheName: "API限流缓存",
		cacheKey: "rate:limit:{api}:{clientIp}",
		cacheType: "Redis",
		cacheGroup: "api",
		expirationTime: 60,
		cacheDescription: "API接口访问频率限制，防止恶意请求和系统过载",
		refreshStrategy: "LRU淘汰刷新",
		status: "启用",
		createTime: "2024-07-28 09:45:00",
		lastUpdateTime: "2024-09-02 10:08:00",
	},
	{
		cacheId: "CACHE_007",
		cacheCode: "MEMORY_007",
		cacheName: "导航菜单缓存",
		cacheKey: "menu:navigation:{userId}",
		cacheType: "Memory",
		cacheGroup: "ui",
		expirationTime: 3600,
		cacheDescription: "用户个性化导航菜单配置，包含快捷入口和常用功能",
		refreshStrategy: "懒加载刷新",
		status: "启用",
		createTime: "2024-07-15 17:30:00",
		lastUpdateTime: "2024-08-25 19:05:00",
	},
	{
		cacheId: "CACHE_008",
		cacheCode: "MEMCACHED_008",
		cacheName: "搜索结果缓存",
		cacheKey: "search:result:{keyword}:{page}",
		cacheType: "Memcached",
		cacheGroup: "search",
		expirationTime: 900,
		cacheDescription: "热门搜索关键词结果缓存，减少数据库查询压力",
		refreshStrategy: "定时刷新",
		status: "启用",
		createTime: "2024-08-05 10:40:00",
		lastUpdateTime: "2024-09-04 11:32:00",
	},
	{
		cacheId: "CACHE_009",
		cacheCode: "REDIS_009",
		cacheName: "统计数据缓存",
		cacheKey: "statistics:daily:{date}:{type}",
		cacheType: "Redis",
		cacheGroup: "stats",
		expirationTime: 43200,
		cacheDescription: "日常运营统计数据，包括用户活跃度、订单量、收入等关键指标",
		refreshStrategy: "定时刷新",
		status: "启用",
		createTime: "2024-06-30 08:20:00",
		lastUpdateTime: "2024-08-30 09:10:00",
	},
	{
		cacheId: "CACHE_010",
		cacheCode: "MEMORY_010",
		cacheName: "文件上传临时缓存",
		cacheKey: "upload:temp:{uploadId}",
		cacheType: "Memory",
		cacheGroup: "file",
		expirationTime: 300,
		cacheDescription: "文件分片上传临时数据，包含已上传分片信息和校验码",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-08-10 13:14:00",
		lastUpdateTime: "2024-09-03 10:46:00",
	},
	{
		cacheId: "CACHE_011",
		cacheCode: "REDIS_011",
		cacheName: "消息推送队列缓存",
		cacheKey: "message:queue:{userId}",
		cacheType: "Redis",
		cacheGroup: "message",
		expirationTime: 1800,
		cacheDescription: "用户消息推送队列，存储待发送的系统通知和业务消息",
		refreshStrategy: "事件触发刷新",
		status: "维护中",
		createTime: "2024-07-05 16:18:00",
		lastUpdateTime: "2024-08-27 14:22:00",
	},
	{
		cacheId: "CACHE_012",
		cacheCode: "REDIS_012",
		cacheName: "分布式锁缓存",
		cacheKey: "lock:distributed:{resource}:{lockId}",
		cacheType: "Redis",
		cacheGroup: "lock",
		expirationTime: 30,
		cacheDescription: "分布式系统资源锁，防止并发操作冲突和数据不一致",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-08-02 12:50:00",
		lastUpdateTime: "2024-09-09 18:05:00",
	},
	{
		cacheId: "CACHE_013",
		cacheCode: "REDIS_013",
		cacheName: "地理位置服务缓存",
		cacheKey: "geo:location:{address}",
		cacheType: "Redis",
		cacheGroup: "geo",
		expirationTime: 7200,
		cacheDescription: "地址解析和地理位置信息缓存，提升定位服务响应速度",
		refreshStrategy: "懒加载刷新",
		status: "启用",
		createTime: "2024-07-22 09:05:00",
		lastUpdateTime: "2024-09-06 10:12:00",
	},
	{
		cacheId: "CACHE_014",
		cacheCode: "REDIS_014",
		cacheName: "验证码缓存",
		cacheKey: "captcha:verify:{session}:{type}",
		cacheType: "Redis",
		cacheGroup: "security",
		expirationTime: 300,
		cacheDescription: "图形验证码和短信验证码临时存储，用于用户身份验证",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-08-12 07:45:00",
		lastUpdateTime: "2024-09-11 08:10:00",
	},
	{
		cacheId: "CACHE_015",
		cacheCode: "GUAVA_CACHE_015",
		cacheName: "热点数据缓存",
		cacheKey: "hot:data:{category}:{itemId}",
		cacheType: "Guava Cache",
		cacheGroup: "hot",
		expirationTime: 1200,
		cacheDescription: "系统热点访问数据，如热门商品、热门文章等高频访问内容",
		refreshStrategy: "LRU淘汰刷新",
		status: "启用",
		createTime: "2024-07-18 15:00:00",
		lastUpdateTime: "2024-08-31 17:30:00",
	},
	{
		cacheId: "CACHE_016",
		cacheCode: "EHCACHE_016",
		cacheName: "计算结果缓存",
		cacheKey: "compute:result:{algorithm}:{params}",
		cacheType: "Ehcache",
		cacheGroup: "compute",
		expirationTime: 2400,
		cacheDescription: "复杂算法计算结果缓存，避免重复计算提升系统性能",
		refreshStrategy: "懒加载刷新",
		status: "启用",
		createTime: "2024-06-25 10:25:00",
		lastUpdateTime: "2024-08-22 13:40:00",
	},
	{
		cacheId: "CACHE_017",
		cacheCode: "REDIS_017",
		cacheName: "库存数据缓存",
		cacheKey: "inventory:stock:{productId}:{warehouse}",
		cacheType: "Redis",
		cacheGroup: "inventory",
		expirationTime: 600,
		cacheDescription: "实时库存数量缓存，支持高并发查询和订单库存扣减",
		refreshStrategy: "事件触发刷新",
		status: "启用",
		createTime: "2024-08-07 14:10:00",
		lastUpdateTime: "2024-09-02 15:15:00",
	},
	{
		cacheId: "CACHE_018",
		cacheCode: "REDIS_018",
		cacheName: "用户会话缓存",
		cacheKey: "session:user:{sessionId}",
		cacheType: "Redis",
		cacheGroup: "session",
		expirationTime: 7200,
		cacheDescription: "用户登录会话信息，包含登录状态、权限令牌等敏感数据",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-07-29 09:00:00",
		lastUpdateTime: "2024-09-08 10:18:00",
	},
	{
		cacheId: "CACHE_019",
		cacheCode: "REDIS_019",
		cacheName: "支付流水缓存",
		cacheKey: "payment:transaction:{transactionId}",
		cacheType: "Redis",
		cacheGroup: "payment",
		expirationTime: 900,
		cacheDescription: "支付交易流水状态，跟踪支付进度和结果回调",
		refreshStrategy: "事件触发刷新",
		status: "启用",
		createTime: "2024-08-04 11:55:00",
		lastUpdateTime: "2024-09-06 16:05:00",
	},
	{
		cacheId: "CACHE_020",
		cacheCode: "HAZELCAST_020",
		cacheName: "邮件队列缓存",
		cacheKey: "email:queue:{batchId}",
		cacheType: "Hazelcast",
		cacheGroup: "notification",
		expirationTime: 1800,
		cacheDescription: "邮件发送队列缓存，存储待发送的营销邮件和系统通知邮件",
		refreshStrategy: "定时刷新",
		status: "启用",
		createTime: "2024-07-12 13:20:00",
		lastUpdateTime: "2024-08-29 14:50:00",
	},
	{
		cacheId: "CACHE_021",
		cacheCode: "INFINISPAN_021",
		cacheName: "配置中心缓存",
		cacheKey: "config:center:{environment}:{key}",
		cacheType: "Infinispan",
		cacheGroup: "config",
		expirationTime: 600,
		cacheDescription: "动态配置中心数据缓存，支持应用运行时配置热更新",
		refreshStrategy: "事件触发刷新",
		status: "维护中",
		createTime: "2024-07-03 09:45:00",
		lastUpdateTime: "2024-08-20 12:00:00",
	},
	{
		cacheId: "CACHE_022",
		cacheCode: "MEMORY_022",
		cacheName: "API接口文档缓存",
		cacheKey: "api:doc:{version}:{endpoint}",
		cacheType: "Memory",
		cacheGroup: "doc",
		expirationTime: 3600,
		cacheDescription: "RESTful API接口文档缓存，包含请求参数说明和响应示例",
		refreshStrategy: "手动刷新",
		status: "启用",
		createTime: "2024-06-18 10:10:00",
		lastUpdateTime: "2024-08-21 09:35:00",
	},
	{
		cacheId: "CACHE_023",
		cacheCode: "REDIS_023",
		cacheName: "数据报表缓存",
		cacheKey: "report:data:{reportId}:{dateRange}",
		cacheType: "Redis",
		cacheGroup: "report",
		expirationTime: 1800,
		cacheDescription: "业务数据报表生成结果缓存，包含图表数据和汇总统计",
		refreshStrategy: "定时刷新",
		status: "启用",
		createTime: "2024-07-08 15:45:00",
		lastUpdateTime: "2024-09-03 17:25:00",
	},
	{
		cacheId: "CACHE_024",
		cacheCode: "CAFFEINE_024",
		cacheName: "用户行为记录缓存",
		cacheKey: "behavior:log:{userId}:{action}",
		cacheType: "Caffeine",
		cacheGroup: "behavior",
		expirationTime: 3600,
		cacheDescription: "用户操作行为日志缓存，用于用户画像分析和个性化推荐",
		refreshStrategy: "LRU淘汰刷新",
		status: "启用",
		createTime: "2024-07-14 16:05:00",
		lastUpdateTime: "2024-08-26 18:40:00",
	},
	{
		cacheId: "CACHE_025",
		cacheCode: "REDIS_025",
		cacheName: "CDN节点状态缓存",
		cacheKey: "cdn:node:{nodeId}:{region}",
		cacheType: "Redis",
		cacheGroup: "cdn",
		expirationTime: 120,
		cacheDescription: "CDN节点健康状态和负载情况缓存，支持智能路由选择",
		refreshStrategy: "定时刷新",
		status: "启用",
		createTime: "2024-08-09 08:25:00",
		lastUpdateTime: "2024-09-07 09:28:00",
	},
	{
		cacheId: "CACHE_026",
		cacheCode: "MEMORY_026",
		cacheName: "数据库连接池缓存",
		cacheKey: "db:pool:{instance}",
		cacheType: "Memory",
		cacheGroup: "database",
		expirationTime: 300,
		cacheDescription: "数据库连接池状态缓存，监控连接数、空闲连接等关键指标",
		refreshStrategy: "定时刷新",
		status: "启用",
		createTime: "2024-06-27 10:35:00",
		lastUpdateTime: "2024-08-19 11:40:00",
	},
	{
		cacheId: "CACHE_027",
		cacheCode: "HAZELCAST_027",
		cacheName: "微服务注册缓存",
		cacheKey: "service:registry:{serviceName}",
		cacheType: "Hazelcast",
		cacheGroup: "microservice",
		expirationTime: 60,
		cacheDescription: "微服务实例注册信息缓存，包含服务地址、健康状态等",
		refreshStrategy: "事件触发刷新",
		status: "启用",
		createTime: "2024-07-01 09:18:00",
		lastUpdateTime: "2024-08-24 10:20:00",
	},
	{
		cacheId: "CACHE_028",
		cacheCode: "MEMORY_028",
		cacheName: "日志分析缓存",
		cacheKey: "log:analysis:{app}:{level}:{timeRange}",
		cacheType: "Memory",
		cacheGroup: "log",
		expirationTime: 900,
		cacheDescription: "应用日志分析结果缓存，包含错误统计、性能趋势等",
		refreshStrategy: "定时刷新",
		status: "禁用",
		createTime: "2024-06-30 14:10:00",
		lastUpdateTime: "2024-08-16 16:48:00",
	},
	{
		cacheId: "CACHE_029",
		cacheCode: "REDIS_029",
		cacheName: "图片处理缓存",
		cacheKey: "image:process:{imageUrl}:{size}",
		cacheType: "Redis",
		cacheGroup: "media",
		expirationTime: 86400,
		cacheDescription: "图片缩略图和处理结果缓存，提升图片访问和加载速度",
		refreshStrategy: "懒加载刷新",
		status: "启用",
		createTime: "2024-07-25 12:28:00",
		lastUpdateTime: "2024-09-01 13:52:00",
	},
	{
		cacheId: "CACHE_030",
		cacheCode: "REDIS_030",
		cacheName: "短信发送限制缓存",
		cacheKey: "sms:limit:{phone}:{type}",
		cacheType: "Redis",
		cacheGroup: "sms",
		expirationTime: 3600,
		cacheDescription: "短信发送频率限制缓存，防止短信轰炸和恶意使用",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-07-11 11:34:00",
		lastUpdateTime: "2024-09-06 15:18:00",
	},
	{
		cacheId: "CACHE_031",
		cacheCode: "INFINISPAN_031",
		cacheName: "监控告警缓存",
		cacheKey: "monitor:alert:{metric}:{threshold}",
		cacheType: "Infinispan",
		cacheGroup: "monitor",
		expirationTime: 300,
		cacheDescription: "系统监控告警状态缓存，包含告警级别、处理状态等信息",
		refreshStrategy: "事件触发刷新",
		status: "维护中",
		createTime: "2024-06-22 09:12:00",
		lastUpdateTime: "2024-08-23 10:55:00",
	},
	{
		cacheId: "CACHE_032",
		cacheCode: "REDIS_032",
		cacheName: "任务调度缓存",
		cacheKey: "task:schedule:{jobId}",
		cacheType: "Redis",
		cacheGroup: "schedule",
		expirationTime: 86400,
		cacheDescription: "定时任务调度状态缓存，包含执行历史、下次执行时间等",
		refreshStrategy: "定时刷新",
		status: "启用",
		createTime: "2024-07-06 08:48:00",
		lastUpdateTime: "2024-09-02 09:26:00",
	},
	{
		cacheId: "CACHE_033",
		cacheCode: "MEMORY_033",
		cacheName: "数据字典缓存",
		cacheKey: "dict:data:{type}:{key}",
		cacheType: "Memory",
		cacheGroup: "dict",
		expirationTime: 43200,
		cacheDescription: "系统数据字典缓存，包含枚举值、状态码等基础数据",
		refreshStrategy: "手动刷新",
		status: "启用",
		createTime: "2024-06-29 10:22:00",
		lastUpdateTime: "2024-08-26 11:14:00",
	},
	{
		cacheId: "CACHE_034",
		cacheCode: "REDIS_034",
		cacheName: "文件元数据缓存",
		cacheKey: "file:metadata:{fileHash}",
		cacheType: "Redis",
		cacheGroup: "storage",
		expirationTime: 7200,
		cacheDescription: "文件存储元数据缓存，包含文件大小、类型、存储位置等",
		refreshStrategy: "懒加载刷新",
		status: "启用",
		createTime: "2024-08-14 09:38:00",
		lastUpdateTime: "2024-09-05 12:32:00",
	},
	{
		cacheId: "CACHE_035",
		cacheCode: "REDIS_035",
		cacheName: "OAuth令牌缓存",
		cacheKey: "oauth:token:{clientId}:{userId}",
		cacheType: "Redis",
		cacheGroup: "oauth",
		expirationTime: 3600,
		cacheDescription: "OAuth2.0访问令牌和刷新令牌缓存，支持第三方应用授权",
		refreshStrategy: "TTL过期刷新",
		status: "启用",
		createTime: "2024-08-17 07:58:00",
		lastUpdateTime: "2024-09-07 09:18:00",
	},
];

