import type { ParkingSpaceStructureDiagramListItem } from "@01s-11comm/type";

/** Parking Space Structure Diagram 模拟数据 */
export const mockParkingSpaceStructureDiagramData: ParkingSpaceStructureDiagramListItem[] = [
    {
        id: "P001",
        parkingSpaceNumber: "A001",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下一层A区",
        parkingSpaceArea: "12.5",
        parkingSpaceStatus: "已售",
        ownerName: "张三",
        contactPhone: "13812340001",
        licensePlateNumber: "京A12345",
        vehicleBrand: "宝马",
        purchaseTime: "2020-01-15",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 100,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下1层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2020-01-15 09:00:00",
        updateTime: "2024-01-15 09:00:00",
    },
    {
        id: "P002",
        parkingSpaceNumber: "A002",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下一层A区",
        parkingSpaceArea: "12.5",
        parkingSpaceStatus: "已租",
        ownerName: "李四",
        contactPhone: "13812340002",
        licensePlateNumber: "京A23456",
        vehicleBrand: "奔驰",
        purchaseTime: "",
        expiryTime: "2025-01-15",
        monthlyRent: 500,
        managementFee: 100,
        parkingSpaceOrientation: "中间",
        floorArea: "地下1层",
        hasEvChargingPile: true,
        chargingPilePower: "7kW",
        createTime: "2023-01-15 10:30:00",
        updateTime: "2024-01-16 10:30:00",
    },
    {
        id: "P003",
        parkingSpaceNumber: "A003",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下一层A区",
        parkingSpaceArea: "12.5",
        parkingSpaceStatus: "空闲",
        ownerName: "",
        contactPhone: "",
        licensePlateNumber: "",
        vehicleBrand: "",
        purchaseTime: "",
        expiryTime: "",
        monthlyRent: 0,
        managementFee: 100,
        parkingSpaceOrientation: "靠柱",
        floorArea: "地下1层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2019-01-15 11:45:00",
        updateTime: "2024-01-17 11:45:00",
    },
    {
        id: "P004",
        parkingSpaceNumber: "B001",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下二层B区",
        parkingSpaceArea: "14.0",
        parkingSpaceStatus: "已售",
        ownerName: "王五",
        contactPhone: "13812340003",
        licensePlateNumber: "京A34567",
        vehicleBrand: "奥迪",
        purchaseTime: "2021-03-20",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 100,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下2层",
        hasEvChargingPile: true,
        chargingPilePower: "11kW",
        createTime: "2021-03-20 14:00:00",
        updateTime: "2024-01-18 14:20:00",
    },
    {
        id: "P005",
        parkingSpaceNumber: "B002",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下二层B区",
        parkingSpaceArea: "14.0",
        parkingSpaceStatus: "已租",
        ownerName: "赵六",
        contactPhone: "13812340004",
        licensePlateNumber: "京A45678",
        vehicleBrand: "特斯拉",
        purchaseTime: "",
        expiryTime: "2024-06-30",
        monthlyRent: 450,
        managementFee: 100,
        parkingSpaceOrientation: "中间",
        floorArea: "地下2层",
        hasEvChargingPile: true,
        chargingPilePower: "7kW",
        createTime: "2023-06-01 09:00:00",
        updateTime: "2024-01-19 08:15:00",
    },
    {
        id: "P006",
        parkingSpaceNumber: "C001",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下三层C区",
        parkingSpaceArea: "12.0",
        parkingSpaceStatus: "空闲",
        ownerName: "",
        contactPhone: "",
        licensePlateNumber: "",
        vehicleBrand: "",
        purchaseTime: "",
        expiryTime: "",
        monthlyRent: 0,
        managementFee: 80,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下3层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2018-01-01 10:00:00",
        updateTime: "2024-01-20 16:30:00",
    },
    {
        id: "P007",
        parkingSpaceNumber: "C002",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下三层C区",
        parkingSpaceArea: "12.0",
        parkingSpaceStatus: "已售",
        ownerName: "钱七",
        contactPhone: "13812340005",
        licensePlateNumber: "京A56789",
        vehicleBrand: "大众",
        purchaseTime: "2022-05-10",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 80,
        parkingSpaceOrientation: "靠柱",
        floorArea: "地下3层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2022-05-10 15:30:00",
        updateTime: "2024-01-21 13:45:00",
    },
    {
        id: "P008",
        parkingSpaceNumber: "D001",
        parkingSpaceType: "地面车位",
        parkingSpaceLocation: "地面一层D区",
        parkingSpaceArea: "15.0",
        parkingSpaceStatus: "已租",
        ownerName: "孙八",
        contactPhone: "13812340006",
        licensePlateNumber: "京A67890",
        vehicleBrand: "丰田",
        purchaseTime: "",
        expiryTime: "2024-12-31",
        monthlyRent: 300,
        managementFee: 50,
        parkingSpaceOrientation: "露天",
        floorArea: "地面层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2023-01-01 08:00:00",
        updateTime: "2024-01-22 10:00:00",
    },
    {
        id: "P009",
        parkingSpaceNumber: "D002",
        parkingSpaceType: "地面车位",
        parkingSpaceLocation: "地面一层D区",
        parkingSpaceArea: "15.0",
        parkingSpaceStatus: "空闲",
        ownerName: "",
        contactPhone: "",
        licensePlateNumber: "",
        vehicleBrand: "",
        purchaseTime: "",
        expiryTime: "",
        monthlyRent: 0,
        managementFee: 50,
        parkingSpaceOrientation: "露天",
        floorArea: "地面层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2017-01-01 09:00:00",
        updateTime: "2024-01-23 09:30:00",
    },
    {
        id: "P010",
        parkingSpaceNumber: "E001",
        parkingSpaceType: "子母车位",
        parkingSpaceLocation: "地下一层E区",
        parkingSpaceArea: "25.0",
        parkingSpaceStatus: "已售",
        ownerName: "周九",
        contactPhone: "13812340007",
        licensePlateNumber: "京A78901",
        vehicleBrand: "保时捷",
        purchaseTime: "2020-08-15",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 150,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下1层",
        hasEvChargingPile: true,
        chargingPilePower: "22kW",
        createTime: "2020-08-15 11:00:00",
        updateTime: "2024-01-24 11:15:00",
    },
    {
        id: "P011",
        parkingSpaceNumber: "E002",
        parkingSpaceType: "子母车位",
        parkingSpaceLocation: "地下一层E区",
        parkingSpaceArea: "25.0",
        parkingSpaceStatus: "已租",
        ownerName: "吴十",
        contactPhone: "13812340008",
        licensePlateNumber: "京A89012",
        vehicleBrand: "路虎",
        purchaseTime: "",
        expiryTime: "2025-08-15",
        monthlyRent: 800,
        managementFee: 150,
        parkingSpaceOrientation: "中间",
        floorArea: "地下1层",
        hasEvChargingPile: true,
        chargingPilePower: "11kW",
        createTime: "2023-08-15 14:00:00",
        updateTime: "2024-01-25 15:00:00",
    },
    {
        id: "P012",
        parkingSpaceNumber: "F001",
        parkingSpaceType: "无障碍车位",
        parkingSpaceLocation: "地下一层F区",
        parkingSpaceArea: "18.0",
        parkingSpaceStatus: "空闲",
        ownerName: "",
        contactPhone: "",
        licensePlateNumber: "",
        vehicleBrand: "",
        purchaseTime: "",
        expiryTime: "",
        monthlyRent: 0,
        managementFee: 100,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下1层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2019-01-01 10:00:00",
        updateTime: "2024-01-26 08:45:00",
    },
    {
        id: "P013",
        parkingSpaceNumber: "F002",
        parkingSpaceType: "无障碍车位",
        parkingSpaceLocation: "地下一层F区",
        parkingSpaceArea: "18.0",
        parkingSpaceStatus: "已售",
        ownerName: "郑十一",
        contactPhone: "13812340009",
        licensePlateNumber: "京A90123",
        vehicleBrand: "沃尔沃",
        purchaseTime: "2021-06-20",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 100,
        parkingSpaceOrientation: "靠柱",
        floorArea: "地下1层",
        hasEvChargingPile: true,
        chargingPilePower: "7kW",
        createTime: "2021-06-20 16:00:00",
        updateTime: "2024-01-27 14:30:00",
    },
    {
        id: "P014",
        parkingSpaceNumber: "G001",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下二层G区",
        parkingSpaceArea: "13.0",
        parkingSpaceStatus: "已租",
        ownerName: "冯十二",
        contactPhone: "13812340010",
        licensePlateNumber: "京A01234",
        vehicleBrand: "本田",
        purchaseTime: "",
        expiryTime: "2024-07-01",
        monthlyRent: 480,
        managementFee: 100,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下2层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2023-07-01 09:30:00",
        updateTime: "2024-01-28 16:00:00",
    },
    {
        id: "P015",
        parkingSpaceNumber: "G002",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下二层G区",
        parkingSpaceArea: "13.0",
        parkingSpaceStatus: "空闲",
        ownerName: "",
        contactPhone: "",
        licensePlateNumber: "",
        vehicleBrand: "",
        purchaseTime: "",
        expiryTime: "",
        monthlyRent: 0,
        managementFee: 100,
        parkingSpaceOrientation: "中间",
        floorArea: "地下2层",
        hasEvChargingPile: true,
        chargingPilePower: "7kW",
        createTime: "2020-01-01 10:00:00",
        updateTime: "2024-01-29 10:30:00",
    },
    {
        id: "P016",
        parkingSpaceNumber: "H001",
        parkingSpaceType: "地面车位",
        parkingSpaceLocation: "地面二层H区",
        parkingSpaceArea: "14.0",
        parkingSpaceStatus: "已售",
        ownerName: "陈十三",
        contactPhone: "13812340011",
        licensePlateNumber: "京B12345",
        vehicleBrand: "福特",
        purchaseTime: "2022-03-15",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 50,
        parkingSpaceOrientation: "露天",
        floorArea: "架空层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2022-03-15 11:00:00",
        updateTime: "2024-01-30 09:00:00",
    },
    {
        id: "P017",
        parkingSpaceNumber: "H002",
        parkingSpaceType: "地面车位",
        parkingSpaceLocation: "地面二层H区",
        parkingSpaceArea: "14.0",
        parkingSpaceStatus: "已租",
        ownerName: "楚十四",
        contactPhone: "13812340012",
        licensePlateNumber: "京B23456",
        vehicleBrand: "雪佛兰",
        purchaseTime: "",
        expiryTime: "2024-03-31",
        monthlyRent: 280,
        managementFee: 50,
        parkingSpaceOrientation: "露天",
        floorArea: "架空层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2023-04-01 08:00:00",
        updateTime: "2024-01-31 13:15:00",
    },
    {
        id: "P018",
        parkingSpaceNumber: "I001",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下三层I区",
        parkingSpaceArea: "12.5",
        parkingSpaceStatus: "空闲",
        ownerName: "",
        contactPhone: "",
        licensePlateNumber: "",
        vehicleBrand: "",
        purchaseTime: "",
        expiryTime: "",
        monthlyRent: 0,
        managementFee: 80,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下3层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2016-01-01 09:00:00",
        updateTime: "2024-02-01 11:00:00",
    },
    {
        id: "P019",
        parkingSpaceNumber: "I002",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下三层I区",
        parkingSpaceArea: "12.5",
        parkingSpaceStatus: "已售",
        ownerName: "沈十五",
        contactPhone: "13812340013",
        licensePlateNumber: "京B34567",
        vehicleBrand: "现代",
        purchaseTime: "2021-09-10",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 80,
        parkingSpaceOrientation: "靠柱",
        floorArea: "地下3层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2021-09-10 14:30:00",
        updateTime: "2024-02-02 08:30:00",
    },
    {
        id: "P020",
        parkingSpaceNumber: "J001",
        parkingSpaceType: "机械车位",
        parkingSpaceLocation: "地下二层J区",
        parkingSpaceArea: "10.0",
        parkingSpaceStatus: "已租",
        ownerName: "韩十六",
        contactPhone: "13812340014",
        licensePlateNumber: "京B45678",
        vehicleBrand: "比亚迪",
        purchaseTime: "",
        expiryTime: "2024-09-30",
        monthlyRent: 350,
        managementFee: 120,
        parkingSpaceOrientation: "机械车位",
        floorArea: "地下2层",
        hasEvChargingPile: true,
        chargingPilePower: "7kW",
        createTime: "2023-10-01 10:00:00",
        updateTime: "2024-02-03 10:00:00",
    },
    {
        id: "P021",
        parkingSpaceNumber: "J002",
        parkingSpaceType: "机械车位",
        parkingSpaceLocation: "地下二层J区",
        parkingSpaceArea: "10.0",
        parkingSpaceStatus: "空闲",
        ownerName: "",
        contactPhone: "",
        licensePlateNumber: "",
        vehicleBrand: "",
        purchaseTime: "",
        expiryTime: "",
        monthlyRent: 0,
        managementFee: 120,
        parkingSpaceOrientation: "机械车位",
        floorArea: "地下2层",
        hasEvChargingPile: false,
        chargingPilePower: "",
        createTime: "2015-01-01 09:00:00",
        updateTime: "2024-02-04 11:30:00",
    },
    {
        id: "P022",
        parkingSpaceNumber: "K001",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下一层K区",
        parkingSpaceArea: "13.5",
        parkingSpaceStatus: "已售",
        ownerName: "杨十七",
        contactPhone: "13812340015",
        licensePlateNumber: "京B56789",
        vehicleBrand: "蔚来",
        purchaseTime: "2023-01-20",
        expiryTime: "2099-12-31",
        monthlyRent: 0,
        managementFee: 100,
        parkingSpaceOrientation: "靠墙",
        floorArea: "地下1层",
        hasEvChargingPile: true,
        chargingPilePower: "20kW",
        createTime: "2023-01-20 15:00:00",
        updateTime: "2024-02-05 09:00:00",
    },
    {
        id: "P023",
        parkingSpaceNumber: "K002",
        parkingSpaceType: "地下车位",
        parkingSpaceLocation: "地下一层K区",
        parkingSpaceArea: "13.5",
        parkingSpaceStatus: "已租",
        ownerName: "朱十八",
        contactPhone: "13812340016",
        licensePlateNumber: "京B67890",
        vehicleBrand: "理想",
        purchaseTime: "",
        expiryTime: "2024-06-15",
        monthlyRent: 520,
        managementFee: 100,
        parkingSpaceOrientation: "中间",
        floorArea: "地下1层",
        hasEvChargingPile: true,
        chargingPilePower: "7kW",
        createTime: "2023-06-15 08:30:00",
        updateTime: "2024-02-06 14:00:00",
    },
];
